package com.wingedsheep.engine.scenarios

import com.wingedsheep.engine.core.ActivateAbility
import com.wingedsheep.engine.state.components.stack.ChosenTarget
import com.wingedsheep.engine.support.ScenarioTestBase
import com.wingedsheep.sdk.core.Phase
import com.wingedsheep.sdk.core.Step
import io.kotest.assertions.withClue
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe

/**
 * Scenario test for Intrepid Hero (USG #19) — {2}{W} Human Soldier, 1/1.
 *
 * "{T}: Destroy target creature with power 4 or greater."
 *
 * This card is auto-generated by `:mtgish-tooling`. The earliest drafts dropped the "power 4 or
 * greater" target restriction (a bare `TargetFilter.Creature`); this test pins the filter so the
 * ability can only be aimed at a creature with power >= 4.
 */
class IntrepidHeroScenarioTest : ScenarioTestBase() {

    private val intrepidHeroAbilityId =
        cardRegistry.getCard("Intrepid Hero")!!.activatedAbilities.first().id

    init {
        context("Intrepid Hero") {

            test("destroys a target creature with power 4 or greater") {
                val game = scenario()
                    .withPlayers("Player1", "Player2")
                    .withCardOnBattlefield(1, "Intrepid Hero")
                    .withCardOnBattlefield(2, "Craw Wurm") // 6/4, power >= 4
                    .withActivePlayer(1)
                    .inPhase(Phase.PRECOMBAT_MAIN, Step.PRECOMBAT_MAIN)
                    .build()

                val hero = game.findPermanent("Intrepid Hero")!!
                val wurm = game.findPermanent("Craw Wurm")!!

                val activation = game.execute(
                    ActivateAbility(
                        playerId = game.player1Id,
                        sourceId = hero,
                        abilityId = intrepidHeroAbilityId,
                        targets = listOf(ChosenTarget.Permanent(wurm)),
                    )
                )
                withClue("Activating Intrepid Hero on a power-6 creature should succeed: ${activation.error}") {
                    activation.error shouldBe null
                }
                game.resolveStack()

                withClue("Craw Wurm (power 6) is destroyed") {
                    game.findPermanent("Craw Wurm") shouldBe null
                    game.findCardsInGraveyard(2, "Craw Wurm").size shouldBe 1
                }
            }

            test("cannot target a creature with power less than 4") {
                val game = scenario()
                    .withPlayers("Player1", "Player2")
                    .withCardOnBattlefield(1, "Intrepid Hero")
                    .withCardOnBattlefield(2, "Hill Giant") // 3/3, power < 4
                    .withActivePlayer(1)
                    .inPhase(Phase.PRECOMBAT_MAIN, Step.PRECOMBAT_MAIN)
                    .build()

                val hero = game.findPermanent("Intrepid Hero")!!
                val giant = game.findPermanent("Hill Giant")!!

                val activation = game.execute(
                    ActivateAbility(
                        playerId = game.player1Id,
                        sourceId = hero,
                        abilityId = intrepidHeroAbilityId,
                        targets = listOf(ChosenTarget.Permanent(giant)),
                    )
                )
                withClue("Intrepid Hero must not be able to target a power-3 creature") {
                    activation.error shouldNotBe null
                }
                withClue("Hill Giant (power 3) survives") {
                    game.findPermanent("Hill Giant") shouldNotBe null
                }
            }
        }
    }
}
