// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.p02.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Angelic Wall
 * {1}{W}
 * Creature — Wall
 * 0/4
 * Defender (This creature can't attack.)
 * Flying
 */
val AngelicWall = card("Angelic Wall") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Wall"
    oracleText = "Defender (This creature can't attack.)\nFlying"
    power = 0
    toughness = 4
    keywords(Keyword.DEFENDER, Keyword.FLYING)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "10"
        artist = "Rebecca Guay"
        flavorText = "Be at peace, and observe its beauty. Be at war, and feel its justice."
        imageUri = "https://cards.scryfall.io/normal/front/e/0/e0bb39fb-29fc-4e69-9918-47277b8af0d3.jpg"
    }
}
