// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rix.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Brass's Bounty
 * {6}{R}
 * Sorcery
 * For each land you control, create a Treasure token. (It's an artifact with "{T}, Sacrifice this token: Add one mana of any color.")
 */
val BrasssBounty = card("Brass's Bounty") {
    manaCost = "{6}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "For each land you control, create a Treasure token. (It's an artifact with \"{T}, Sacrifice this token: Add one mana of any color.\")"
    spell {
        effect = Effects.CreateTreasure(count = DynamicAmount.AggregateBattlefield(Player.You, GameObjectFilter.Land))
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "94"
        artist = "Grzegorz Rutkowski"
        flavorText = "\"Why squabble for trinkets when we could be living large off all this gold?\"\n—Admiral Beckett Brass"
        imageUri = "https://cards.scryfall.io/normal/front/1/3/13505866-6ce9-4d11-b3f3-fc2f09839b71.jpg"
    }
}
