// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rix.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Brazen Freebooter
 * {3}{R}
 * Creature — Human Pirate
 * 3/3
 * When this creature enters, create a Treasure token. (It's an artifact with "{T}, Sacrifice this token: Add one mana of any color.")
 */
val BrazenFreebooter = card("Brazen Freebooter") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Human Pirate"
    oracleText = "When this creature enters, create a Treasure token. (It's an artifact with \"{T}, Sacrifice this token: Add one mana of any color.\")"
    power = 3
    toughness = 3
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.CreateTreasure(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "95"
        artist = "Randy Gallegos"
        flavorText = "Finders, keepers."
        imageUri = "https://cards.scryfall.io/normal/front/a/e/aeb3d3b6-6805-4476-aea1-a95c31bd21d7.jpg"
    }
}
