// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rix.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Zetalpa, Primal Dawn
 * {6}{W}{W}
 * Legendary Creature — Elder Dinosaur
 * 4/8
 * Flying, double strike, vigilance, trample, indestructible
 */
val ZetalpaPrimalDawn = card("Zetalpa, Primal Dawn") {
    manaCost = "{6}{W}{W}"
    colorIdentity = "W"
    typeLine = "Legendary Creature — Elder Dinosaur"
    oracleText = "Flying, double strike, vigilance, trample, indestructible"
    power = 4
    toughness = 8
    keywords(Keyword.FLYING, Keyword.DOUBLE_STRIKE, Keyword.VIGILANCE, Keyword.TRAMPLE, Keyword.INDESTRUCTIBLE)
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "30"
        artist = "Chris Rallis"
        flavorText = "The sky takes flight and the earth trembles."
        imageUri = "https://cards.scryfall.io/normal/front/3/d/3d10560f-199d-4d04-b573-90024f8aecc4.jpg"
    }
}
