// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.IfYouDoEffect
import com.wingedsheep.sdk.scripting.effects.MayEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Incinerating Blast
 * {4}{R}
 * Sorcery
 * Incinerating Blast deals 6 damage to target creature.
 * You may discard a card. If you do, draw a card.
 */
val IncineratingBlast = card("Incinerating Blast") {
    manaCost = "{4}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Incinerating Blast deals 6 damage to target creature.\nYou may discard a card. If you do, draw a card."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            DealDamageEffect(6, t),
            MayEffect(effect = IfYouDoEffect(action = Patterns.Hand.discardCards(1), ifYouDo = DrawCardsEffect(1)))
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "90"
        artist = "Zoltan Boros"
        flavorText = "Most pyromancers could never summon the sheer heat necessary to melt solid rock, but most pyromancers aren't Chandra Nalaar."
        imageUri = "https://cards.scryfall.io/normal/front/d/5/d58e20ab-c5ca-4295-884d-78efdaa83243.jpg"
    }
}
