// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Filters
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ConditionalStaticAbility
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Inspiring Paladin
 * {2}{W}
 * Creature — Human Knight
 * 3/3
 * During your turn, this creature has first strike. (It deals combat damage before creatures without first strike.)
 * During your turn, creatures you control with +1/+1 counters on them have first strike.
 */
val InspiringPaladin = card("Inspiring Paladin") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Knight"
    oracleText = "During your turn, this creature has first strike. (It deals combat damage before creatures without first strike.)\nDuring your turn, creatures you control with +1/+1 counters on them have first strike."
    power = 3
    toughness = 3
    staticAbility {
        ability = ConditionalStaticAbility(
            ability = GrantKeyword(Keyword.FIRST_STRIKE, Filters.Self),
            condition = Conditions.IsYourTurn
        )
    }
    staticAbility {
        condition = Conditions.IsYourTurn
        ability = GrantKeyword(
            Keyword.FIRST_STRIKE,
            GroupFilter(GameObjectFilter.Creature.withCounter(Counters.PLUS_ONE_PLUS_ONE).youControl())
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "18"
        artist = "Valera Lutfullina"
        flavorText = "As the line faltered, the thunder of hoofbeats heralded desperately needed aid."
        imageUri = "https://cards.scryfall.io/normal/front/0/7/0763be06-25b2-4d6b-ab33-a1af85aeb443.jpg"
    }
}
