// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Vanguard Seraph
 * {3}{W}
 * Creature — Angel Warrior
 * 3/3
 * Flying
 * Whenever you gain life for the first time each turn, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
 */
val VanguardSeraph = card("Vanguard Seraph") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Angel Warrior"
    oracleText = "Flying\nWhenever you gain life for the first time each turn, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)"
    power = 3
    toughness = 3
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.YouGainLifeFirstTimeEachTurn
        effect = Patterns.Library.surveil(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "28"
        artist = "Zezhou Chen"
        flavorText = "She guides expedition parties through the perilous floating ruins of Zendikar's ancient empires."
        imageUri = "https://cards.scryfall.io/normal/front/4/3/4329c861-fc16-4a96-9c03-25af6ac2adc8.jpg"
    }
}
