// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tor.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Compulsion
 * {1}{U}
 * Enchantment
 * {1}{U}, Discard a card: Draw a card.
 * {1}{U}, Sacrifice this enchantment: Draw a card.
 */
val Compulsion = card("Compulsion") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Enchantment"
    oracleText = "{1}{U}, Discard a card: Draw a card.\n{1}{U}, Sacrifice this enchantment: Draw a card."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}{U}"), Costs.DiscardCard)
        effect = DrawCardsEffect(1)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}{U}"), Costs.SacrificeSelf)
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "34"
        artist = "Christopher Moeller"
        imageUri = "https://cards.scryfall.io/normal/front/2/d/2d1f56e8-55cb-4b81-9946-9f0f813e3d4a.jpg"
    }
}
