// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tor.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Hypochondria
 * {1}{W}
 * Enchantment
 * {W}, Discard a card: Prevent the next 3 damage that would be dealt to any target this turn.
 * {W}, Sacrifice this enchantment: Prevent the next 3 damage that would be dealt to any target this turn.
 */
val Hypochondria = card("Hypochondria") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment"
    oracleText = "{W}, Discard a card: Prevent the next 3 damage that would be dealt to any target this turn.\n{W}, Sacrifice this enchantment: Prevent the next 3 damage that would be dealt to any target this turn."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{W}"), Costs.DiscardCard)
        val t = target("target", AnyTarget())
        effect = Effects.PreventNextDamage(3, t)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{W}"), Costs.SacrificeSelf)
        val t = target("target", AnyTarget())
        effect = Effects.PreventNextDamage(3, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "7"
        artist = "Christopher Moeller"
        imageUri = "https://cards.scryfall.io/normal/front/3/4/3467c940-dae4-4667-bec8-524dbce13283.jpg"
    }
}
