// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tor.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Nantuko Shade
 * {B}{B}
 * Creature — Insect Shade
 * 2/1
 * {B}: This creature gets +1/+1 until end of turn.
 */
val NantukoShade = card("Nantuko Shade") {
    manaCost = "{B}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Insect Shade"
    oracleText = "{B}: This creature gets +1/+1 until end of turn."
    power = 2
    toughness = 1
    activatedAbility {
        cost = Costs.Mana("{B}")
        effect = Effects.ModifyStats(1, 1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "74"
        artist = "Brian Snõddy"
        flavorText = "\"If the Nantuko only knew what awaits them beyond death, they would abandon all they hold dear.\"\n—Cabal Patriarch"
        imageUri = "https://cards.scryfall.io/normal/front/2/e/2ed9dc9c-b92b-4305-8c54-1a63f750f8d1.jpg"
    }
}
