// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tor.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Pyromania
 * {2}{R}
 * Enchantment
 * {1}{R}, Discard a card at random: This enchantment deals 1 damage to any target.
 * {1}{R}, Sacrifice this enchantment: It deals 1 damage to any target.
 */
val Pyromania = card("Pyromania") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Enchantment"
    oracleText = "{1}{R}, Discard a card at random: This enchantment deals 1 damage to any target.\n{1}{R}, Sacrifice this enchantment: It deals 1 damage to any target."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}{R}"), Costs.DiscardAtRandom(1))
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(1, t)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}{R}"), Costs.SacrificeSelf)
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(1, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "112"
        artist = "Christopher Moeller"
        imageUri = "https://cards.scryfall.io/normal/front/6/a/6a5af4e9-a2b6-43c7-8ff4-e761fbf693a7.jpg"
    }
}
