// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Deadapult
 * {2}{R}
 * Enchantment
 * {R}, Sacrifice a Zombie: This enchantment deals 2 damage to any target.
 */
val Deadapult = card("Deadapult") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Enchantment"
    oracleText = "{R}, Sacrifice a Zombie: This enchantment deals 2 damage to any target."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{R}"), Costs.Sacrifice(GameObjectFilter.Permanent.withSubtype("Zombie")))
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(2, t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "59"
        artist = "Mark Brill"
        flavorText = "\"Nothing ruins your day like a blazing zombie.\"\n—Tahngarth"
        imageUri = "https://cards.scryfall.io/normal/front/b/d/bdc93b3d-bde4-422f-9edc-e337719be7b4.jpg"
    }
}
