// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.CounterEffect
import com.wingedsheep.sdk.scripting.targets.TargetSpell


/**
 * Ertai, the Corrupted
 * {2}{W}{U}{B}
 * Legendary Creature — Phyrexian Human Wizard
 * 3/4
 * {U}, {T}, Sacrifice a creature or enchantment: Counter target spell.
 */
val ErtaiTheCorrupted = card("Ertai, the Corrupted") {
    manaCost = "{2}{W}{U}{B}"
    colorIdentity = "WUB"
    typeLine = "Legendary Creature — Phyrexian Human Wizard"
    oracleText = "{U}, {T}, Sacrifice a creature or enchantment: Counter target spell."
    power = 3
    toughness = 4
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{U}"), Costs.Tap, Costs.Sacrifice(GameObjectFilter.CreatureOrEnchantment))
        val t = target("target", TargetSpell())
        effect = CounterEffect()
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "107"
        artist = "Mark Tedin"
        flavorText = "Altered by Phyrexian science, corrupted by black mana, and twisted by rage, Ertai still looked in the mirror and saw only glory."
        imageUri = "https://cards.scryfall.io/normal/front/6/6/66b950d9-8fef-4deb-b51b-26edb90abc56.jpg"
    }
}
