// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.ZonePlacement
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Hunting Drake
 * {4}{U}
 * Creature — Drake
 * 2/2
 * Flying
 * When this creature enters, put target red or green creature on top of its owner's library.
 */
val HuntingDrake = card("Hunting Drake") {
    manaCost = "{4}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Drake"
    oracleText = "Flying\nWhen this creature enters, put target red or green creature on top of its owner's library."
    power = 2
    toughness = 2
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.withAnyColor(Color.RED, Color.GREEN)))
        effect = Effects.Move(t, Zone.LIBRARY, ZonePlacement.Top)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "27"
        artist = "Wayne England"
        flavorText = "Even the fiercest beast will flee when faced with the possibility of becoming dinner."
        imageUri = "https://cards.scryfall.io/normal/front/5/b/5b0293a9-48fe-4018-bd25-3e02c227a3dd.jpg"
    }
}
