// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Implode
 * {4}{R}
 * Sorcery
 * Destroy target land.
 * Draw a card.
 */
val Implode = card("Implode") {
    manaCost = "{4}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Destroy target land.\nDraw a card."
    spell {
        val t = target("target", TargetPermanent(filter = TargetFilter.Land))
        effect = Effects.Composite(
            Effects.Move(t, Zone.GRAVEYARD, byDestruction = true),
            DrawCardsEffect(1)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "62"
        artist = "Arnie Swekel"
        flavorText = "To save Dominaria, nine planeswalkers sought the annihilation of Phyrexia itself."
        imageUri = "https://cards.scryfall.io/normal/front/a/7/a76ee318-8126-4ebf-884d-8369ae8726ac.jpg"
    }
}
