// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Mana Cylix
 * {1}
 * Artifact
 * {1}, {T}: Add one mana of any color.
 */
val ManaCylix = card("Mana Cylix") {
    manaCost = "{1}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{1}, {T}: Add one mana of any color."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}"), Costs.Tap)
        effect = Effects.AddManaOfChoice()
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "132"
        artist = "Donato Giancola"
        flavorText = "Overflowing with visions of the possible future, it lends power to those in the present."
        imageUri = "https://cards.scryfall.io/normal/front/c/6/c6f95767-afda-4d74-bbd4-1b702eeae54b.jpg"
    }
}
