// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Skyshroud Blessing
 * {1}{G}
 * Instant
 * All lands gain shroud until end of turn. (They can't be the targets of spells or abilities.)
 * Draw a card.
 */
val SkyshroudBlessing = card("Skyshroud Blessing") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "All lands gain shroud until end of turn. (They can't be the targets of spells or abilities.)\nDraw a card."
    spell {
        effect = Effects.Composite(
            Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Land),
                Effects.GrantKeyword(Keyword.SHROUD, EffectTarget.Self)
            ),
            DrawCardsEffect(1)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "92"
        artist = "Jerry Tiritilli"
        flavorText = "\"Behold,\" said Freyalise to Eladamri. \"Your Skyshroud home has followed you to Dominaria.\""
        imageUri = "https://cards.scryfall.io/normal/front/c/0/c0c10b16-97b1-4a36-b2b4-f0c28ead3eb4.jpg"
    }
}
