// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Slingshot Goblin
 * {2}{R}
 * Creature — Goblin
 * 2/2
 * {R}, {T}: This creature deals 2 damage to target blue creature.
 */
val SlingshotGoblin = card("Slingshot Goblin") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Goblin"
    oracleText = "{R}, {T}: This creature deals 2 damage to target blue creature."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{R}"), Costs.Tap)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.withColor(Color.BLUE)))
        effect = DealDamageEffect(2, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "72"
        artist = "Jeff Easley"
        flavorText = "It's most effective when it doesn't eat the ammunition."
        imageUri = "https://cards.scryfall.io/normal/front/8/1/81825aef-bef7-46b7-bf52-29e32c1836b0.jpg"
    }
}
