// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Stone Kavu
 * {4}{G}
 * Creature — Kavu
 * 3/3
 * {R}: This creature gets +1/+0 until end of turn.
 * {W}: This creature gets +0/+1 until end of turn.
 */
val StoneKavu = card("Stone Kavu") {
    manaCost = "{4}{G}"
    colorIdentity = "WRG"
    typeLine = "Creature — Kavu"
    oracleText = "{R}: This creature gets +1/+0 until end of turn.\n{W}: This creature gets +0/+1 until end of turn."
    power = 3
    toughness = 3
    activatedAbility {
        cost = Costs.Mana("{R}")
        effect = Effects.ModifyStats(1, 0, EffectTarget.Self)
    }
    activatedAbility {
        cost = Costs.Mana("{W}")
        effect = Effects.ModifyStats(0, 1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "93"
        artist = "Adam Rex"
        flavorText = "To maintain its hide, it consumes a variety of rocks—not to mention a variety of Phyrexians."
        imageUri = "https://cards.scryfall.io/normal/front/3/6/36a1cdca-d48c-4936-ad6a-4610aeb991ce.jpg"
    }
}
