// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Strafe
 * {R}
 * Sorcery
 * Strafe deals 3 damage to target nonred creature.
 */
val Strafe = card("Strafe") {
    manaCost = "{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Strafe deals 3 damage to target nonred creature."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.notColor(Color.RED)))
        effect = DealDamageEffect(3, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "73"
        artist = "Jim Nelson"
        flavorText = "\"All right, let's light 'em up!\"\n—Gerrard"
        imageUri = "https://cards.scryfall.io/normal/front/e/c/ec8b77cf-9c1e-4c8f-b452-295cc1570d0e.jpg"
    }
}
