// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Terminate
 * {B}{R}
 * Instant
 * Destroy target creature. It can't be regenerated.
 */
val Terminate = card("Terminate") {
    manaCost = "{B}{R}"
    colorIdentity = "BR"
    typeLine = "Instant"
    oracleText = "Destroy target creature. It can't be regenerated."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Destroy(t, noRegenerate = true)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "128"
        artist = "DiTerlizzi"
        flavorText = "Like his mother before him, Darigaaz gave his life defending Dominaria from the tyranny of self-styled \"gods.\""
        imageUri = "https://cards.scryfall.io/normal/front/1/9/190ca502-672d-4cc0-b6e0-b9de517058d0.jpg"
    }
}
