// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.znr.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Marauding Blight-Priest
 * {2}{B}
 * Creature — Vampire Cleric
 * 3/2
 * Whenever you gain life, each opponent loses 1 life.
 */
val MaraudingBlightPriest = card("Marauding Blight-Priest") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Vampire Cleric"
    oracleText = "Whenever you gain life, each opponent loses 1 life."
    power = 3
    toughness = 2
    triggeredAbility {
        trigger = Triggers.YouGainLife
        effect = Effects.LoseLife(1, EffectTarget.PlayerRef(Player.EachOpponent))
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "112"
        artist = "Caio Monteiro"
        flavorText = "\"The vampires never had gods. We followed our bloodchiefs. Now they are gone. What is left? Destruction and death, my friends. That is enough.\""
        imageUri = "https://cards.scryfall.io/normal/front/7/3/730ddbcd-0814-4e22-85e9-78b0878324b6.jpg"
    }
}
