// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Air Elemental
 * {3}{U}{U}
 * Creature — Elemental
 * 4/4
 * Flying
 */
val AirElemental = card("Air Elemental") {
    manaCost = "{3}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Elemental"
    oracleText = "Flying"
    power = 4
    toughness = 4
    keywords(Keyword.FLYING)
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "46"
        artist = "Richard Thomas"
        flavorText = "These spirits of the air are winsome and wild, and cannot be truly contained. Only marginally intelligent, they often substitute whimsy for strategy, delighting in mischief and mayhem."
        imageUri = "https://cards.scryfall.io/normal/front/6/9/69c3b2a3-0daa-4d42-832d-fcdfda6555ea.jpg"
    }
}
