// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.targets.TargetPlayer


/**
 * Ancestral Recall
 * {U}
 * Instant
 * Target player draws three cards.
 */
val AncestralRecall = card("Ancestral Recall") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Target player draws three cards."
    spell {
        val t = target("target", TargetPlayer())
        effect = DrawCardsEffect(3, t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "47"
        artist = "Mark Poole"
        imageUri = "https://cards.scryfall.io/normal/front/7/0/70e7ddf2-5604-41e7-bb9d-ddd03d3e9d0b.jpg"
    }
}
