// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Castle
 * {3}{W}
 * Enchantment
 * Untapped creatures you control get +0/+2.
 */
val Castle = card("Castle") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment"
    oracleText = "Untapped creatures you control get +0/+2."
    staticAbility {
        ability = ModifyStats(
            powerBonus = 0,
            toughnessBonus = 2,
            filter = GroupFilter(GameObjectFilter.Creature.untapped().youControl())
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "9"
        artist = "Dameon Willich"
        imageUri = "https://cards.scryfall.io/normal/front/b/0/b0da8d56-3178-44c2-9344-95d2346d326f.jpg"
    }
}
