// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.CounterEffect
import com.wingedsheep.sdk.scripting.targets.TargetSpell


/**
 * Counterspell
 * {U}{U}
 * Instant
 * Counter target spell.
 */
val Counterspell = card("Counterspell") {
    manaCost = "{U}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Counter target spell."
    spell {
        val t = target("target", TargetSpell())
        effect = CounterEffect()
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "54"
        artist = "Mark Poole"
        imageUri = "https://cards.scryfall.io/normal/front/0/d/0df55e3f-14de-46ef-b6b1-616618724d9e.jpg"
    }
}
