// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Crusade
 * {W}{W}
 * Enchantment
 * White creatures get +1/+1.
 */
val Crusade = card("Crusade") {
    manaCost = "{W}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment"
    oracleText = "White creatures get +1/+1."
    staticAbility {
        ability = ModifyStats(
            powerBonus = 1,
            toughnessBonus = 1,
            filter = GroupFilter(GameObjectFilter.Creature.withColor(Color.WHITE))
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "16"
        artist = "Mark Poole"
        imageUri = "https://cards.scryfall.io/normal/front/0/5/057986c7-20c0-4157-b4df-beae4ef5c66d.jpg"
    }
}
