// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Fog
 * {G}
 * Instant
 * Prevent all combat damage that would be dealt this turn.
 */
val Fog = card("Fog") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Prevent all combat damage that would be dealt this turn."
    spell {
        effect = Effects.PreventAllCombatDamage()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "193"
        artist = "Jesper Myrfors"
        imageUri = "https://cards.scryfall.io/normal/front/c/f/cfba606d-bb55-43ba-aa0c-299649958788.jpg"
    }
}
