// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.LookAtTargetHandEffect
import com.wingedsheep.sdk.scripting.targets.TargetPlayer


/**
 * Glasses of Urza
 * {1}
 * Artifact
 * {T}: Look at target player's hand.
 */
val GlassesOfUrza = card("Glasses of Urza") {
    manaCost = "{1}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{T}: Look at target player's hand."
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", TargetPlayer())
        effect = LookAtTargetHandEffect(t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "245"
        artist = "Douglas Shuler"
        imageUri = "https://cards.scryfall.io/normal/front/c/a/cafc2350-5d64-4379-9198-79a114654d45.jpg"
    }
}
