// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Goblin Balloon Brigade
 * {R}
 * Creature — Goblin Warrior
 * 1/1
 * {R}: This creature gains flying until end of turn.
 */
val GoblinBalloonBrigade = card("Goblin Balloon Brigade") {
    manaCost = "{R}"
    colorIdentity = "R"
    typeLine = "Creature — Goblin Warrior"
    oracleText = "{R}: This creature gains flying until end of turn."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Mana("{R}")
        effect = Effects.GrantKeyword(Keyword.FLYING, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "153"
        artist = "Andi Rusu"
        flavorText = "\"From up here we can drop rocks and arrows and more rocks!\" \"Uh, yeah boss, but how do we get down?\""
        imageUri = "https://cards.scryfall.io/normal/front/5/1/5129b422-7a35-4bc5-b14b-c814012a0d8f.jpg"
    }
}
