// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Gray Ogre
 * {2}{R}
 * Creature — Ogre
 * 2/2
 */
val GrayOgre = card("Gray Ogre") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Ogre"
    power = 2
    toughness = 2
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "156"
        artist = "Dan Frazier"
        flavorText = "The Ogre philosopher Gnerdel believed the purpose of life was to live as high on the food chain as possible. She refused to eat vegetarians, and preferred to live entirely on creatures that preyed on sentient beings."
        imageUri = "https://cards.scryfall.io/normal/front/7/3/73ae5276-b607-4f23-a9d2-e8cc7b8e3693.jpg"
    }
}
