// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ModifyStats


/**
 * Holy Strength
 * {W}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature gets +1/+2.
 */
val HolyStrength = card("Holy Strength") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature gets +1/+2."
    auraTarget = Targets.Creature
    staticAbility {
        ability = ModifyStats(1, 2)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "24"
        artist = "Anson Maddocks"
        imageUri = "https://cards.scryfall.io/normal/front/e/9/e945a4cd-0eb1-4f54-898d-169ce2748a03.jpg"
    }
}
