// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Ice Storm
 * {2}{G}
 * Sorcery
 * Destroy target land.
 */
val IceStorm = card("Ice Storm") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "Destroy target land."
    spell {
        val t = target("target", TargetPermanent(filter = TargetFilter.Land))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "201"
        artist = "Dan Frazier"
        imageUri = "https://cards.scryfall.io/normal/front/9/9/9914836e-2fa6-4390-94b2-431427848a54.jpg"
    }
}
