// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Jump
 * {U}
 * Instant
 * Target creature gains flying until end of turn.
 */
val Jump = card("Jump") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Target creature gains flying until end of turn."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.GrantKeyword(Keyword.FLYING, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "60"
        artist = "Mark Poole"
        imageUri = "https://cards.scryfall.io/normal/front/c/b/cb3f4b11-ad1b-48e2-a500-787d351b0174.jpg"
    }
}
