// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Lightning Bolt
 * {R}
 * Instant
 * Lightning Bolt deals 3 damage to any target.
 */
val LightningBolt = card("Lightning Bolt") {
    manaCost = "{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Lightning Bolt deals 3 damage to any target."
    spell {
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(3, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "161"
        artist = "Christopher Rush"
        imageUri = "https://cards.scryfall.io/normal/front/d/5/d573ef03-4730-45aa-93dd-e45ac1dbaf4a.jpg"
    }
}
