// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.RegenerateEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Living Wall
 * {4}
 * Artifact Creature — Wall
 * 0/6
 * Defender (This creature can't attack.)
 * {1}: Regenerate this creature.
 */
val LivingWall = card("Living Wall") {
    manaCost = "{4}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Wall"
    oracleText = "Defender (This creature can't attack.)\n{1}: Regenerate this creature."
    power = 0
    toughness = 6
    keywords(Keyword.DEFENDER)
    activatedAbility {
        cost = Costs.Mana("{1}")
        effect = RegenerateEffect(EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "258"
        artist = "Anson Maddocks"
        flavorText = "Some fiendish mage had created a horrifying wall of living flesh, patched together from a jumble of still-recognizable body parts. As we sought to hew our way through it, some unknown power healed the gaping wounds we cut, denying us passage."
        imageUri = "https://cards.scryfall.io/normal/front/4/a/4a98ada6-923a-44a5-bdef-ea6a160b481e.jpg"
    }
}
