// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Mahamoti Djinn
 * {4}{U}{U}
 * Creature — Djinn
 * 5/6
 * Flying (This creature can't be blocked except by creatures with flying or reach.)
 */
val MahamotiDjinn = card("Mahamoti Djinn") {
    manaCost = "{4}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Djinn"
    oracleText = "Flying (This creature can't be blocked except by creatures with flying or reach.)"
    power = 5
    toughness = 6
    keywords(Keyword.FLYING)
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "64"
        artist = "Dan Frazier"
        flavorText = "Of royal blood among the spirits of the air, the Mahamoti Djinn rides on the wings of the winds. As dangerous in the gambling hall as he is in battle, he is a master of trickery and misdirection."
        imageUri = "https://cards.scryfall.io/normal/front/3/6/36204ddd-ddf7-4b44-ae3c-b4a5a41ac9cb.jpg"
    }
}
