// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Northern Paladin
 * {2}{W}{W}
 * Creature — Human Knight
 * 3/3
 * {W}{W}, {T}: Destroy target black permanent.
 */
val NorthernPaladin = card("Northern Paladin") {
    manaCost = "{2}{W}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Knight"
    oracleText = "{W}{W}, {T}: Destroy target black permanent."
    power = 3
    toughness = 3
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{W}{W}"), Costs.Tap)
        val t = target("target", TargetPermanent(filter = TargetFilter.Permanent.withColor(Color.BLACK)))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "29"
        artist = "Douglas Shuler"
        flavorText = "\"Look to the north; there you will find aid and comfort.\" —The Book of Tal"
        imageUri = "https://cards.scryfall.io/normal/front/6/3/6303233b-35eb-49ca-b844-ba6b9fe1cbd2.jpg"
    }
}
