// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Plateau
 * Land — Mountain Plains
 * ({T}: Add {R} or {W}.)
 */
val Plateau = card("Plateau") {
    manaCost = ""
    colorIdentity = "WR"
    typeLine = "Land — Mountain Plains"
    oracleText = "({T}: Add {R} or {W}.)"
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "279"
        artist = "Drew Tucker"
        imageUri = "https://cards.scryfall.io/normal/front/6/e/6eafa00b-c628-40f6-86eb-88e1361fc7a0.jpg"
    }
}
