// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Prodigal Sorcerer
 * {2}{U}
 * Creature — Human Wizard Sorcerer
 * 1/1
 * {T}: This creature deals 1 damage to any target.
 */
val ProdigalSorcerer = card("Prodigal Sorcerer") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Wizard Sorcerer"
    oracleText = "{T}: This creature deals 1 damage to any target."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(1, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "73"
        artist = "Douglas Shuler"
        flavorText = "Occasionally a member of the Institute of Arcane Study acquires a taste for worldly pleasures. Seldom do they have trouble finding employment."
        imageUri = "https://cards.scryfall.io/normal/front/e/4/e4dc1103-7bf1-47f6-9006-d3ed9ccd7a6a.jpg"
    }
}
