// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent
import com.wingedsheep.sdk.scripting.targets.TargetSpell


/**
 * Red Elemental Blast
 * {R}
 * Instant
 * Choose one —
 * • Counter target blue spell.
 * • Destroy target blue permanent.
 */
val RedElementalBlast = card("Red Elemental Blast") {
    manaCost = "{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Choose one —\n• Counter target blue spell.\n• Destroy target blue permanent."
    spell {
        modal(chooseCount = 1) {
            mode("Counter target blue spell") {
                val t = target("target", TargetSpell(filter = TargetFilter.SpellOnStack.withColor(Color.BLUE)))
                effect = Effects.CounterSpell()
            }
            mode("Destroy target blue permanent") {
                val t = target("target", TargetPermanent(filter = TargetFilter.Permanent.withColor(Color.BLUE)))
                effect = Effects.Destroy(t)
            }
        }
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "169"
        artist = "Richard Thomas"
        imageUri = "https://cards.scryfall.io/normal/front/7/7/776ad9be-3309-4f1d-9f27-6219d9477662.jpg"
    }
}
