// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GrantProtection


/**
 * Red Ward
 * {W}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature has protection from red. This effect doesn't remove this Aura.
 */
val RedWard = card("Red Ward") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature has protection from red. This effect doesn't remove this Aura."
    auraTarget = Targets.Creature
    staticAbility {
        ability = GrantProtection(Color.RED)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "33"
        artist = "Dan Frazier"
        imageUri = "https://cards.scryfall.io/normal/front/e/0/e0c64c01-c2aa-470b-88c6-3d3e4a969649.jpg"
    }
}
