// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Resurrection
 * {2}{W}{W}
 * Sorcery
 * Return target creature card from your graveyard to the battlefield.
 */
val Resurrection = card("Resurrection") {
    manaCost = "{2}{W}{W}"
    colorIdentity = "W"
    typeLine = "Sorcery"
    oracleText = "Return target creature card from your graveyard to the battlefield."
    spell {
        val t = target("target", TargetObject(filter = TargetFilter.CreatureInYourGraveyard))
        effect = Effects.Move(t, Zone.BATTLEFIELD, fromZone = Zone.GRAVEYARD)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "34"
        artist = "Dan Frazier"
        imageUri = "https://cards.scryfall.io/normal/front/4/f/4fff6e6f-4ebd-4ec8-9443-59efb22d376c.jpg"
    }
}
