// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Savannah
 * Land — Forest Plains
 * ({T}: Add {G} or {W}.)
 */
val Savannah = card("Savannah") {
    manaCost = ""
    colorIdentity = "WG"
    typeLine = "Land — Forest Plains"
    oracleText = "({T}: Add {G} or {W}.)"
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "280"
        artist = "Rob Alexander"
        imageUri = "https://cards.scryfall.io/normal/front/9/4/94f7e24c-2546-41b6-81ad-5e920b07e64e.jpg"
    }
}
