// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.CounterEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetSpell


/**
 * Spell Blast
 * {X}{U}
 * Instant
 * Counter target spell with mana value X. (For example, if that spell's mana cost is {3}{U}{U}, X is 5.)
 */
val SpellBlast = card("Spell Blast") {
    manaCost = "{X}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Counter target spell with mana value X. (For example, if that spell's mana cost is {3}{U}{U}, X is 5.)"
    spell {
        val t = target("target", TargetSpell(filter = TargetFilter.SpellOnStack.manaValueEqualsX()))
        effect = CounterEffect()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "79"
        artist = "Brian Snõddy"
        imageUri = "https://cards.scryfall.io/normal/front/8/4/845734da-ab03-4dbc-bb5f-96481d3b8e88.jpg"
    }
}
