// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Stone Rain
 * {2}{R}
 * Sorcery
 * Destroy target land.
 */
val StoneRain = card("Stone Rain") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    spell {
        val t = target("target", TargetPermanent(filter = TargetFilter.Land))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "177"
        artist = "Daniel Gelon"
        imageUri = "https://cards.scryfall.io/normal/front/5/7/57ff74cb-a2ed-4123-ac42-f72f9820049e.jpg"
    }
}
