// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Timber Wolves
 * {G}
 * Creature — Wolf
 * 1/1
 * Banding (Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creature's combat damage, not its controller, among any of the creatures it's being blocked by or is blocking.)
 */
val TimberWolves = card("Timber Wolves") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Creature — Wolf"
    oracleText = "Banding (Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creature's combat damage, not its controller, among any of the creatures it's being blocked by or is blocking.)"
    power = 1
    toughness = 1
    keywords(Keyword.BANDING)
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "219"
        artist = "Melissa A. Benson"
        flavorText = "Though many think of Wolves as solitary predators, they are actually extremely social animals. During a hunt they often call to each other, which can be quite unsettling for their prey."
        imageUri = "https://cards.scryfall.io/normal/front/b/c/bc2570a4-eef9-430d-b6c2-cd51d29b9d01.jpg"
    }
}
