// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.TakeExtraTurnEffect


/**
 * Time Walk
 * {1}{U}
 * Sorcery
 * Take an extra turn after this one.
 */
val TimeWalk = card("Time Walk") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Take an extra turn after this one."
    spell {
        effect = TakeExtraTurnEffect()
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "83"
        artist = "Amy Weber"
        imageUri = "https://cards.scryfall.io/normal/front/e/0/e0139f60-d48e-46fb-9f5a-1e3d7558c834.jpg"
    }
}
