// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Tranquility
 * {2}{G}
 * Sorcery
 * Destroy all enchantments.
 */
val Tranquility = card("Tranquility") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "Destroy all enchantments."
    spell {
        effect = Effects.DestroyAll(GameObjectFilter.Enchantment)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "220"
        artist = "Douglas Shuler"
        imageUri = "https://cards.scryfall.io/normal/front/7/7/774cc5a6-3a69-4812-add4-eb5eb6389238.jpg"
    }
}
