// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ModifyStats


/**
 * Unholy Strength
 * {B}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature gets +2/+1.
 */
val UnholyStrength = card("Unholy Strength") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature gets +2/+1."
    auraTarget = Targets.Creature
    staticAbility {
        ability = ModifyStats(2, 1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "131"
        artist = "Douglas Shuler"
        imageUri = "https://cards.scryfall.io/normal/front/9/0/90563f90-0127-4164-b43b-f0321dc63a1d.jpg"
    }
}
