// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Wall of Water
 * {1}{U}{U}
 * Creature — Wall
 * 0/5
 * Defender (This creature can't attack.)
 * {U}: This creature gets +1/+0 until end of turn.
 */
val WallOfWater = card("Wall of Water") {
    manaCost = "{1}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Wall"
    oracleText = "Defender (This creature can't attack.)\n{U}: This creature gets +1/+0 until end of turn."
    power = 0
    toughness = 5
    keywords(Keyword.DEFENDER)
    activatedAbility {
        cost = Costs.Mana("{U}")
        effect = Effects.ModifyStats(1, 0, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "90"
        artist = "Richard Thomas"
        flavorText = "A deafening roar arose as the fury of an enormous vertical river supplanted our serenity. Eddies turned into whirling geysers, leveling everything in their path."
        imageUri = "https://cards.scryfall.io/normal/front/4/1/41faed1a-ded8-49ee-8e2a-c60d377775d7.jpg"
    }
}
