// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Wall of Air
 * {1}{U}{U}
 * Creature — Wall
 * 1/5
 * Defender, flying (This creature can't attack, and it can block creatures with flying.)
 */
val WallOfAir = card("Wall of Air") {
    manaCost = "{1}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Wall"
    oracleText = "Defender, flying (This creature can't attack, and it can block creatures with flying.)"
    power = 1
    toughness = 5
    keywords(Keyword.DEFENDER, Keyword.FLYING)
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "89"
        artist = "Richard Thomas"
        flavorText = "\"This 'standing windstorm' can hold us off indefinitely? Ridiculous!\" Saying nothing, she put a pinch of salt on the table. With a bang she clapped her hands, and the salt disappeared, blown away."
        imageUri = "https://cards.scryfall.io/normal/front/d/a/da56fdf3-6a8f-4833-a5c3-197650cc4889.jpg"
    }
}
