// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.RegenerateEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Will-o'-the-Wisp
 * {B}
 * Creature — Spirit
 * 0/1
 * Flying (This creature can't be blocked except by creatures with flying or reach.)
 * {B}: Regenerate this creature. (The next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)
 */
val WillOTheWisp = card("Will-o'-the-Wisp") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Creature — Spirit"
    oracleText = "Flying (This creature can't be blocked except by creatures with flying or reach.)\n{B}: Regenerate this creature. (The next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)"
    power = 0
    toughness = 1
    keywords(Keyword.FLYING)
    activatedAbility {
        cost = Costs.Mana("{B}")
        effect = RegenerateEffect(EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "135"
        artist = "Jesper Myrfors"
        flavorText = "\"About, about in reel and rout\nThe death-fires danced at night;\nThe water, like a witch's oils,\nBurnt green, and blue and white.\"\n—Samuel Coleridge, \"The Rime of the Ancient Mariner\""
        imageUri = "https://cards.scryfall.io/normal/front/a/1/a1a6f8e9-7bc1-4151-b55f-acf877b1a7a6.jpg"
    }
}
