// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Afflict
 * {2}{B}
 * Instant
 * Target creature gets -1/-1 until end of turn.
 * Draw a card.
 */
val Afflict = card("Afflict") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Instant"
    oracleText = "Target creature gets -1/-1 until end of turn.\nDraw a card."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.ModifyStats(-1, -1, t),
            DrawCardsEffect(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "115"
        artist = "Roger Raupp"
        flavorText = "When one of the Patriarch's champions displeased him, he would only shake his finger. That was enough."
        imageUri = "https://cards.scryfall.io/normal/front/0/0/0012621b-c0e1-48d6-99b9-ecca4763d748.jpg"
    }
}
