// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Amugaba
 * {5}{U}{U}
 * Creature — Illusion
 * 6/6
 * Flying
 * {2}{U}, Discard a card: Return this creature to its owner's hand.
 */
val Amugaba = card("Amugaba") {
    manaCost = "{5}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Illusion"
    oracleText = "Flying\n{2}{U}, Discard a card: Return this creature to its owner's hand."
    power = 6
    toughness = 6
    keywords(Keyword.FLYING)
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}{U}"), Costs.DiscardCard)
        effect = Effects.Move(EffectTarget.Self, Zone.HAND)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "61"
        artist = "Heather Hudson"
        flavorText = "The aven claim it feeds on thunder and rainbows."
        imageUri = "https://cards.scryfall.io/normal/front/8/d/8d73d1e7-79be-4b28-a480-b65b4f34f755.jpg"
    }
}
