// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Ashen Firebeast
 * {6}{R}{R}
 * Creature — Elemental Beast
 * 6/6
 * {1}{R}: This creature deals 1 damage to each creature without flying.
 */
val AshenFirebeast = card("Ashen Firebeast") {
    manaCost = "{6}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Elemental Beast"
    oracleText = "{1}{R}: This creature deals 1 damage to each creature without flying."
    power = 6
    toughness = 6
    activatedAbility {
        cost = Costs.Mana("{1}{R}")
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature.withoutKeyword(Keyword.FLYING)),
            DealDamageEffect(1, EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "174"
        artist = "Mark Tedin"
        flavorText = "\"I'm not sure which impresses me most, its thoroughness or its intensity.\"\n—Matoc, lavamancer"
        imageUri = "https://cards.scryfall.io/normal/front/e/b/ebaef0bd-8288-49ba-a889-d897a4aae64c.jpg"
    }
}
