// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Bash to Bits
 * {3}{R}
 * Instant
 * Destroy target artifact.
 * Flashback {4}{R}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val BashToBits = card("Bash to Bits") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Destroy target artifact.\nFlashback {4}{R}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        val t = target("target", TargetPermanent(filter = TargetFilter.Artifact))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    keywordAbility(KeywordAbility.flashback("{4}{R}{R}"))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "176"
        artist = "Matt Cavotta"
        imageUri = "https://cards.scryfall.io/normal/front/6/9/694b24de-d7f8-49c6-8ab3-d5fab13b6a8f.jpg"
    }
}
