// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Blessed Orator
 * {3}{W}
 * Creature — Human Cleric
 * 1/4
 * Other creatures you control get +0/+1.
 */
val BlessedOrator = card("Blessed Orator") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Cleric"
    oracleText = "Other creatures you control get +0/+1."
    power = 1
    toughness = 4
    staticAbility {
        ability = ModifyStats(
            powerBonus = 0,
            toughnessBonus = 1,
            filter = GroupFilter(GameObjectFilter.Creature.youControl(), excludeSelf = true)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "12"
        artist = "Terese Nielsen"
        flavorText = "His quiet words fade into the night's chill, yet they burn into his listeners' minds with all the power of a thousand suns."
        imageUri = "https://cards.scryfall.io/normal/front/5/6/5654575e-0849-4e7f-98f2-0074ac8e0faa.jpg"
    }
}
