// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.ForceSacrificeEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Braids, Cabal Minion
 * {2}{B}{B}
 * Legendary Creature — Human Minion
 * 2/2
 * At the beginning of each player's upkeep, that player sacrifices an artifact, creature, or land of their choice.
 */
val BraidsCabalMinion = card("Braids, Cabal Minion") {
    manaCost = "{2}{B}{B}"
    colorIdentity = "B"
    typeLine = "Legendary Creature — Human Minion"
    oracleText = "At the beginning of each player's upkeep, that player sacrifices an artifact, creature, or land of their choice."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EachUpkeep
        effect = ForceSacrificeEffect(GameObjectFilter.Creature, 1, EffectTarget.PlayerRef(Player.TriggeringPlayer))
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "117"
        artist = "Eric Peterson"
        flavorText = "\"Home is where you can find a decent graveyard and strangers can disappear without awkward questions.\""
        imageUri = "https://cards.scryfall.io/normal/front/4/d/4dcdcad5-e4fb-480e-984f-1ac5cdc986b9.jpg"
    }
}
