// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Careful Study
 * {U}
 * Sorcery
 * Draw two cards, then discard two cards.
 */
val CarefulStudy = card("Careful Study") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Draw two cards, then discard two cards."
    spell {
        effect = Effects.Composite(
            DrawCardsEffect(2),
            Patterns.Hand.discardCards(2)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "70"
        artist = "Scott M. Fischer"
        flavorText = "Books are like crops—they must be thinned for best yield."
        imageUri = "https://cards.scryfall.io/normal/front/d/e/dea15b53-2940-40e7-8d48-8ec11341da83.jpg"
    }
}
