// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Cephalid Retainer
 * {2}{U}{U}
 * Creature — Octopus
 * 2/3
 * {U}{U}: Tap target creature without flying.
 */
val CephalidRetainer = card("Cephalid Retainer") {
    manaCost = "{2}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Octopus"
    oracleText = "{U}{U}: Tap target creature without flying."
    power = 2
    toughness = 3
    activatedAbility {
        cost = Costs.Mana("{U}{U}")
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.withoutKeyword(Keyword.FLYING)))
        effect = Effects.Tap(t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "73"
        artist = "Tony Szczudlo"
        flavorText = "Cephalids whisper flattery in your ear, put jewels in your hand, spin dreams in your head, and stick knives in your back."
        imageUri = "https://cards.scryfall.io/normal/front/7/8/78480527-cfd6-4065-b702-82de4694f9bb.jpg"
    }
}
