// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Coffin Purge
 * {B}
 * Instant
 * Exile target card from a graveyard.
 * Flashback {B} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val CoffinPurge = card("Coffin Purge") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Instant"
    oracleText = "Exile target card from a graveyard.\nFlashback {B} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        val t = target("target", TargetObject(filter = TargetFilter.CardInGraveyard))
        effect = Effects.Move(t, Zone.EXILE)
    }
    keywordAbility(KeywordAbility.flashback("{B}"))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "124"
        artist = "Pete Venters"
        imageUri = "https://cards.scryfall.io/normal/front/5/4/541e06cb-5616-40b4-9d36-89471a795ac8.jpg"
    }
}
