// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Crystal Quarry
 * Land
 * {T}: Add {C}.
 * {5}, {T}: Add {W}{U}{B}{R}{G}.
 */
val CrystalQuarry = card("Crystal Quarry") {
    manaCost = ""
    colorIdentity = "WUBRG"
    typeLine = "Land"
    oracleText = "{T}: Add {C}.\n{5}, {T}: Add {W}{U}{B}{R}{G}."
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddColorlessMana(1)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{5}"), Costs.Tap)
        effect = Effects.Composite(
            Effects.AddMana(Color.WHITE, 1),
            Effects.AddMana(Color.BLUE, 1),
            Effects.AddMana(Color.BLACK, 1),
            Effects.AddMana(Color.RED, 1),
            Effects.AddMana(Color.GREEN, 1)
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "318"
        artist = "Alan Pollack"
        flavorText = "\"How tragic that greed eclipses beauty.\"\n—Seton, centaur druid"
        imageUri = "https://cards.scryfall.io/normal/front/1/0/1012124a-5401-4bd1-a163-4633d934938f.jpg"
    }
}
