// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Deep Reconnaissance
 * {2}{G}
 * Sorcery
 * Search your library for a basic land card, put that card onto the battlefield tapped, then shuffle.
 * Flashback {4}{G} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val DeepReconnaissance = card("Deep Reconnaissance") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "Search your library for a basic land card, put that card onto the battlefield tapped, then shuffle.\nFlashback {4}{G} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.BasicLand,
            destination = SearchDestination.BATTLEFIELD,
            entersTapped = true
        )
    }
    keywordAbility(KeywordAbility.flashback("{4}{G}"))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "236"
        artist = "Jeff Remmer"
        imageUri = "https://cards.scryfall.io/normal/front/1/4/148ce683-3911-4b77-9e07-3985766a3777.jpg"
    }
}
