// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Deluge
 * {2}{U}
 * Instant
 * Tap all creatures without flying.
 */
val Deluge = card("Deluge") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Tap all creatures without flying."
    spell {
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature.withoutKeyword(Keyword.FLYING)),
            Effects.Tap(EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "80"
        artist = "Wayne England"
        flavorText = "\"From the sea came all life, and to the sea it will return. The sooner the better.\"\n—Emperor Aboshan"
        imageUri = "https://cards.scryfall.io/normal/front/2/2/22e64f32-0436-4f07-b2b5-a622e3f59d65.jpg"
    }
}
