// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Dogged Hunter
 * {2}{W}
 * Creature — Human Nomad
 * 1/1
 * {T}: Destroy target creature token.
 */
val DoggedHunter = card("Dogged Hunter") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Nomad"
    oracleText = "{T}: Destroy target creature token."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "20"
        artist = "rk post"
        flavorText = "The relationship between hunter and hunted knows nothing of alliances."
        imageUri = "https://cards.scryfall.io/normal/front/b/5/b50d4337-9b71-429b-b6bc-2d70299a6e76.jpg"
    }
}
