// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Dwarven Strike Force
 * {4}{R}
 * Creature — Dwarf Berserker
 * 4/3
 * Discard a card at random: This creature gains first strike and haste until end of turn.
 */
val DwarvenStrikeForce = card("Dwarven Strike Force") {
    manaCost = "{4}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Dwarf Berserker"
    oracleText = "Discard a card at random: This creature gains first strike and haste until end of turn."
    power = 4
    toughness = 3
    activatedAbility {
        cost = Costs.DiscardAtRandom(1)
        effect = Effects.Composite(
            Effects.GrantKeyword(Keyword.FIRST_STRIKE, EffectTarget.Self),
            Effects.GrantKeyword(Keyword.HASTE, EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "188"
        artist = "Mike Ploog"
        flavorText = "Any given foothill may hide dozens of dwarves waiting to spill from their tunnels like fire ants."
        imageUri = "https://cards.scryfall.io/normal/front/a/2/a2bc3d85-5ba1-4f2e-a676-be989bdb04f7.jpg"
    }
}
