// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility


/**
 * Elephant Ambush
 * {2}{G}{G}
 * Instant
 * Create a 3/3 green Elephant creature token.
 * Flashback {6}{G}{G} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val ElephantAmbush = card("Elephant Ambush") {
    manaCost = "{2}{G}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Create a 3/3 green Elephant creature token.\nFlashback {6}{G}{G} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        effect = Effects.CreateToken(
            power = 3,
            toughness = 3,
            colors = setOf(Color.GREEN),
            creatureTypes = setOf("Elephant")
        )
    }
    keywordAbility(KeywordAbility.flashback("{6}{G}{G}"))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "240"
        artist = "Anthony S. Waters"
        imageUri = "https://cards.scryfall.io/normal/front/b/4/b4abdf1c-a0a9-4e1d-b448-58742830f767.jpg"
    }
}
