// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.effects.ForEachPlayerEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Howling Gale
 * {1}{G}
 * Instant
 * Howling Gale deals 1 damage to each creature with flying and each player.
 * Flashback {1}{G} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val HowlingGale = card("Howling Gale") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Howling Gale deals 1 damage to each creature with flying and each player.\nFlashback {1}{G} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        effect = Effects.Composite(
            Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Creature.withKeyword(Keyword.FLYING)),
                DealDamageEffect(1, EffectTarget.Self)
            ),
            ForEachPlayerEffect(Player.Each, listOf(DealDamageEffect(1, EffectTarget.Controller)))
        )
    }
    keywordAbility(KeywordAbility.flashback("{1}{G}"))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "244"
        artist = "Greg Staples"
        imageUri = "https://cards.scryfall.io/normal/front/9/9/9917cf32-0236-4463-9b1d-e8193754ff97.jpg"
    }
}
