// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Krosan Archer
 * {3}{G}
 * Creature — Centaur Archer
 * 2/3
 * Reach (This creature can block creatures with flying.)
 * {G}, Discard a card: This creature gets +0/+2 until end of turn.
 */
val KrosanArcher = card("Krosan Archer") {
    manaCost = "{3}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Centaur Archer"
    oracleText = "Reach (This creature can block creatures with flying.)\n{G}, Discard a card: This creature gets +0/+2 until end of turn."
    power = 2
    toughness = 3
    keywords(Keyword.REACH)
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{G}"), Costs.DiscardCard)
        effect = Effects.ModifyStats(0, 2, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "246"
        artist = "Ron Spears"
        imageUri = "https://cards.scryfall.io/normal/front/e/1/e188562f-8219-4fb0-ac2c-5618cfb00bca.jpg"
    }
}
