// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.targets.TargetPlayer


/**
 * Limestone Golem
 * {6}
 * Artifact Creature — Golem
 * 3/4
 * {2}, Sacrifice this creature: Target player draws a card.
 */
val LimestoneGolem = card("Limestone Golem") {
    manaCost = "{6}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Golem"
    oracleText = "{2}, Sacrifice this creature: Target player draws a card."
    power = 3
    toughness = 4
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.SacrificeSelf)
        val t = target("target", TargetPlayer())
        effect = DrawCardsEffect(1, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "301"
        artist = "Mark Tedin"
        flavorText = "Dwarves have been known to take pickaxes to their own creations, hoping to discover treasures within."
        imageUri = "https://cards.scryfall.io/normal/front/b/5/b522518c-1846-4e95-b77d-2aadac78684d.jpg"
    }
}
