// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Malevolent Awakening
 * {1}{B}{B}
 * Enchantment
 * {1}{B}{B}, Sacrifice a creature: Return target creature card from your graveyard to your hand.
 */
val MalevolentAwakening = card("Malevolent Awakening") {
    manaCost = "{1}{B}{B}"
    colorIdentity = "B"
    typeLine = "Enchantment"
    oracleText = "{1}{B}{B}, Sacrifice a creature: Return target creature card from your graveyard to your hand."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}{B}{B}"), Costs.Sacrifice(GameObjectFilter.Creature))
        val t = target("target", TargetObject(filter = TargetFilter.CreatureInYourGraveyard))
        effect = Effects.Move(t, Zone.HAND)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "147"
        artist = "Alex Horley-Orlandelli"
        flavorText = "The most popular pit fighters are brought back for encore performances."
        imageUri = "https://cards.scryfall.io/normal/front/3/5/35d94052-aae3-4ced-9309-fc4a0d1f159d.jpg"
    }
}
