// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Morbid Hunger
 * {4}{B}{B}
 * Sorcery
 * Morbid Hunger deals 3 damage to any target. You gain 3 life.
 * Flashback {7}{B}{B} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val MorbidHunger = card("Morbid Hunger") {
    manaCost = "{4}{B}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Morbid Hunger deals 3 damage to any target. You gain 3 life.\nFlashback {7}{B}{B} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        val t = target("target", AnyTarget())
        effect = Effects.Composite(
            DealDamageEffect(3, t),
            GainLifeEffect(3)
        )
    }
    keywordAbility(KeywordAbility.flashback("{7}{B}{B}"))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "150"
        artist = "Eric Peterson"
        imageUri = "https://cards.scryfall.io/normal/front/4/7/47a4e7d0-ff09-4e19-8456-f4845f56dc8b.jpg"
    }
}
