// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Patrol Hound
 * {1}{W}
 * Creature — Dog
 * 2/2
 * Discard a card: This creature gains first strike until end of turn.
 */
val PatrolHound = card("Patrol Hound") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Dog"
    oracleText = "Discard a card: This creature gains first strike until end of turn."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.DiscardCard
        effect = Effects.GrantKeyword(Keyword.FIRST_STRIKE, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "38"
        artist = "Daren Bader"
        flavorText = "To the camp, it was a fierce and loyal protector. To the sentry's youngest daughter, it would always be her \"Wuv Muffin.\""
        imageUri = "https://cards.scryfall.io/normal/front/e/2/e216a539-152b-4a83-98ef-1996182a5714.jpg"
    }
}
