// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GrantKeyword


/**
 * Primal Frenzy
 * {G}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature has trample.
 */
val PrimalFrenzy = card("Primal Frenzy") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature has trample."
    auraTarget = Targets.Creature
    staticAbility {
        ability = GrantKeyword(Keyword.TRAMPLE)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "262"
        artist = "Alex Horley-Orlandelli"
        flavorText = "\"Don't dismiss its anger as mindless fury. I assure you, it has purpose.\"\n—Seton, centaur druid"
        imageUri = "https://cards.scryfall.io/normal/front/f/5/f5e2d822-09d0-42e5-ad91-67c66e947b3d.jpg"
    }
}
