// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.TargetPlayerOrPlaneswalker


/**
 * Scorching Missile
 * {3}{R}
 * Sorcery
 * Scorching Missile deals 4 damage to target player or planeswalker.
 * Flashback {9}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val ScorchingMissile = card("Scorching Missile") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Scorching Missile deals 4 damage to target player or planeswalker.\nFlashback {9}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        val t = target("target", TargetPlayerOrPlaneswalker())
        effect = DealDamageEffect(4, t)
    }
    keywordAbility(KeywordAbility.flashback("{9}{R}"))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "219"
        artist = "Don Hazeltine"
        imageUri = "https://cards.scryfall.io/normal/front/0/6/0672960b-4cb5-4ed6-ba3c-6b97290e0330.jpg"
    }
}
