// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Skycloud Expanse
 * Land
 * {1}, {T}: Add {W}{U}.
 */
val SkycloudExpanse = card("Skycloud Expanse") {
    manaCost = ""
    colorIdentity = "WU"
    typeLine = "Land"
    oracleText = "{1}, {T}: Add {W}{U}."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}"), Costs.Tap)
        effect = Effects.Composite(Effects.AddMana(Color.WHITE, 1), Effects.AddMana(Color.BLUE, 1))
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "327"
        artist = "Rob Alexander"
        flavorText = "From Otaria, the sun above meets the sea below at a glittering horizon."
        imageUri = "https://cards.scryfall.io/normal/front/c/8/c8c0da61-59c5-4206-83d9-c4676e169f01.jpg"
    }
}
