// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Steamclaw
 * {2}
 * Artifact
 * {3}, {T}: Exile target card from a graveyard.
 * {1}, Sacrifice this artifact: Exile target card from a graveyard.
 */
val Steamclaw = card("Steamclaw") {
    manaCost = "{2}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{3}, {T}: Exile target card from a graveyard.\n{1}, Sacrifice this artifact: Exile target card from a graveyard."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{3}"), Costs.Tap)
        val t = target("target", TargetObject(filter = TargetFilter.CardInGraveyard))
        effect = Effects.Move(t, Zone.EXILE)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}"), Costs.SacrificeSelf)
        val t = target("target", TargetObject(filter = TargetFilter.CardInGraveyard))
        effect = Effects.Move(t, Zone.EXILE)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "310"
        artist = "Jim Nelson"
        flavorText = "\"There's dead, and then there's dead dead.\"\n—Steamclaw driver"
        imageUri = "https://cards.scryfall.io/normal/front/4/f/4f84a9bf-ce64-4301-8f2c-20f1b4acd3ef.jpg"
    }
}
