// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Thaumatog
 * {1}{G}{W}
 * Creature — Atog
 * 1/2
 * Sacrifice a land: This creature gets +1/+1 until end of turn.
 * Sacrifice an enchantment: This creature gets +1/+1 until end of turn.
 */
val Thaumatog = card("Thaumatog") {
    manaCost = "{1}{G}{W}"
    colorIdentity = "WG"
    typeLine = "Creature — Atog"
    oracleText = "Sacrifice a land: This creature gets +1/+1 until end of turn.\nSacrifice an enchantment: This creature gets +1/+1 until end of turn."
    power = 1
    toughness = 2
    activatedAbility {
        cost = Costs.Sacrifice(GameObjectFilter.Land)
        effect = Effects.ModifyStats(1, 1, EffectTarget.Self)
    }
    activatedAbility {
        cost = Costs.Sacrifice(GameObjectFilter.Enchantment)
        effect = Effects.ModifyStats(1, 1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "295"
        artist = "Monte Michael Moore"
        imageUri = "https://cards.scryfall.io/normal/front/a/a/aa559342-9587-4fe3-9059-3b3a08d6637a.jpg"
    }
}
