// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.effects.ForEachPlayerEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Volcanic Spray
 * {1}{R}
 * Sorcery
 * Volcanic Spray deals 1 damage to each creature without flying and each player.
 * Flashback {1}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val VolcanicSpray = card("Volcanic Spray") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Volcanic Spray deals 1 damage to each creature without flying and each player.\nFlashback {1}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        effect = Effects.Composite(
            Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Creature.withoutKeyword(Keyword.FLYING)),
                DealDamageEffect(1, EffectTarget.Self)
            ),
            ForEachPlayerEffect(Player.Each, listOf(DealDamageEffect(1, EffectTarget.Controller)))
        )
    }
    keywordAbility(KeywordAbility.flashback("{1}{R}"))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "226"
        artist = "Matt Cavotta"
        imageUri = "https://cards.scryfall.io/normal/front/9/7/97daab4b-d934-4a3f-a043-f7c9c1dd32bf.jpg"
    }
}
