// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mor.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Kindled Fury
 * {R}
 * Instant
 * Target creature gets +1/+0 and gains first strike until end of turn. (It deals combat damage before creatures without first strike.)
 */
val KindledFury = card("Kindled Fury") {
    manaCost = "{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Target creature gets +1/+0 and gains first strike until end of turn. (It deals combat damage before creatures without first strike.)"
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.ModifyStats(1, 0, t),
            Effects.GrantKeyword(Keyword.FIRST_STRIKE, t)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "92"
        artist = "Shelly Wan"
        flavorText = "\"All beings carry the fire inside them. The challenge is to unleash it before they dwindle into oblivion.\"\n—Illulia, flamekin soulstoke"
        imageUri = "https://cards.scryfall.io/normal/front/9/9/993956c9-30d8-41ee-84c2-c06d0512aea4.jpg"
    }
}
