// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mor.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.CounterEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetSpell


/**
 * Negate
 * {1}{U}
 * Instant
 * Counter target noncreature spell.
 */
val Negate = card("Negate") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Counter target noncreature spell."
    spell {
        val t = target("target", TargetSpell(filter = TargetFilter.NoncreatureSpellOnStack))
        effect = CounterEffect()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "43"
        artist = "Jeremy Jarvis"
        flavorText = "Masters of the arcane savor a delicious irony. Their study of deep and complex arcana leads to such a simple end: the ability to say merely yes or no."
        imageUri = "https://cards.scryfall.io/normal/front/5/a/5a501252-e722-4ebf-bcf7-f53a42745fa7.jpg"
    }
}
