// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jmp.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Corsair Captain
 * {2}{U}
 * Creature — Human Pirate
 * 2/2
 * When this creature enters, create a Treasure token. (It's an artifact with "{T}, Sacrifice this token: Add one mana of any color.")
 * Other Pirates you control get +1/+1.
 */
val CorsairCaptain = card("Corsair Captain") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Pirate"
    oracleText = "When this creature enters, create a Treasure token. (It's an artifact with \"{T}, Sacrifice this token: Add one mana of any color.\")\nOther Pirates you control get +1/+1."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.CreateTreasure()
    }
    staticAbility {
        ability = ModifyStats(
            powerBonus = 1,
            toughnessBonus = 1,
            // "Other Pirates you control" names the subtype and not the card type, so the lord
            // reaches Pirate *permanents*. Found by the Assay differential.
            filter = GroupFilter(
                GameObjectFilter.Permanent.withSubtype(Subtype.PIRATE).youControl(),
                excludeSelf = true,
            )
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "11"
        artist = "Victor Adame Minguez"
        flavorText = "\"Lungs full of sea air and a hold full of loot. Ah, what a life!\""
        imageUri = "https://cards.scryfall.io/normal/front/a/9/a9b016d4-ddf6-47d6-b934-a0b979b60680.jpg"
    }
}
