// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.otj.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersTapped
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.TargetOpponent


/**
 * Creosote Heath
 * Land — Desert
 * This land enters tapped.
 * When this land enters, it deals 1 damage to target opponent.
 * {T}: Add {G} or {W}.
 */
val CreosoteHeath = card("Creosote Heath") {
    manaCost = ""
    colorIdentity = "WG"
    typeLine = "Land — Desert"
    oracleText = "This land enters tapped.\nWhen this land enters, it deals 1 damage to target opponent.\n{T}: Add {G} or {W}."
    replacementEffect(EntersTapped())
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetOpponent())
        effect = DealDamageEffect(1, t)
    }
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.GREEN)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.WHITE)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "255"
        artist = "Leon Tukker"
        flavorText = "\"The sunsets in Spinegully sure make the soul question why we bother with cities.\"\n—Pioneer journal of Big Ralph"
        imageUri = "https://cards.scryfall.io/normal/front/c/5/c5523dac-7aa0-4486-89c8-3b22a1411f26.jpg"
    }
}
