// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.otj.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Redrock Sentinel
 * {3}
 * Artifact Creature — Golem
 * 2/4
 * Defender
 * {2}, {T}, Sacrifice a land: Draw a card and create a Treasure token. (It's an artifact with "{T}, Sacrifice this token: Add one mana of any color.")
 */
val RedrockSentinel = card("Redrock Sentinel") {
    manaCost = "{3}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Golem"
    oracleText = "Defender\n{2}, {T}, Sacrifice a land: Draw a card and create a Treasure token. (It's an artifact with \"{T}, Sacrifice this token: Add one mana of any color.\")"
    power = 2
    toughness = 4
    keywords(Keyword.DEFENDER)
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.Tap, Costs.Sacrifice(GameObjectFilter.Land))
        effect = Effects.Composite(
            DrawCardsEffect(1),
            Effects.CreateTreasure(1)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "247"
        artist = "Milivoj Ćeran"
        flavorText = "The miners thought it would be genius to increase their productivity with explosives. The land thought otherwise."
        imageUri = "https://cards.scryfall.io/normal/front/8/e/8eb98381-8418-4dfd-b7d1-4353570e611b.jpg"
    }
}
