// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.otj.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Sterling Keykeeper
 * {1}{W}
 * Creature — Human Mercenary
 * 2/2
 * {2}, {T}: Tap target non-Mount creature.
 */
val SterlingKeykeeper = card("Sterling Keykeeper") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Mercenary"
    oracleText = "{2}, {T}: Tap target non-Mount creature."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.Tap)
        val t = target(
            "target",
            TargetCreature(filter = TargetFilter(GameObjectFilter.Creature.notSubtype(Subtype("Mount"))))
        )
        effect = Effects.Tap(t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "32"
        artist = "David Astruga"
        flavorText = "\"If you don't want to tell me where the stash is, you'd best start getting comfy in there. You just let me know when you've changed your mind.\""
        imageUri = "https://cards.scryfall.io/normal/front/0/1/019d539f-04c2-43f1-8677-6d6fbb0e94f7.jpg"
    }
}
