// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.otj.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Trained Arynx
 * {1}{W}
 * Creature — Cat Beast Mount
 * 3/1
 * Whenever this creature attacks while saddled, it gains first strike until end of turn. Scry 1. (Look at the top card of your library. You may put that card on the bottom.)
 * Saddle 2 (Tap any number of other creatures you control with total power 2 or more: This Mount becomes saddled until end of turn. Saddle only as a sorcery.)
 */
val TrainedArynx = card("Trained Arynx") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Cat Beast Mount"
    oracleText = "Whenever this creature attacks while saddled, it gains first strike until end of turn. Scry 1. (Look at the top card of your library. You may put that card on the bottom.)\nSaddle 2 (Tap any number of other creatures you control with total power 2 or more: This Mount becomes saddled until end of turn. Saddle only as a sorcery.)"
    power = 3
    toughness = 1
    triggeredAbility {
        trigger = Triggers.Attacks
        triggerRestriction = Conditions.SourceIsSaddled
        effect = Effects.Composite(
            Effects.GrantKeyword(Keyword.FIRST_STRIKE, EffectTarget.Self),
            Patterns.Library.scry(1)
        )
    }
    keywordAbility(KeywordAbility.saddle(2))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "36"
        artist = "Milivoj Ćeran"
        imageUri = "https://cards.scryfall.io/normal/front/e/f/ef32a5f8-f69d-47dc-a800-4f0ddf4eada5.jpg"
    }
}
