// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.otj.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.TargetOpponent


/**
 * Vial Smasher, Gleeful Grenadier
 * {B}{R}
 * Legendary Creature — Goblin Mercenary
 * 3/2
 * Whenever another outlaw you control enters, Vial Smasher deals 1 damage to target opponent. (Assassins, Mercenaries, Pirates, Rogues, and Warlocks are outlaws.)
 */
val VialSmasherGleefulGrenadier = card("Vial Smasher, Gleeful Grenadier") {
    manaCost = "{B}{R}"
    colorIdentity = "BR"
    typeLine = "Legendary Creature — Goblin Mercenary"
    oracleText = "Whenever another outlaw you control enters, Vial Smasher deals 1 damage to target opponent. (Assassins, Mercenaries, Pirates, Rogues, and Warlocks are outlaws.)"
    power = 3
    toughness = 2
    triggeredAbility {
        trigger = Triggers.entersBattlefield(
            filter = GameObjectFilter.Creature.withAnyOfSubtypes(Subtype.OUTLAW_TYPES).youControl(),
            binding = TriggerBinding.OTHER
        )
        val t = target("target", TargetOpponent())
        effect = DealDamageEffect(1, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "235"
        artist = "Borja Pindado"
        flavorText = "It wasn't quite home, but the fire still burned bright and the bombs still went boom."
        imageUri = "https://cards.scryfall.io/normal/front/3/a/3afce4e6-ac59-4fba-b63a-8fed96bbdc4a.jpg"
    }
}
