// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ths.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.TargetCreatureOrPlaneswalker


/**
 * Hero's Downfall
 * {1}{B}{B}
 * Instant
 * Destroy target creature or planeswalker.
 */
val HerosDownfall = card("Hero's Downfall") {
    manaCost = "{1}{B}{B}"
    colorIdentity = "B"
    typeLine = "Instant"
    oracleText = "Destroy target creature or planeswalker."
    spell {
        val t = target("target", TargetCreatureOrPlaneswalker())
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "90"
        artist = "Ryan Pancoast"
        flavorText = "Destiny exalts a chosen few, but even heroes break."
        imageUri = "https://cards.scryfall.io/normal/front/5/9/596822f6-dbd4-4cc8-aa50-9331ff42544e.jpg"
    }
}
