// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.emn.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Blood Mist
 * {3}{R}
 * Enchantment
 * At the beginning of combat on your turn, target creature you control gains double strike until end of turn.
 */
val BloodMist = card("Blood Mist") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Enchantment"
    oracleText = "At the beginning of combat on your turn, target creature you control gains double strike until end of turn."
    triggeredAbility {
        trigger = Triggers.BeginCombat
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.youControl()))
        effect = Effects.GrantKeyword(Keyword.DOUBLE_STRIKE, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "119"
        artist = "Joseph Meehan"
        flavorText = "\"Some claim that rage is a cloud that obscures thought and vision. But I can assure you—I've never seen with greater clarity.\""
        imageUri = "https://cards.scryfall.io/normal/front/a/6/a6982bde-1fa3-48fa-803d-a45d6acbc2fe.jpg"
    }
}
