// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.emn.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Clear Shot
 * {2}{G}
 * Instant
 * Target creature you control gets +1/+1 until end of turn. It deals damage equal to its power to target creature you don't control.
 */
val ClearShot = card("Clear Shot") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Target creature you control gets +1/+1 until end of turn. It deals damage equal to its power to target creature you don't control."
    spell {
        val t1 = target("t1", TargetCreature(filter = TargetFilter.Creature.youControl()))
        val t2 = target("t2", TargetCreature(filter = TargetFilter.Creature.opponentControls()))
        effect = Effects.Composite(
            Effects.ModifyStats(1, 1, t1),
            DealDamageEffect(DynamicAmounts.targetPower(0), t2, damageSource = t1)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "152"
        artist = "Craig J Spearing"
        flavorText = "\"What worked to bring down angels will do the same for these horrors.\"\n—Rem Karolus, Slayer of Eldrazi"
        imageUri = "https://cards.scryfall.io/normal/front/1/2/12fa1d34-7e32-45b7-9f6f-68f152f75d1a.jpg"
    }
}
