// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.emn.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Nebelgast Herald
 * {2}{U}
 * Creature — Spirit
 * 2/1
 * Flash
 * Flying
 * Whenever this creature or another Spirit you control enters, tap target creature an opponent controls.
 */
val NebelgastHerald = card("Nebelgast Herald") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Spirit"
    oracleText = "Flash\nFlying\nWhenever this creature or another Spirit you control enters, tap target creature an opponent controls."
    power = 2
    toughness = 1
    keywords(Keyword.FLASH, Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.entersBattlefield(
            filter = GameObjectFilter.Permanent.withSubtype(Subtype.SPIRIT).youControl(),
            binding = TriggerBinding.ANY
        )
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.opponentControls()))
        effect = Effects.Tap(t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "71"
        artist = "Zezhou Chen"
        imageUri = "https://cards.scryfall.io/normal/front/4/0/40965d3b-9b8f-4706-9364-64f758a768e6.jpg"
    }
}
