// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.all.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Storm Crow
 * {1}{U}
 * Creature — Bird
 * 1/2
 * Flying (This creature can't be blocked except by creatures with flying or reach.)
 */
val StormCrow = card("Storm Crow") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Bird"
    power = 1
    toughness = 2
    keywords(Keyword.FLYING)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "36a"
        artist = "Sandra Everingham"
        flavorText = "\"It tells you that the worst is coming. Do you listen?\"\n—Lovisa Coldeyes, Balduvian Chieftain"
        imageUri = "https://cards.scryfall.io/normal/front/a/2/a2d4ea78-16f1-46ac-8a60-db20c37aad5e.jpg"
    }
}
