// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.akh.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Regal Caracal
 * {3}{W}{W}
 * Creature — Cat
 * 3/3
 * Other Cats you control get +1/+1 and have lifelink. (Damage dealt by those creatures also causes you to gain that much life.)
 * When this creature enters, create two 1/1 white Cat creature tokens with lifelink.
 */
val RegalCaracal = card("Regal Caracal") {
    manaCost = "{3}{W}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Cat"
    oracleText = "Other Cats you control get +1/+1 and have lifelink. (Damage dealt by those creatures also causes you to gain that much life.)\nWhen this creature enters, create two 1/1 white Cat creature tokens with lifelink."
    power = 3
    toughness = 3
    staticAbility {
        ability = ModifyStats(
            powerBonus = 1,
            toughnessBonus = 1,
            filter = GroupFilter(GameObjectFilter.Permanent.withSubtype(Subtype.CAT).youControl(), excludeSelf = true)
        )
    }
    staticAbility {
        ability = GrantKeyword(
            Keyword.LIFELINK,
            GroupFilter(GameObjectFilter.Permanent.withSubtype(Subtype.CAT).youControl(), excludeSelf = true)
        )
    }
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.CreateToken(
            power = 1,
            toughness = 1,
            colors = setOf(Color.WHITE),
            creatureTypes = setOf("Cat"),
            keywords = setOf(Keyword.LIFELINK),
            count = 2
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "24"
        artist = "Filip Burburan"
        flavorText = "Oketra's closest viziers are known as her chosen, though others may have a better claim to that moniker."
        imageUri = "https://cards.scryfall.io/normal/front/c/d/cd349f95-3eae-4ef2-abf8-e911bb8e93e5.jpg"
    }
}
