// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rna.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Bladebrand
 * {1}{B}
 * Instant
 * Target creature gains deathtouch until end of turn.
 * Draw a card.
 */
val Bladebrand = card("Bladebrand") {
    manaCost = "{1}{B}"
    colorIdentity = "B"
    typeLine = "Instant"
    oracleText = "Target creature gains deathtouch until end of turn.\nDraw a card."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.GrantKeyword(Keyword.DEATHTOUCH, t),
            DrawCardsEffect(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "64"
        artist = "Winona Nelson"
        flavorText = "\"The pain of searing iron and razor edges pales beside the pleasure of performance.\"\n—Judith"
        imageUri = "https://cards.scryfall.io/normal/front/f/7/f738545d-5483-45ec-bb31-d62b0fae9ea7.jpg"
    }
}
