// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.`5dn`.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Staff of Domination
 * {3}
 * Artifact
 * {1}: Untap this artifact.
 * {2}, {T}: You gain 1 life.
 * {3}, {T}: Untap target creature.
 * {4}, {T}: Tap target creature.
 * {5}, {T}: Draw a card.
 */
val StaffOfDomination = card("Staff of Domination") {
    manaCost = "{3}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{1}: Untap this artifact.\n{2}, {T}: You gain 1 life.\n{3}, {T}: Untap target creature.\n{4}, {T}: Tap target creature.\n{5}, {T}: Draw a card."
    activatedAbility {
        cost = Costs.Mana("{1}")
        effect = Effects.Untap(EffectTarget.Self)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.Tap)
        effect = GainLifeEffect(1)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{3}"), Costs.Tap)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Untap(t)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{4}"), Costs.Tap)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Tap(t)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{5}"), Costs.Tap)
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "156"
        artist = "Ben Thompson"
        imageUri = "https://cards.scryfall.io/normal/front/7/9/7980fc3b-71d5-427d-bd42-087256fd2059.jpg"
    }
}
