package com.wingedsheep.assay.corpus

import com.wingedsheep.sdk.model.CardDefinition
import com.wingedsheep.sdk.serialization.CardLoader
import java.io.File

/**
 * The **semantic oracle**: every hand-written card in the repository, as a real [CardDefinition].
 *
 * The touchstone proves a parse is *reversible*; it cannot prove it is *right*. A rule that reads
 * "Elves" as `Elve` round-trips perfectly and means nothing. The general answer is to diff Assay's
 * reading against a definition a human wrote from the same text — and that corpus already exists
 * here, which is the asset the incumbent pipeline structurally could not have.
 *
 * ## Why this does not break the SDK-only dependency rule
 *
 * `:oracle-assay` depends on `:mtg-sdk` and nothing else, deliberately (see `build.gradle.kts`).
 * This object does not change that: the goldens under `mtg-sets/src/test/resources/snapshots/cards/`
 * are **data**, read off disk exactly the way [OracleCorpus] reads the Scryfall bulk, and they are
 * decoded by [CardLoader] — which lives in `mtg-sdk`. No `:mtg-sets` code is linked, no card
 * definition is executed, and Assay comes no closer to being a runtime card loader than it was.
 *
 * The goldens are committed and regenerated by `CardDefinitionSnapshotTest`, so they are exactly as
 * current as the last re-bless. A stale golden shows up as a divergence on a card that was recently
 * edited, which is the correct and visible failure mode.
 *
 * ## File format
 *
 * One file per set, entries joined by a blank line, each entry a `// <card name>` header followed by
 * the exported JSON. Header lines are the only thing in the file that starts at column 0 with `//`
 * — the JSON is indented — so that is what the reader splits on.
 */
object ImplementedCorpus {

    /** Repo-relative location of the goldens. Not a resource: Assay must not depend on `:mtg-sets`. */
    private const val SNAPSHOT_DIR = "mtg-sets/src/test/resources/snapshots/cards"

    /**
     * Every hand-written card, streamed a set file at a time so the whole 20 MB of JSON is never
     * resident at once.
     *
     * @param root repository root; discovered from the working directory when null.
     */
    fun cards(root: File? = null): Sequence<ImplementedCard> =
        snapshotFiles(root).asSequence().flatMap { file ->
            val setCode = file.nameWithoutExtension
            splitEntries(file.readText()).asSequence().map { (name, json) ->
                val card = runCatching { CardLoader.fromJsonPreservingIds(json) }.getOrNull()
                ImplementedCard(name = name, setCode = setCode, definition = card)
            }
        }

    /**
     * Just the names, without decoding a single definition.
     *
     * The decline report's `--implemented` split asks a set-membership question — *does this card
     * already have a golden?* — and nothing else. Answering it through [cards] would decode 8,874
     * `CardDefinition`s to look at their headers, which costs more than the entire touchstone run
     * it is meant to scope.
     *
     * Names are the Scryfall names verbatim, split cards included ("Wax // Wane"), because that is
     * what `CardDefinitionSnapshotTest` writes into the header.
     */
    fun names(root: File? = null): Set<String> =
        snapshotFiles(root)
            .flatMap { file -> file.readLines().filter { it.startsWith("// ") } }
            .mapTo(mutableSetOf()) { it.removePrefix("// ").trim() }

    private fun snapshotFiles(root: File?): List<File> =
        snapshotDir(root).listFiles { f: File -> f.isFile && f.extension == "json" }
            ?.sortedBy { it.name }
            .orEmpty()

    /** True when the goldens are where they are expected to be, so the CLI can say so before running. */
    fun isAvailable(root: File? = null): Boolean =
        runCatching { snapshotDir(root).isDirectory }.getOrDefault(false)

    fun snapshotDir(root: File? = null): File = File(root ?: repoRoot(), SNAPSHOT_DIR)

    /**
     * Walks up from the working directory looking for `settings.gradle.kts`.
     *
     * The `just assay*` recipes and the Gradle `run` task both start at the repo root, so this
     * almost always terminates immediately; the walk exists so that running the installed binary
     * from a subdirectory is not a confusing "0 cards" report.
     */
    private fun repoRoot(): File {
        var dir: File? = File(System.getProperty("user.dir")).absoluteFile
        while (dir != null) {
            if (File(dir, "settings.gradle.kts").isFile) return dir
            dir = dir.parentFile
        }
        error(
            "could not locate the repository root from ${System.getProperty("user.dir")} — " +
                "run the differential gate from inside the repository"
        )
    }

    /**
     * `// <name>` header at column 0 begins an entry; everything up to the next such line is its
     * JSON. Written as a scan rather than a regex split so a `//` inside a card's Oracle text (split
     * cards are named "Wax // Wane") cannot be mistaken for a header — those are always indented,
     * inside a JSON string value.
     */
    internal fun splitEntries(text: String): List<Pair<String, String>> {
        val entries = mutableListOf<Pair<String, String>>()
        var name: String? = null
        val body = StringBuilder()

        fun flush() {
            val n = name ?: return
            if (body.isNotBlank()) entries.add(n to body.toString())
            body.setLength(0)
        }

        for (line in text.lineSequence()) {
            if (line.startsWith("// ")) {
                flush()
                name = line.removePrefix("// ").trim()
            } else if (name != null) {
                body.appendLine(line)
            }
        }
        flush()
        return entries
    }
}

/**
 * One hand-written card from the goldens.
 *
 * [definition] is null when the golden could not be decoded. That is counted and named rather than
 * thrown, so one unreadable entry cannot cost the whole corpus run — the same "declining is success"
 * discipline the grammar is held to.
 */
data class ImplementedCard(
    val name: String,
    val setCode: String,
    val definition: CardDefinition?,
)
