// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.bfz.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Valakut Invoker
 * {2}{R}
 * Creature — Human Shaman
 * 2/3
 * {8}: This creature deals 3 damage to any target.
 */
val ValakutInvoker = card("Valakut Invoker") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Human Shaman"
    oracleText = "{8}: This creature deals 3 damage to any target."
    power = 2
    toughness = 3
    activatedAbility {
        cost = Costs.Mana("{8}")
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(3, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "159"
        artist = "Joseph Meehan"
        flavorText = "\"As long as we have walked this world, we have known it as a harsh and unforgiving place.\"\n—The Invokers' Tales"
        imageUri = "https://cards.scryfall.io/normal/front/1/7/178c66b8-c577-49c6-9efc-7bab740e66b6.jpg"
    }
}
