// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dtk.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Seismic Rupture
 * {2}{R}
 * Sorcery
 * Seismic Rupture deals 2 damage to each creature without flying.
 */
val SeismicRupture = card("Seismic Rupture") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Seismic Rupture deals 2 damage to each creature without flying."
    spell {
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature.withoutKeyword(Keyword.FLYING)),
            DealDamageEffect(2, EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "156"
        artist = "Jason A. Engle"
        flavorText = "The shaman opened the earth beneath their feet, trapping the survivors within the crevices of Ayagor for Atarka to devour at her leisure."
        imageUri = "https://cards.scryfall.io/normal/front/9/b/9b952e4e-c1ed-4455-90d5-46b56478e6b0.jpg"
    }
}
