// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.gtc.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersTapped
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Boros Guildgate
 * Land — Gate
 * This land enters tapped.
 * {T}: Add {R} or {W}.
 */
val BorosGuildgate = card("Boros Guildgate") {
    manaCost = ""
    colorIdentity = "WR"
    typeLine = "Land — Gate"
    oracleText = "This land enters tapped.\n{T}: Add {R} or {W}."
    replacementEffect(EntersTapped())
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.RED)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.WHITE)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "239"
        artist = "Noah Bradley"
        flavorText = "Enter with merciful hearts. Exit with battle cries."
        imageUri = "https://cards.scryfall.io/normal/front/a/0/a0b447a8-524b-4bda-b975-7e194fd741fb.jpg"
    }
}
