// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.gtc.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Ripscale Predator
 * {4}{R}{R}
 * Creature — Dinosaur
 * 6/5
 * Menace (This creature can't be blocked except by two or more creatures.)
 */
val RipscalePredator = card("Ripscale Predator") {
    manaCost = "{4}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Dinosaur"
    oracleText = "Menace (This creature can't be blocked except by two or more creatures.)"
    power = 6
    toughness = 5
    keywords(Keyword.MENACE)
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "103"
        artist = "Volkan Baǵa"
        flavorText = "As Ravnica's wilds expanded, even advocates for nature had to confront fiercer natural threats."
        imageUri = "https://cards.scryfall.io/normal/front/3/b/3b7d5daf-404d-46e9-b622-e89a1f55e908.jpg"
    }
}
