// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility


/**
 * Autarch Mammoth
 * {4}{G}{G}
 * Creature — Elephant Mount
 * 5/5
 * When this creature enters and whenever it attacks while saddled, create a 3/3 green Elephant creature token.
 * Saddle 5 (Tap any number of other creatures you control with total power 5 or more: This Mount becomes saddled until end of turn. Saddle only as a sorcery.)
 */
val AutarchMammoth = card("Autarch Mammoth") {
    manaCost = "{4}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Elephant Mount"
    oracleText = "When this creature enters and whenever it attacks while saddled, create a 3/3 green Elephant creature token.\nSaddle 5 (Tap any number of other creatures you control with total power 5 or more: This Mount becomes saddled until end of turn. Saddle only as a sorcery.)"
    power = 5
    toughness = 5
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.CreateToken(
            power = 3,
            toughness = 3,
            colors = setOf(Color.GREEN),
            creatureTypes = setOf("Elephant")
        )
    }
    triggeredAbility {
        trigger = Triggers.Attacks
        triggerRestriction = Conditions.SourceIsSaddled
        effect = Effects.CreateToken(
            power = 3,
            toughness = 3,
            colors = setOf(Color.GREEN),
            creatureTypes = setOf("Elephant")
        )
    }
    keywordAbility(KeywordAbility.saddle(5))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "153"
        artist = "Leonardo Santanna"
        imageUri = "https://cards.scryfall.io/normal/front/4/d/4d313ea7-2456-48f3-8b12-97d8e8c2a5b3.jpg"
    }
}
