// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Draconautics Engineer
 * {1}{R}
 * Creature — Goblin Artificer
 * 2/2
 * Exhaust — {R}: Other creatures you control gain haste until end of turn. Put a +1/+1 counter on this creature. (Activate each exhaust ability only once.)
 * Exhaust — {3}{R}: Create a 4/4 red Dinosaur Dragon creature token with flying.
 */
val DraconauticsEngineer = card("Draconautics Engineer") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Goblin Artificer"
    oracleText = "Exhaust — {R}: Other creatures you control gain haste until end of turn. Put a +1/+1 counter on this creature. (Activate each exhaust ability only once.)\nExhaust — {3}{R}: Create a 4/4 red Dinosaur Dragon creature token with flying."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.Mana("{R}")
        isExhaust = true
        effect = Effects.Composite(
            Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Creature.youControl(), excludeSelf = true),
                Effects.GrantKeyword(Keyword.HASTE, EffectTarget.Self)
            ),
            AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self)
        )
    }
    activatedAbility {
        cost = Costs.Mana("{3}{R}")
        isExhaust = true
        effect = Effects.CreateToken(
            power = 4,
            toughness = 4,
            colors = setOf(Color.RED),
            creatureTypes = setOf("Dinosaur", "Dragon"),
            keywords = setOf(Keyword.FLYING)
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "121"
        artist = "Artur Nakhodkin"
        imageUri = "https://cards.scryfall.io/normal/front/c/4/c44440be-e611-4e70-9919-b08e2354b7ad.jpg"
    }
}
