// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Hazard of the Dunes
 * {3}{G}
 * Creature — Wurm
 * 4/4
 * Trample, reach
 * Exhaust — {6}{G}: Put three +1/+1 counters on this creature. (Activate each exhaust ability only once.)
 */
val HazardOfTheDunes = card("Hazard of the Dunes") {
    manaCost = "{3}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Wurm"
    oracleText = "Trample, reach\nExhaust — {6}{G}: Put three +1/+1 counters on this creature. (Activate each exhaust ability only once.)"
    power = 4
    toughness = 4
    keywords(Keyword.TRAMPLE, Keyword.REACH)
    activatedAbility {
        cost = Costs.Mana("{6}{G}")
        isExhaust = true
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 3, target = EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "165"
        artist = "Brent Hollowell"
        flavorText = "\"It's aggravating that nature can build better hazards than I ever could.\"\n—Termin, track designer"
        imageUri = "https://cards.scryfall.io/normal/front/c/3/c3fbee7a-7e73-43cf-bc39-ccb1c63bf837.jpg"
    }
}
