// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Keen Buccaneer
 * {2}{U}
 * Creature — Octopus Pirate
 * 2/3
 * Vigilance
 * Exhaust — {1}{U}: Draw a card, then discard a card. Put a +1/+1 counter on this creature. (Activate each exhaust ability only once.)
 */
val KeenBuccaneer = card("Keen Buccaneer") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Octopus Pirate"
    oracleText = "Vigilance\nExhaust — {1}{U}: Draw a card, then discard a card. Put a +1/+1 counter on this creature. (Activate each exhaust ability only once.)"
    power = 2
    toughness = 3
    keywords(Keyword.VIGILANCE)
    activatedAbility {
        cost = Costs.Mana("{1}{U}")
        isExhaust = true
        effect = Effects.Composite(
            DrawCardsEffect(1),
            Patterns.Hand.discardCards(1),
            AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "48"
        artist = "Mirko Failoni"
        flavorText = "\"The secret to good piratin' is being ready for anything. That, and havin' eight arms.\""
        imageUri = "https://cards.scryfall.io/normal/front/0/e/0ed90a63-5aca-470a-8e1e-518d8aeb6d91.jpg"
    }
}
