// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Pactdoll Terror
 * {3}{B}
 * Artifact Creature — Toy
 * 3/4
 * Whenever this creature or another artifact you control enters, each opponent loses 1 life and you gain 1 life.
 */
val PactdollTerror = card("Pactdoll Terror") {
    manaCost = "{3}{B}"
    colorIdentity = "B"
    typeLine = "Artifact Creature — Toy"
    oracleText = "Whenever this creature or another artifact you control enters, each opponent loses 1 life and you gain 1 life."
    power = 3
    toughness = 4
    triggeredAbility {
        trigger = Triggers.entersBattlefield(
            filter = GameObjectFilter.Artifact.youControl(),
            binding = TriggerBinding.ANY
        )
        effect = Effects.Composite(
            Effects.LoseLife(1, EffectTarget.PlayerRef(Player.EachOpponent)),
            GainLifeEffect(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "99"
        artist = "David Astruga"
        flavorText = "\"And you're telling me this was designed for children?\"\n—Sita Varma"
        imageUri = "https://cards.scryfall.io/normal/front/7/0/70226354-47b7-4f9d-a5a8-559d17f07720.jpg"
    }
}
