// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Prowcatcher Specialist
 * {1}{R}
 * Creature — Goblin Warrior
 * 2/1
 * Haste
 * Exhaust — {3}{R}: Put two +1/+1 counters on this creature. (Activate each exhaust ability only once.)
 */
val ProwcatcherSpecialist = card("Prowcatcher Specialist") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Goblin Warrior"
    oracleText = "Haste\nExhaust — {3}{R}: Put two +1/+1 counters on this creature. (Activate each exhaust ability only once.)"
    power = 2
    toughness = 1
    keywords(Keyword.HASTE)
    activatedAbility {
        cost = Costs.Mana("{3}{R}")
        isExhaust = true
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 2, target = EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "142"
        artist = "Konstantin Porubov"
        flavorText = "\"Don't you know it's dangerous to go faster than us?\""
        imageUri = "https://cards.scryfall.io/normal/front/a/f/affbc8db-4ff7-4a86-954a-910493e5a2ef.jpg"
    }
}
