// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Stampeding Scurryfoot
 * {G}
 * Creature — Mouse
 * 1/1
 * Exhaust — {3}{G}: Put a +1/+1 counter on this creature. Create a 3/3 green Elephant creature token. (Activate each exhaust ability only once.)
 */
val StampedingScurryfoot = card("Stampeding Scurryfoot") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Creature — Mouse"
    oracleText = "Exhaust — {3}{G}: Put a +1/+1 counter on this creature. Create a 3/3 green Elephant creature token. (Activate each exhaust ability only once.)"
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Mana("{3}{G}")
        isExhaust = true
        effect = Effects.Composite(
            AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self),
            Effects.CreateToken(
                power = 3,
                toughness = 3,
                colors = setOf(Color.GREEN),
                creatureTypes = setOf("Elephant")
            )
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "181"
        artist = "Julia Metzger"
        flavorText = "All creatures great and small contribute to the stampede."
        imageUri = "https://cards.scryfall.io/normal/front/7/f/7fc713d7-4a7e-4f1f-b461-e89bb1457d7d.jpg"
    }
}
