// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rtr.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersTapped
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Azorius Guildgate
 * Land — Gate
 * This land enters tapped.
 * {T}: Add {W} or {U}.
 */
val AzoriusGuildgate = card("Azorius Guildgate") {
    manaCost = ""
    colorIdentity = "WU"
    typeLine = "Land — Gate"
    oracleText = "This land enters tapped.\n{T}: Add {W} or {U}."
    replacementEffect(EntersTapped())
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.WHITE)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.BLUE)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "237"
        artist = "Drew Baker"
        flavorText = "Enter the Senate, the seat of justice and the foundation of Ravnican society."
        imageUri = "https://cards.scryfall.io/normal/front/9/8/984e37df-0734-493a-a958-f519a0c98580.jpg"
    }
}
