// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tsp.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Mystical Teachings
 * {3}{U}
 * Instant
 * Search your library for an instant card or a card with flash, reveal it, put it into your hand, then shuffle.
 * Flashback {5}{B} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val MysticalTeachings = card("Mystical Teachings") {
    manaCost = "{3}{U}"
    colorIdentity = "UB"
    typeLine = "Instant"
    oracleText = "Search your library for an instant card or a card with flash, reveal it, put it into your hand, then shuffle.\nFlashback {5}{B} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Instant,
            destination = SearchDestination.HAND,
            reveal = true
        )
    }
    keywordAbility(KeywordAbility.flashback("{5}{B}"))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "69"
        artist = "Ron Spears"
        imageUri = "https://cards.scryfall.io/normal/front/a/0/a057e5f3-b6bd-4995-b990-714201f36989.jpg"
    }
}
