// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ori.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Gilt-Leaf Winnower
 * {3}{B}{B}
 * Creature — Elf Warrior
 * 4/3
 * Menace (This creature can't be blocked except by two or more creatures.)
 * When this creature enters, you may destroy target non-Elf creature whose power and toughness aren't equal.
 */
val GiltLeafWinnower = card("Gilt-Leaf Winnower") {
    manaCost = "{3}{B}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Elf Warrior"
    oracleText = "Menace (This creature can't be blocked except by two or more creatures.)\nWhen this creature enters, you may destroy target non-Elf creature whose power and toughness aren't equal."
    power = 4
    toughness = 3
    keywords(Keyword.MENACE)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        optional = true
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "99"
        artist = "Viktor Titov"
        imageUri = "https://cards.scryfall.io/normal/front/c/9/c9667cae-6801-434b-9d91-ea1f2bd2449e.jpg"
    }
}
