// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ori.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Skyraker Giant
 * {2}{R}{R}
 * Creature — Giant
 * 4/3
 * Reach (This creature can block creatures with flying.)
 */
val SkyrakerGiant = card("Skyraker Giant") {
    manaCost = "{2}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Giant"
    oracleText = "Reach (This creature can block creatures with flying.)"
    power = 4
    toughness = 3
    keywords(Keyword.REACH)
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "162"
        artist = "Anastasia Ovchinnikova"
        flavorText = "She will not be content until hers is the highest head in the sky."
        imageUri = "https://cards.scryfall.io/normal/front/c/5/c5f0d87a-8f37-4598-9106-c3545dadf6fd.jpg"
    }
}
