// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.aer.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Universal Solvent
 * {1}
 * Artifact
 * {7}, {T}, Sacrifice this artifact: Destroy target permanent.
 */
val UniversalSolvent = card("Universal Solvent") {
    manaCost = "{1}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{7}, {T}, Sacrifice this artifact: Destroy target permanent."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{7}"), Costs.Tap, Costs.SacrificeSelf)
        val t = target("target", TargetPermanent())
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "178"
        artist = "Christopher Moeller"
        flavorText = "\"A few drops of this, and the trickiest problems simply melt away.\"\n—Thamaz, Weldfast inventor"
        imageUri = "https://cards.scryfall.io/normal/front/2/f/2f1b66b2-12b2-497b-a328-b43630c79e73.jpg"
    }
}
