// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.m19.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Gigantosaurus
 * {G}{G}{G}{G}{G}
 * Creature — Dinosaur
 * 10/10
 */
val Gigantosaurus = card("Gigantosaurus") {
    manaCost = "{G}{G}{G}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Dinosaur"
    power = 10
    toughness = 10
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "185"
        artist = "Jonathan Kuo"
        flavorText = "\"Each tooth is the length of a horse, and new ones grow in every sixteen days. Let's get a closer look!\"\n—Vivien Reid"
        imageUri = "https://cards.scryfall.io/normal/front/c/1/c1db84d8-d426-4c0d-b44e-5be7b0f5f5bf.jpg"
    }
}
