// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.m19.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.TargetCreature
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Volley Veteran
 * {3}{R}
 * Creature — Goblin Warrior
 * 4/2
 * When this creature enters, it deals damage to target creature an opponent controls equal to the number of Goblins you control.
 */
val VolleyVeteran = card("Volley Veteran") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Goblin Warrior"
    oracleText = "When this creature enters, it deals damage to target creature an opponent controls equal to the number of Goblins you control."
    power = 4
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.opponentControls()))
        effect = DealDamageEffect(
            DynamicAmount.AggregateBattlefield(Player.You, GameObjectFilter.Permanent.withSubtype("Goblin")),
            t
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "168"
        artist = "Craig J Spearing"
        flavorText = "\"Fill the sky with stuff!\""
        imageUri = "https://cards.scryfall.io/normal/front/1/6/164960fc-6e80-4a53-90d7-5a18c0a28083.jpg"
    }
}
