// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.shm.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Farhaven Elf
 * {2}{G}
 * Creature — Elf Druid
 * 1/1
 * When this creature enters, you may search your library for a basic land card, put it onto the battlefield tapped, then shuffle.
 */
val FarhavenElf = card("Farhaven Elf") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Elf Druid"
    oracleText = "When this creature enters, you may search your library for a basic land card, put it onto the battlefield tapped, then shuffle."
    power = 1
    toughness = 1
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        optional = true
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.BasicLand,
            destination = SearchDestination.BATTLEFIELD,
            entersTapped = true
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "113"
        artist = "Brandon Kitkouski"
        flavorText = "\"Verdant bloom does exist. It merely hides for its own safety.\""
        imageUri = "https://cards.scryfall.io/normal/front/8/9/89d7ff79-779f-4fb1-a842-56ba38e80fdd.jpg"
    }
}
