// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Agrus Kos, Wojek Veteran
 * {3}{R}{W}
 * Legendary Creature — Human Soldier
 * 3/3
 * Whenever Agrus Kos attacks, attacking red creatures get +2/+0 and attacking white creatures get +0/+2 until end of turn.
 */
val AgrusKosWojekVeteran = card("Agrus Kos, Wojek Veteran") {
    manaCost = "{3}{R}{W}"
    colorIdentity = "WR"
    typeLine = "Legendary Creature — Human Soldier"
    oracleText = "Whenever Agrus Kos attacks, attacking red creatures get +2/+0 and attacking white creatures get +0/+2 until end of turn."
    power = 3
    toughness = 3
    triggeredAbility {
        trigger = Triggers.Attacks
        effect = Effects.Composite(
            Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Creature.withColor(Color.RED).attacking()),
                Effects.ModifyStats(2, 0, EffectTarget.Self)
            ),
            Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Creature.withColor(Color.WHITE).attacking()),
                Effects.ModifyStats(0, 2, EffectTarget.Self)
            )
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "190"
        artist = "Donato Giancola"
        flavorText = "Lieutenant Kos has never met a group of recruits he could not inspire or a mob he could not quell."
        imageUri = "https://cards.scryfall.io/normal/front/c/2/c2521942-0ecd-45a9-bac6-04267a2c29ed.jpg"
    }
}
