// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Barbarian Riftcutter
 * {4}{R}
 * Creature — Human Barbarian
 * 3/3
 * {R}, Sacrifice this creature: Destroy target land.
 */
val BarbarianRiftcutter = card("Barbarian Riftcutter") {
    manaCost = "{4}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Human Barbarian"
    oracleText = "{R}, Sacrifice this creature: Destroy target land."
    power = 3
    toughness = 3
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{R}"), Costs.SacrificeSelf)
        val t = target("target", TargetPermanent(filter = TargetFilter.Land))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "114"
        artist = "Carl Critchlow"
        flavorText = "\"Riftcutters are suicidal anarchists, waving those lightning axes around so much that the walls are as likely to fall as their foes.\"\n—Heruj, Selesnya initiate"
        imageUri = "https://cards.scryfall.io/normal/front/1/5/152f4cfa-4f03-404d-a6f7-24c27505906f.jpg"
    }
}
