// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Carrion Howler
 * {3}{B}
 * Creature — Zombie Wolf
 * 2/2
 * Pay 1 life: This creature gets +2/-1 until end of turn.
 */
val CarrionHowler = card("Carrion Howler") {
    manaCost = "{3}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Zombie Wolf"
    oracleText = "Pay 1 life: This creature gets +2/-1 until end of turn."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.PayLife(1)
        effect = Effects.ModifyStats(2, -1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "79"
        artist = "John Zeleznik"
        flavorText = "They chase tirelessly after the bone-carts that speed along the streets of the Plague Quarter."
        imageUri = "https://cards.scryfall.io/normal/front/0/f/0ff031f4-df27-40de-8615-f3ea225f9830.jpg"
    }
}
