// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Centaur Safeguard
 * {2}{G/W}
 * Creature — Centaur Warrior
 * 3/1
 * ({G/W} can be paid with either {G} or {W}.)
 * When this creature dies, you may gain 3 life.
 */
val CentaurSafeguard = card("Centaur Safeguard") {
    manaCost = "{2}{G/W}"
    colorIdentity = "WG"
    typeLine = "Creature — Centaur Warrior"
    oracleText = "({G/W} can be paid with either {G} or {W}.)\nWhen this creature dies, you may gain 3 life."
    power = 3
    toughness = 1
    triggeredAbility {
        trigger = Triggers.Dies
        optional = true
        effect = GainLifeEffect(3)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "244"
        artist = "Glenn Fabry"
        flavorText = "Swift, strong, and selfless, the centaurs are the shields of the Conclave."
        imageUri = "https://cards.scryfall.io/normal/front/6/4/647d3e06-93e6-4948-a3ec-6a00bdfc0f99.jpg"
    }
}
