// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Congregation at Dawn
 * {G}{G}{W}
 * Instant
 * Search your library for up to three creature cards, reveal them, then shuffle and put those cards on top in any order.
 */
val CongregationAtDawn = card("Congregation at Dawn") {
    manaCost = "{G}{G}{W}"
    colorIdentity = "WG"
    typeLine = "Instant"
    oracleText = "Search your library for up to three creature cards, reveal them, then shuffle and put those cards on top in any order."
    spell {
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Creature,
            count = 3,
            destination = SearchDestination.TOP_OF_LIBRARY,
            reveal = true
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "198"
        artist = "Randy Gallegos"
        flavorText = "\"It is fitting that we meet in the first hour of light, for we are called by the Conclave to pierce a threat of darkness.\""
        imageUri = "https://cards.scryfall.io/normal/front/2/f/2f1b950a-b2fe-4afc-bb79-c9f4c272ea36.jpg"
    }
}
