// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Dimir Signet
 * {2}
 * Artifact
 * {1}, {T}: Add {U}{B}.
 */
val DimirSignet = card("Dimir Signet") {
    manaCost = "{2}"
    colorIdentity = "UB"
    typeLine = "Artifact"
    oracleText = "{1}, {T}: Add {U}{B}."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}"), Costs.Tap)
        effect = Effects.Composite(Effects.AddMana(Color.BLUE, 1), Effects.AddMana(Color.BLACK, 1))
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "260"
        artist = "Greg Hildebrandt"
        flavorText = "An emblem of a secret guild, the Dimir insignia is seen only by its own members—and the doomed."
        imageUri = "https://cards.scryfall.io/normal/front/9/a/9a9a1df5-a4e8-49a4-aebe-ca93894ccfcf.jpg"
    }
}
