// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Flame-Kin Zealot
 * {1}{R}{R}{W}
 * Creature — Elemental Berserker
 * 2/2
 * When this creature enters, creatures you control get +1/+1 and gain haste until end of turn.
 */
val FlameKinZealot = card("Flame-Kin Zealot") {
    manaCost = "{1}{R}{R}{W}"
    colorIdentity = "WR"
    typeLine = "Creature — Elemental Berserker"
    oracleText = "When this creature enters, creatures you control get +1/+1 and gain haste until end of turn."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature.youControl()),
            Effects.Composite(
                Effects.ModifyStats(1, 1, EffectTarget.Self),
                Effects.GrantKeyword(Keyword.HASTE, EffectTarget.Self)
            )
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "206"
        artist = "Arnie Swekel"
        flavorText = "Boros soldiers are like a cache of bombs ready to explode, and the flame-kin light their fuses."
        imageUri = "https://cards.scryfall.io/normal/front/a/e/aec53f16-5bf7-4ef5-b83e-9e36463d1640.jpg"
    }
}
