// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Flow of Ideas
 * {5}{U}
 * Sorcery
 * Draw a card for each Island you control.
 */
val FlowOfIdeas = card("Flow of Ideas") {
    manaCost = "{5}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Draw a card for each Island you control."
    spell {
        effect = DrawCardsEffect(
            DynamicAmount.AggregateBattlefield(Player.You, GameObjectFilter.Land.withSubtype(Subtype.ISLAND))
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "50"
        artist = "Dan Murayama Scott"
        flavorText = "\"A system to direct the flow of Ravnica's entire water supply? Thinking a bit small, aren't we?\"\n—Trivaz, Izzet mage"
        imageUri = "https://cards.scryfall.io/normal/front/2/7/27203b79-b383-4698-8b81-b6198c51c2f6.jpg"
    }
}
