// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Glass Golem
 * {5}
 * Artifact Creature — Golem
 * 6/2
 */
val GlassGolem = card("Glass Golem") {
    manaCost = "{5}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Golem"
    power = 6
    toughness = 2
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "261"
        artist = "Glen Angus"
        flavorText = "Izzet artificers have learned to steer their beautiful constructs clear of Boros warhammers—and the opera house."
        imageUri = "https://cards.scryfall.io/normal/front/1/b/1b87dc27-3cea-4101-aec5-ca0b96978476.jpg"
    }
}
