// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Grayscaled Gharial
 * {U}
 * Creature — Crocodile
 * 1/1
 * Islandwalk (This creature can't be blocked as long as defending player controls an Island.)
 */
val GrayscaledGharial = card("Grayscaled Gharial") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Creature — Crocodile"
    oracleText = "Islandwalk (This creature can't be blocked as long as defending player controls an Island.)"
    power = 1
    toughness = 1
    keywords(Keyword.ISLANDWALK)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "52"
        artist = "Chris Dien"
        flavorText = "Each tooth carries enough bacteria to kill a person in a day or two. But then, gharials do have 138 teeth."
        imageUri = "https://cards.scryfall.io/normal/front/8/9/89c2c94a-31df-4789-a309-4cdfe7f6a719.jpg"
    }
}
