// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Greater Forgeling
 * {3}{R}{R}
 * Creature — Elemental
 * 3/4
 * {1}{R}: This creature gets +3/-3 until end of turn.
 */
val GreaterForgeling = card("Greater Forgeling") {
    manaCost = "{3}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Elemental"
    oracleText = "{1}{R}: This creature gets +3/-3 until end of turn."
    power = 3
    toughness = 4
    activatedAbility {
        cost = Costs.Mana("{1}{R}")
        effect = Effects.ModifyStats(3, -3, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "129"
        artist = "Marcelo Vignali"
        flavorText = "Few have seen the inner workings of Ravnica's furnaces, but neighboring districts catch brief glimpses in the horrors that escape the flames."
        imageUri = "https://cards.scryfall.io/normal/front/e/e/eef8ad11-4ffa-4878-9354-737be6f9e90c.jpg"
    }
}
