// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.effects.ForEachPlayerEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Hammerfist Giant
 * {4}{R}{R}
 * Creature — Giant Warrior
 * 5/4
 * {T}: This creature deals 4 damage to each creature without flying and each player.
 */
val HammerfistGiant = card("Hammerfist Giant") {
    manaCost = "{4}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Giant Warrior"
    oracleText = "{T}: This creature deals 4 damage to each creature without flying and each player."
    power = 5
    toughness = 4
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.Composite(
            Effects.ForEachInGroup(
                GroupFilter(GameObjectFilter.Creature.withoutKeyword(Keyword.FLYING)),
                DealDamageEffect(4, EffectTarget.Self)
            ),
            ForEachPlayerEffect(Player.Each, listOf(DealDamageEffect(4, EffectTarget.Controller)))
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "130"
        artist = "Carl Critchlow"
        flavorText = "\"Oh sure, they buy a lot of ale, but I always find myself needing to rebuild after the giants have paid a visit.\"\n—Belko, owner of Titan's Keg tavern"
        imageUri = "https://cards.scryfall.io/normal/front/4/4/446f946d-9715-466e-b322-905995d28107.jpg"
    }
}
