// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.LoseLifeEffect
import com.wingedsheep.sdk.scripting.targets.TargetPlayer


/**
 * Infectious Host
 * {2}{B}
 * Creature — Zombie
 * 1/1
 * When this creature dies, target player loses 2 life.
 */
val InfectiousHost = card("Infectious Host") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Zombie"
    oracleText = "When this creature dies, target player loses 2 life."
    power = 1
    toughness = 1
    triggeredAbility {
        trigger = Triggers.Dies
        val t = target("target", TargetPlayer())
        effect = LoseLifeEffect(2, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "91"
        artist = "rk post"
        flavorText = "\"Lost man, dead man, knocking on the door. Cankerman, soreman, knock no more.\"\n—Ravnican children's rhyme"
        imageUri = "https://cards.scryfall.io/normal/front/1/1/11858b4f-3a90-4990-9984-d888c000ec73.jpg"
    }
}
