// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Ivy Dancer
 * {2}{G}
 * Creature — Dryad Shaman
 * 1/2
 * {T}: Target creature gains forestwalk until end of turn. (It can't be blocked as long as defending player controls a Forest.)
 */
val IvyDancer = card("Ivy Dancer") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Dryad Shaman"
    oracleText = "{T}: Target creature gains forestwalk until end of turn. (It can't be blocked as long as defending player controls a Forest.)"
    power = 1
    toughness = 2
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.GrantKeyword(Keyword.FORESTWALK, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "171"
        artist = "Terese Nielsen"
        flavorText = "Her ivy locks are a remnant of the wooded wilds now lost to Ravnica forever."
        imageUri = "https://cards.scryfall.io/normal/front/7/3/73597c90-a527-4338-9668-126c6cf15927.jpg"
    }
}
