// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Keening Banshee
 * {2}{B}{B}
 * Creature — Spirit
 * 2/2
 * Flying
 * When this creature enters, target creature gets -2/-2 until end of turn.
 */
val KeeningBanshee = card("Keening Banshee") {
    manaCost = "{2}{B}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Spirit"
    oracleText = "Flying\nWhen this creature enters, target creature gets -2/-2 until end of turn."
    power = 2
    toughness = 2
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(-2, -2, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "92"
        artist = "Robert Bliss"
        flavorText = "Her cold wail echoes in the alleys and under-eaves, finding the unfortunate and turning their blood to ice."
        imageUri = "https://cards.scryfall.io/normal/front/0/8/0866b383-dced-459e-9510-38248a29dd14.jpg"
    }
}
