// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter


/**
 * Oathsworn Giant
 * {4}{W}{W}
 * Creature — Giant Soldier
 * 3/4
 * Vigilance
 * Other creatures you control get +0/+2 and have vigilance.
 */
val OathswornGiant = card("Oathsworn Giant") {
    manaCost = "{4}{W}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Giant Soldier"
    oracleText = "Vigilance\nOther creatures you control get +0/+2 and have vigilance."
    power = 3
    toughness = 4
    keywords(Keyword.VIGILANCE)
    staticAbility {
        ability = ModifyStats(
            powerBonus = 0,
            toughnessBonus = 2,
            filter = GroupFilter(GameObjectFilter.Creature.youControl(), excludeSelf = true)
        )
    }
    staticAbility {
        ability = GrantKeyword(
            Keyword.VIGILANCE,
            GroupFilter(GameObjectFilter.Creature.youControl(), excludeSelf = true)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "27"
        artist = "Daren Bader"
        flavorText = "The town stands on his ancestors' former burial grounds. Even with the graves long gone, he continues his determined vigil."
        imageUri = "https://cards.scryfall.io/normal/front/2/c/2c342b0f-a8a5-4991-a0a2-fd75b54e1de2.jpg"
    }
}
