// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Recollect
 * {2}{G}
 * Sorcery
 * Return target card from your graveyard to your hand.
 */
val Recollect = card("Recollect") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "Return target card from your graveyard to your hand."
    spell {
        val t = target(
            "target",
            TargetObject(filter = TargetFilter(GameObjectFilter.Any.ownedByYou(), zone = Zone.GRAVEYARD)),
        )
        effect = Effects.Move(t, Zone.HAND)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "178"
        artist = "Pete Venters"
        flavorText = "\"The bones of the past will tell their tales—if you know how to speak their language.\"\n—Savra"
        imageUri = "https://cards.scryfall.io/normal/front/5/2/52aa7f09-a2cc-4bef-857a-32bcccb7366a.jpg"
    }
}
