// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Seismic Spike
 * {2}{R}{R}
 * Sorcery
 * Destroy target land. Add {R}{R}.
 */
val SeismicSpike = card("Seismic Spike") {
    manaCost = "{2}{R}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Destroy target land. Add {R}{R}."
    spell {
        val t = target("target", TargetPermanent(filter = TargetFilter.Land))
        effect = Effects.Composite(
            Effects.Move(t, Zone.GRAVEYARD, byDestruction = true),
            Effects.AddMana(Color.RED, 2)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "141"
        artist = "John Avon"
        flavorText = "Natural disasters in Ravnica are largely nullified by the Izzet. Unnatural disasters, on the other hand, happen all the time."
        imageUri = "https://cards.scryfall.io/normal/front/b/9/b9caddbe-1329-4ac2-9071-6fc5059d4dec.jpg"
    }
}
