// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Sparkmage Apprentice
 * {1}{R}
 * Creature — Human Wizard
 * 1/1
 * When this creature enters, it deals 1 damage to any target.
 */
val SparkmageApprentice = card("Sparkmage Apprentice") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Human Wizard"
    oracleText = "When this creature enters, it deals 1 damage to any target."
    power = 1
    toughness = 1
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(1, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "144"
        artist = "Mark Poole"
        flavorText = "Pajik was amazed and pleased at his newfound powers. His pet cat Rivin was slightly less enthusiastic."
        imageUri = "https://cards.scryfall.io/normal/front/6/c/6ca91f7f-4b17-469e-8650-4c18e1521ea9.jpg"
    }
}
