// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Undercity Shade
 * {4}{B}
 * Creature — Shade
 * 1/1
 * Fear (This creature can't be blocked except by artifact creatures and/or black creatures.)
 * {B}: This creature gets +1/+1 until end of turn.
 */
val UndercityShade = card("Undercity Shade") {
    manaCost = "{4}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Shade"
    oracleText = "Fear (This creature can't be blocked except by artifact creatures and/or black creatures.)\n{B}: This creature gets +1/+1 until end of turn."
    power = 1
    toughness = 1
    keywords(Keyword.FEAR)
    activatedAbility {
        cost = Costs.Mana("{B}")
        effect = Effects.ModifyStats(1, 1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "110"
        artist = "Dana Knutson"
        flavorText = "\"Officially, there's nothing under that bridge to hunt . . . . Unofficially, my torchers are too terrified to go there after nightfall.\"\n—Agrus Kos"
        imageUri = "https://cards.scryfall.io/normal/front/6/6/6609aa2e-6832-4c20-beda-e5f2506bf9b2.jpg"
    }
}
