// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Ursapine
 * {3}{G}{G}
 * Creature — Beast
 * 3/3
 * {G}: Target creature gets +1/+1 until end of turn.
 */
val Ursapine = card("Ursapine") {
    manaCost = "{3}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Beast"
    oracleText = "{G}: Target creature gets +1/+1 until end of turn."
    power = 3
    toughness = 3
    activatedAbility {
        cost = Costs.Mana("{G}")
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(1, 1, t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "188"
        artist = "Jim Murray"
        flavorText = "A friendly ursapine means a constant supply of sharp spears. An unfriendly one means a constant supply of small holes."
        imageUri = "https://cards.scryfall.io/normal/front/b/a/ba547810-c82a-498b-81eb-e81a8dcbbd42.jpg"
    }
}
