// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.RegenerateEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Votary of the Conclave
 * {W}
 * Creature — Human Soldier
 * 1/1
 * {2}{G}: Regenerate this creature.
 */
val VotaryOfTheConclave = card("Votary of the Conclave") {
    manaCost = "{W}"
    colorIdentity = "WG"
    typeLine = "Creature — Human Soldier"
    oracleText = "{2}{G}: Regenerate this creature."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Mana("{2}{G}")
        effect = RegenerateEffect(EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "35"
        artist = "Alan Pollack"
        flavorText = "An ageless order, the votaries receive the gift of rejuvenation from the temple gardens they guard."
        imageUri = "https://cards.scryfall.io/normal/front/9/b/9bb6f929-5a19-421b-ae88-9bbb7e64756c.jpg"
    }
}
