// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rav.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * War-Torch Goblin
 * {R}
 * Creature — Goblin Warrior
 * 1/1
 * {R}, Sacrifice this creature: It deals 2 damage to target blocking creature.
 */
val WarTorchGoblin = card("War-Torch Goblin") {
    manaCost = "{R}"
    colorIdentity = "R"
    typeLine = "Creature — Goblin Warrior"
    oracleText = "{R}, Sacrifice this creature: It deals 2 damage to target blocking creature."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{R}"), Costs.SacrificeSelf)
        val t = target("target", TargetCreature(filter = TargetFilter.BlockingCreature))
        effect = DealDamageEffect(2, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "151"
        artist = "Alex Horley-Orlandelli"
        flavorText = "\"In a town shaped by the subtle machinations and political intrigue of its guilds, it's reassuring to see a goblin waving his torch and screaming about some nonsense or other.\"\n—Agrus Kos"
        imageUri = "https://cards.scryfall.io/normal/front/2/5/259469b3-1212-4030-97ae-a84f132798d4.jpg"
    }
}
