// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dsk.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter


/**
 * Split Up
 * {1}{W}{W}
 * Sorcery
 * Choose one —
 * • Destroy all tapped creatures.
 * • Destroy all untapped creatures.
 */
val SplitUp = card("Split Up") {
    manaCost = "{1}{W}{W}"
    colorIdentity = "W"
    typeLine = "Sorcery"
    oracleText = "Choose one —\n• Destroy all tapped creatures.\n• Destroy all untapped creatures."
    spell {
        // `Effects.DestroyAll`, not an iteration: a "destroy all" is one effect, so it gathers the
        // matching permanents and destroys the collection, and they leave the battlefield in a
        // single event. A `ForEachInGroup` destroys them one at a time, so a dies-trigger on the
        // first would see the rest still on the battlefield, and a creature whose toughness comes
        // from the others could survive a sweep that should have killed it.
        modal(chooseCount = 1) {
            mode("Destroy all tapped creatures") {
                effect = Effects.DestroyAll(GameObjectFilter.Creature.tapped())
            }
            mode("Destroy all untapped creatures") {
                effect = Effects.DestroyAll(GameObjectFilter.Creature.untapped())
            }
        }
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "32"
        artist = "Dominik Mayer"
        flavorText = "\"Don't be a wimp. We'll cover more ground this way.\"\n—Rian, former survivor"
        imageUri = "https://cards.scryfall.io/normal/front/1/b/1bb9a5b1-48d2-453e-8991-c788bc63e482.jpg"
    }
}
