// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dgm.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.ModifyStats


/**
 * Unflinching Courage
 * {1}{G}{W}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature gets +2/+2 and has trample and lifelink. (Damage dealt by the creature also causes its controller to gain that much life.)
 */
val UnflinchingCourage = card("Unflinching Courage") {
    manaCost = "{1}{G}{W}"
    colorIdentity = "WG"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature gets +2/+2 and has trample and lifelink. (Damage dealt by the creature also causes its controller to gain that much life.)"
    auraTarget = Targets.Creature
    staticAbility {
        ability = ModifyStats(2, 2)
    }
    staticAbility {
        ability = GrantKeyword(Keyword.TRAMPLE)
    }
    staticAbility {
        ability = GrantKeyword(Keyword.LIFELINK)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "111"
        artist = "Mike Bierek"
        flavorText = "As Trostani's influence grew, vitality spread through the Conclave—much to the other guilds' dismay."
        imageUri = "https://cards.scryfall.io/normal/front/3/5/35952c24-d728-4ec6-b0d1-b8183a18554a.jpg"
    }
}
