// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Kodama's Reach
 * {2}{G}
 * Sorcery — Arcane
 * Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle.
 */
val KodamasReach = card("Kodama's Reach") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Sorcery — Arcane"
    oracleText = "Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle."
    spell {
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.BasicLand,
            count = 2,
            destination = SearchDestination.HAND,
            entersTapped = true,
            reveal = true
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "225"
        artist = "Heather Hudson"
        flavorText = "\"The land grows only where the kami will it.\"\n—Dosan the Falling Leaf"
        imageUri = "https://cards.scryfall.io/normal/front/8/5/85d207ac-0680-47ef-85d9-4323c1321d6f.jpg"
    }
}
