// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.m20.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Spectral Sailor
 * {U}
 * Creature — Spirit Pirate
 * 1/1
 * Flash (You may cast this spell any time you could cast an instant.)
 * Flying
 * {3}{U}: Draw a card.
 */
val SpectralSailor = card("Spectral Sailor") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Creature — Spirit Pirate"
    oracleText = "Flash (You may cast this spell any time you could cast an instant.)\nFlying\n{3}{U}: Draw a card."
    power = 1
    toughness = 1
    keywords(Keyword.FLASH, Keyword.FLYING)
    activatedAbility {
        cost = Costs.Mana("{3}{U}")
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "76"
        artist = "Cristi Balanescu"
        flavorText = "\"Any ship that sails on these mean seas for long is bound to pick up a ghost or two.\"\n—Admiral Beckett Brass"
        imageUri = "https://cards.scryfall.io/normal/front/6/7/67483891-36d1-46f2-8b4f-b8b7bd54bdcc.jpg"
    }
}
