// === Originally GENERATED by mtgish-tooling from the mtgish oracle IR; hand-corrected since. ===
// The emitter renders cascade as the bare `Keyword.CASCADE`, which the engine never reads — see
// the note on the definition below.

package com.wingedsheep.mtg.sets.definitions.cmr.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Annoyed Altisaur
 * {5}{G}{G}
 * Creature — Dinosaur
 * 6/5
 * Reach, trample
 * Cascade (When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost. Put the exiled cards on the bottom in a random order.)
 *
 * `Keyword.CASCADE` is display-only — nothing in the rules engine reads it. Cascade is itself a
 * "when you cast this spell" triggered ability (CR 702.85a), so the behavior lives in the cast
 * trigger below, mirroring `sos/cards/QuandrixTheProof.kt`. The generated render carried only the
 * keyword, which left the card inert; Modern Horizons 3 reprints it (`mh3/cards/AnnoyedAltisaurReprint.kt`),
 * so the trigger is wired here rather than shipping a reprint that does nothing.
 */
val AnnoyedAltisaur = card("Annoyed Altisaur") {
    manaCost = "{5}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Dinosaur"
    oracleText = "Reach, trample\nCascade (When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost. Put the exiled cards on the bottom in a random order.)"
    power = 6
    toughness = 5
    keywords(Keyword.REACH, Keyword.TRAMPLE, Keyword.CASCADE)

    triggeredAbility {
        trigger = Triggers.WhenYouCastThisSpell()
        effect = Effects.Cascade
        description = "Cascade"
    }

    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "216"
        artist = "Lars Grant-West"
        flavorText = "It pairs a long neck with a short temper."
        imageUri = "https://cards.scryfall.io/normal/front/7/5/7536d618-0c98-45bb-913b-b8117b4acf87.jpg"
    }
}
