// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.cmr.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Apex Devastator
 * {8}{G}{G}
 * Creature — Chimera Hydra
 * 10/10
 * Cascade, cascade, cascade, cascade (When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost. Put the exiled cards on the bottom in a random order. Multiple instances of cascade each trigger separately.)
 */
val ApexDevastator = card("Apex Devastator") {
    manaCost = "{8}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Chimera Hydra"
    oracleText = "Cascade, cascade, cascade, cascade (When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost. Put the exiled cards on the bottom in a random order. Multiple instances of cascade each trigger separately.)"
    power = 10
    toughness = 10
    keywords(Keyword.CASCADE)
    metadata {
        rarity = Rarity.MYTHIC
        collectorNumber = "217"
        artist = "Svetlin Velinov"
        imageUri = "https://cards.scryfall.io/normal/front/8/f/8fa281e1-5c48-4bba-b8e9-88c6f5f53abb.jpg"
    }
}
