// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.cmr.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Ghen, Arcanum Weaver
 * {R}{W}{B}
 * Legendary Creature — Human Wizard
 * 2/3
 * {R}{W}{B}, {T}, Sacrifice an enchantment: Return target enchantment card from your graveyard to the battlefield.
 */
val GhenArcanumWeaver = card("Ghen, Arcanum Weaver") {
    manaCost = "{R}{W}{B}"
    colorIdentity = "WBR"
    typeLine = "Legendary Creature — Human Wizard"
    oracleText = "{R}{W}{B}, {T}, Sacrifice an enchantment: Return target enchantment card from your graveyard to the battlefield."
    power = 2
    toughness = 3
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{R}{W}{B}"), Costs.Tap, Costs.Sacrifice(GameObjectFilter.Enchantment))
        val t = target(
            "target",
            TargetObject(filter = TargetFilter(GameObjectFilter.Enchantment.ownedByYou(), zone = Zone.GRAVEYARD))
        )
        effect = Effects.PutOntoBattlefieldFromGraveyard(t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "275"
        artist = "Kieran Yanner"
        flavorText = "\"Any apprentice with a spellbook and two sticks can churn out a fireball. This is different. This is art.\""
        imageUri = "https://cards.scryfall.io/normal/front/4/b/4b335496-05d2-40f5-a52c-10029f7fa008.jpg"
    }
}
