// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.cmr.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Magus of the Order
 * {2}{G}{G}
 * Creature — Human Wizard
 * 3/3
 * {G}, {T}, Sacrifice this creature and another green creature: Search your library for a green creature card, put it onto the battlefield, then shuffle.
 */
val MagusOfTheOrder = card("Magus of the Order") {
    manaCost = "{2}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Human Wizard"
    oracleText = "{G}, {T}, Sacrifice this creature and another green creature: Search your library for a green creature card, put it onto the battlefield, then shuffle."
    power = 3
    toughness = 3
    activatedAbility {
        cost = Costs.Composite(
            Costs.Mana("{G}"),
            Costs.Tap,
            Costs.Composite(Costs.SacrificeSelf, Costs.Sacrifice(GameObjectFilter.Creature.withColor(Color.GREEN)))
        )
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Creature.withColor(Color.GREEN),
            destination = SearchDestination.BATTLEFIELD
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "242"
        artist = "Tomasz Jedruszek"
        flavorText = "\"Life for life. The cost is always the same.\""
        imageUri = "https://cards.scryfall.io/normal/front/a/9/a93e5fa9-cfe3-487b-af77-0dbf6c68ee04.jpg"
    }
}
