// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.soi.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Open the Armory
 * {1}{W}
 * Sorcery
 * Search your library for an Aura or Equipment card, reveal it, put it into your hand, then shuffle.
 */
val OpenTheArmory = card("Open the Armory") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Sorcery"
    oracleText = "Search your library for an Aura or Equipment card, reveal it, put it into your hand, then shuffle."
    spell {
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Enchantment.withSubtype("Aura"),
            destination = SearchDestination.HAND,
            reveal = true
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "32"
        artist = "Steve Prescott"
        flavorText = "\"Once Avacyn returned, I hoped I'd never need these things again. I didn't think I'd be dusting them off to use against angels.\""
        imageUri = "https://cards.scryfall.io/normal/front/0/7/07dc0c44-908f-40e9-9c6a-e1ef699e6d2e.jpg"
    }
}
