// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.soi.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.CreateTokenEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Rise from the Tides
 * {5}{U}
 * Sorcery
 * Create a tapped 2/2 black Zombie creature token for each instant and sorcery card in your graveyard.
 */
val RiseFromTheTides = card("Rise from the Tides") {
    manaCost = "{5}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Create a tapped 2/2 black Zombie creature token for each instant and sorcery card in your graveyard."
    spell {
        effect = CreateTokenEffect(
            count = DynamicAmount.Count(Player.You, Zone.GRAVEYARD, GameObjectFilter.InstantOrSorcery),
            power = 2,
            toughness = 2,
            colors = setOf(Color.BLACK),
            creatureTypes = setOf("Zombie"),
            tapped = true
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "83"
        artist = "Dave Kendall"
        flavorText = "\"Dear brother, it's sweet that you have chosen to share your toys with Ludevic, but I too have found some new playmates.\"\n—Ghoulcaller Gisa"
        imageUri = "https://cards.scryfall.io/normal/front/6/e/6e099a6a-97c4-42cd-aca6-5e1a2da0d5e5.jpg"
    }
}
