// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.soi.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Thraben Inspector
 * {W}
 * Creature — Human Soldier
 * 1/2
 * When this creature enters, investigate. (Create a Clue token. It's an artifact with "{2}, Sacrifice this token: Draw a card.")
 */
val ThrabenInspector = card("Thraben Inspector") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Soldier"
    oracleText = "When this creature enters, investigate. (Create a Clue token. It's an artifact with \"{2}, Sacrifice this token: Draw a card.\")"
    power = 1
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.Investigate()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "44"
        artist = "Matt Stewart"
        flavorText = "\"If you've been at this as long as I have, nothing can surprise you. That's the hope, at least.\""
        imageUri = "https://cards.scryfall.io/normal/front/d/1/d140c3b7-ca78-483d-baeb-307b624fea8b.jpg"
    }
}
