// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.soi.cards

import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.ConditionalEffect
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Traverse the Ulvenwald
 * {G}
 * Sorcery
 * Search your library for a basic land card, reveal it, put it into your hand, then shuffle.
 * Delirium — If there are four or more card types among cards in your graveyard, instead search your library for a creature or land card, reveal it, put it into your hand, then shuffle.
 */
val TraverseTheUlvenwald = card("Traverse the Ulvenwald") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "Search your library for a basic land card, reveal it, put it into your hand, then shuffle.\nDelirium — If there are four or more card types among cards in your graveyard, instead search your library for a creature or land card, reveal it, put it into your hand, then shuffle."
    spell {
        effect = ConditionalEffect(
            condition = Conditions.Delirium(4),
            effect = Patterns.Library.searchLibrary(
                filter = GameObjectFilter.CreatureOrLand,
                destination = SearchDestination.HAND,
                reveal = true
            ),
            elseEffect = Patterns.Library.searchLibrary(
                filter = GameObjectFilter.BasicLand,
                destination = SearchDestination.HAND,
                reveal = true
            )
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "234"
        artist = "Vincent Proce"
        imageUri = "https://cards.scryfall.io/normal/front/b/b/bbc69a17-db08-4b4a-bc37-98a12ea108dc.jpg"
    }
}
