// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Alarum
 * {1}{W}
 * Instant
 * Untap target nonattacking creature. It gets +1/+3 until end of turn.
 */
val Alarum = card("Alarum") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Untap target nonattacking creature. It gets +1/+3 until end of turn."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.Untap(t),
            Effects.ModifyStats(1, 3, t)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "2"
        artist = "Andrew Robinson"
        flavorText = "\"One timely cry of warning can save nine of surprise.\"\n—Sidar Jabari"
        imageUri = "https://cards.scryfall.io/normal/front/1/5/155f2aa6-6c47-4a06-b0ef-2d9205cd133e.jpg"
    }
}
