// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.LoseLifeEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Benthic Djinn
 * {2}{U}{B}
 * Creature — Djinn
 * 5/3
 * Islandwalk (This creature can't be blocked as long as defending player controls an Island.)
 * At the beginning of your upkeep, you lose 2 life.
 */
val BenthicDjinn = card("Benthic Djinn") {
    manaCost = "{2}{U}{B}"
    colorIdentity = "UB"
    typeLine = "Creature — Djinn"
    oracleText = "Islandwalk (This creature can't be blocked as long as defending player controls an Island.)\nAt the beginning of your upkeep, you lose 2 life."
    power = 5
    toughness = 3
    keywords(Keyword.ISLANDWALK)
    triggeredAbility {
        trigger = Triggers.YourUpkeep
        effect = LoseLifeEffect(2, EffectTarget.Controller)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "257"
        artist = "Adam Rex"
        flavorText = "\"In all my years I've only met one mage who successfully trapped a djinn—and none who tried and failed.\"\n—Talibah, embermage"
        imageUri = "https://cards.scryfall.io/normal/front/9/5/95b03586-8d04-4114-a7ce-b8c8ab5ff857.jpg"
    }
}
