// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Blighted Shaman
 * {1}{B}
 * Creature — Human Cleric Shaman
 * 1/1
 * {T}, Sacrifice a Swamp: Target creature gets +1/+1 until end of turn.
 * {T}, Sacrifice a creature: Target creature gets +2/+2 until end of turn.
 */
val BlightedShaman = card("Blighted Shaman") {
    manaCost = "{1}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Human Cleric Shaman"
    oracleText = "{T}, Sacrifice a Swamp: Target creature gets +1/+1 until end of turn.\n{T}, Sacrifice a creature: Target creature gets +2/+2 until end of turn."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.Sacrifice(GameObjectFilter.Land.withSubtype(Subtype.SWAMP)))
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(1, 1, t)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.Sacrifice(GameObjectFilter.Creature))
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(2, 2, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "107"
        artist = "Ian Miller"
        imageUri = "https://cards.scryfall.io/normal/front/b/5/b5f2b33c-8d4d-406e-98de-b92d92a3012a.jpg"
    }
}
