// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Blistering Barrier
 * {2}{R}
 * Creature — Wall
 * 5/2
 * Defender (This creature can't attack.)
 */
val BlisteringBarrier = card("Blistering Barrier") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Wall"
    oracleText = "Defender (This creature can't attack.)"
    power = 5
    toughness = 2
    keywords(Keyword.DEFENDER)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "159"
        artist = "David Ho"
        flavorText = "I live without food, stand without leg, wound without force, and am harder to fight than to kill. What am I?\n—Femeref riddle"
        imageUri = "https://cards.scryfall.io/normal/front/5/6/56d000d8-24e1-4cf3-bed9-e68a89c8f569.jpg"
    }
}
