// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Breathstealer
 * {2}{B}
 * Creature — Nightstalker
 * 2/2
 * {B}: This creature gets +1/-1 until end of turn.
 */
val Breathstealer = card("Breathstealer") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Nightstalker"
    oracleText = "{B}: This creature gets +1/-1 until end of turn."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.Mana("{B}")
        effect = Effects.ModifyStats(1, -1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "109"
        artist = "Cliff Nielsen"
        flavorText = "\"As a child, I slept with a cloth over my face, to hide from the spirits that might pull the air from my lungs.\"\n—Mosi, Femeref weaver"
        imageUri = "https://cards.scryfall.io/normal/front/0/c/0cd9da69-5e57-4719-a712-630c9464fada.jpg"
    }
}
