// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.RegenerateEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Cadaverous Knight
 * {2}{B}
 * Creature — Zombie Knight
 * 2/2
 * Flanking (Whenever a creature without flanking blocks this creature, the blocking creature gets -1/-1 until end of turn.)
 * {1}{B}{B}: Regenerate this creature.
 */
val CadaverousKnight = card("Cadaverous Knight") {
    manaCost = "{2}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Zombie Knight"
    oracleText = "Flanking (Whenever a creature without flanking blocks this creature, the blocking creature gets -1/-1 until end of turn.)\n{1}{B}{B}: Regenerate this creature."
    power = 2
    toughness = 2
    keywords(Keyword.FLANKING)
    activatedAbility {
        cost = Costs.Mana("{1}{B}{B}")
        effect = RegenerateEffect(EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "110"
        artist = "Dermot Power"
        flavorText = "Grieve for the soul in death dishonored.\n—Shadow Guild saying"
        imageUri = "https://cards.scryfall.io/normal/front/0/6/06e954b2-c8ce-4b6c-a118-4a14ffa72063.jpg"
    }
}
