// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.ProtectionScope


/**
 * Cerulean Wyvern
 * {4}{U}
 * Creature — Drake
 * 3/3
 * Flying, protection from green
 */
val CeruleanWyvern = card("Cerulean Wyvern") {
    manaCost = "{4}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Drake"
    oracleText = "Flying, protection from green"
    power = 3
    toughness = 3
    keywords(Keyword.FLYING)
    keywordAbility(KeywordAbility.Protection(ProtectionScope.Color(Color.GREEN)))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "57"
        artist = "Gerry Grace"
        flavorText = "\"Once, a Quirion asked why I was so cautious when the day was clear. I told him of the sky-blue hide of the cerluean wyvern, and he offered me double if I could conjure a strong tailwind!\"\n—Sisay, Captain of the Weatherlight"
        imageUri = "https://cards.scryfall.io/normal/front/5/c/5c599f95-c0dd-4dd8-a8d7-9481df0cf649.jpg"
    }
}
