// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Crash of Rhinos
 * {6}{G}{G}
 * Creature — Rhino
 * 8/4
 * Trample
 */
val CrashOfRhinos = card("Crash of Rhinos") {
    manaCost = "{6}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Rhino"
    oracleText = "Trample"
    power = 8
    toughness = 4
    keywords(Keyword.TRAMPLE)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "210"
        artist = "Steve White"
        flavorText = "Love is like a rhino, short-sighted and hasty; if it cannot find a way, it will make a way.\n—Femeref adage"
        imageUri = "https://cards.scryfall.io/normal/front/d/7/d74e0337-d9ac-4bf2-b2b5-aadc97433030.jpg"
    }
}
