// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersTapped
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Elixir of Vitality
 * {4}
 * Artifact
 * This artifact enters tapped.
 * {T}, Sacrifice this artifact: You gain 4 life.
 * {8}, {T}, Sacrifice this artifact: You gain 8 life.
 */
val ElixirOfVitality = card("Elixir of Vitality") {
    manaCost = "{4}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "This artifact enters tapped.\n{T}, Sacrifice this artifact: You gain 4 life.\n{8}, {T}, Sacrifice this artifact: You gain 8 life."
    replacementEffect(EntersTapped())
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.SacrificeSelf)
        effect = GainLifeEffect(4)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{8}"), Costs.Tap, Costs.SacrificeSelf)
        effect = GainLifeEffect(8)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "300"
        artist = "Douglas Shuler"
        flavorText = "\"Eternal life or your money back.\"\n—Unnamed Suq'Ata merchant, deceased"
        imageUri = "https://cards.scryfall.io/normal/front/6/0/60450239-6055-4561-9f8c-565b4e4d9cb1.jpg"
    }
}
