// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Femeref Healer
 * {1}{W}
 * Creature — Human Cleric
 * 1/1
 * {T}: Prevent the next 1 damage that would be dealt to any target this turn.
 */
val FemerefHealer = card("Femeref Healer") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Cleric"
    oracleText = "{T}: Prevent the next 1 damage that would be dealt to any target this turn."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", AnyTarget())
        effect = Effects.PreventNextDamage(1, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "17"
        artist = "Steve Luke"
        flavorText = "\"Faith is my shield, and hope is my armor; I am vulnerable only to myself.\"\n—Asmira, Holy Avenger"
        imageUri = "https://cards.scryfall.io/normal/front/9/0/90dedd5e-e2ee-46ec-8541-27f1548b2a2a.jpg"
    }
}
