// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersTapped
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Grasslands
 * Land
 * This land enters tapped.
 * {T}, Sacrifice this land: Search your library for a Forest or Plains card, put it onto the battlefield, then shuffle.
 */
val Grasslands = card("Grasslands") {
    manaCost = ""
    colorIdentity = ""
    typeLine = "Land"
    oracleText = "This land enters tapped.\n{T}, Sacrifice this land: Search your library for a Forest or Plains card, put it onto the battlefield, then shuffle."
    replacementEffect(EntersTapped())
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.SacrificeSelf)
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Land.withAnySubtype("Forest", "Plains"),
            destination = SearchDestination.BATTLEFIELD
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "327"
        artist = "John Avon"
        imageUri = "https://cards.scryfall.io/normal/front/6/5/65f5efac-ef98-4be2-abcc-1aa38bf66b06.jpg"
    }
}
