// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Jolrael's Centaur
 * {1}{G}{G}
 * Creature — Centaur Archer
 * 2/2
 * Shroud (This creature can't be the target of spells or abilities.)
 * Flanking (Whenever a creature without flanking blocks this creature, the blocking creature gets -1/-1 until end of turn.)
 */
val JolraelsCentaur = card("Jolrael's Centaur") {
    manaCost = "{1}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Centaur Archer"
    oracleText = "Shroud (This creature can't be the target of spells or abilities.)\nFlanking (Whenever a creature without flanking blocks this creature, the blocking creature gets -1/-1 until end of turn.)"
    power = 2
    toughness = 2
    keywords(Keyword.SHROUD, Keyword.FLANKING)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "222"
        artist = "Junior Tomlin"
        flavorText = "\"What need have I for cavalry when I can have horse and rider both in one?\"\n—Jolrael"
        imageUri = "https://cards.scryfall.io/normal/front/3/1/31588ea3-31d2-4118-9b9f-4ce820c16a15.jpg"
    }
}
