// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.ProtectionScope


/**
 * Karoo Meerkat
 * {1}{G}
 * Creature — Mongoose
 * 2/1
 * Protection from blue
 */
val KarooMeerkat = card("Karoo Meerkat") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Mongoose"
    oracleText = "Protection from blue"
    power = 2
    toughness = 1
    keywordAbility(KeywordAbility.Protection(ProtectionScope.Color(Color.BLUE)))
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "225"
        artist = "Janine Johnston"
        flavorText = "\"Be like the meerkat, my daughters: ever vigilant, true to your own, and wary of strangers.\"\n—Nabil Alamat, Suq'Ata merchant"
        imageUri = "https://cards.scryfall.io/normal/front/1/6/16396594-4f59-4600-8e39-d99544062265.jpg"
    }
}
