// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersTapped
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Marble Diamond
 * {2}
 * Artifact
 * This artifact enters tapped.
 * {T}: Add {W}.
 */
val MarbleDiamond = card("Marble Diamond") {
    manaCost = "{2}"
    colorIdentity = "W"
    typeLine = "Artifact"
    oracleText = "This artifact enters tapped.\n{T}: Add {W}."
    replacementEffect(EntersTapped())
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddMana(Color.WHITE)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "310"
        artist = "Jeff Miracola"
        imageUri = "https://cards.scryfall.io/normal/front/4/7/4731eb16-3088-4d4d-80a4-7e39d00c1a87.jpg"
    }
}
