// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Nettletooth Djinn
 * {3}{G}
 * Creature — Djinn
 * 4/4
 * At the beginning of your upkeep, this creature deals 1 damage to you.
 */
val NettletoothDjinn = card("Nettletooth Djinn") {
    manaCost = "{3}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Djinn"
    oracleText = "At the beginning of your upkeep, this creature deals 1 damage to you."
    power = 4
    toughness = 4
    triggeredAbility {
        trigger = Triggers.YourUpkeep
        effect = DealDamageEffect(1, EffectTarget.PlayerRef(Player.You))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "232"
        artist = "Janine Johnston"
        flavorText = "\"The few of us who survived were denied entry to our camp for two days—so like the pox were the marks we bore.\"\n—Travelogue of Najat"
        imageUri = "https://cards.scryfall.io/normal/front/7/b/7b5aa60d-91aa-4eee-9d13-55a357c8eced.jpg"
    }
}
