// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Sea Scryer
 * {1}{U}
 * Creature — Merfolk Wizard
 * 1/1
 * {T}: Add {C}.
 * {1}, {T}: Add {U}.
 */
val SeaScryer = card("Sea Scryer") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Merfolk Wizard"
    oracleText = "{T}: Add {C}.\n{1}, {T}: Add {U}."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddColorlessMana(1)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}"), Costs.Tap)
        effect = Effects.AddMana(Color.BLUE)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "90"
        artist = "Martin McKenna"
        imageUri = "https://cards.scryfall.io/normal/front/1/2/124308ac-1bf6-4a79-8aaa-f3be8eeb3e78.jpg"
    }
}
