// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ActivationRestriction
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Sewer Rats
 * {B}
 * Creature — Rat
 * 1/1
 * {B}, Pay 1 life: This creature gets +1/+0 until end of turn. Activate no more than three times each turn.
 */
val SewerRats = card("Sewer Rats") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Creature — Rat"
    oracleText = "{B}, Pay 1 life: This creature gets +1/+0 until end of turn. Activate no more than three times each turn."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{B}"), Costs.PayLife(1))
        restrictions = listOf(ActivationRestriction.MaxPerTurn(3))
        effect = Effects.ModifyStats(1, 0, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "139"
        artist = "Martin McKenna"
        flavorText = "You lie down with rats, and the rats run away.\n—Suq'Ata insult"
        imageUri = "https://cards.scryfall.io/normal/front/4/2/42fe08c3-5024-486c-ba03-19d371ceccb0.jpg"
    }
}
