// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Shaper Guildmage
 * {U}
 * Creature — Human Wizard
 * 1/1
 * {W}, {T}: Target creature gains first strike until end of turn.
 * {B}, {T}: Target creature gets +1/+0 until end of turn.
 */
val ShaperGuildmage = card("Shaper Guildmage") {
    manaCost = "{U}"
    colorIdentity = "WUB"
    typeLine = "Creature — Human Wizard"
    oracleText = "{W}, {T}: Target creature gains first strike until end of turn.\n{B}, {T}: Target creature gets +1/+0 until end of turn."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{W}"), Costs.Tap)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.GrantKeyword(Keyword.FIRST_STRIKE, t)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{B}"), Costs.Tap)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(1, 0, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "91"
        artist = "D. Alexander Gregory"
        flavorText = "Shape this world in Zhalfir's image.\n—Shaper Guild maxim"
        imageUri = "https://cards.scryfall.io/normal/front/4/a/4a9304e1-f403-404d-9fe9-169da75e0d62.jpg"
    }
}
