// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Sidar Jabari
 * {3}{W}
 * Legendary Creature — Human Knight
 * 2/2
 * Flanking (Whenever a creature without flanking blocks this creature, the blocking creature gets -1/-1 until end of turn.)
 * Whenever Sidar Jabari attacks, tap target creature defending player controls.
 */
val SidarJabari = card("Sidar Jabari") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Legendary Creature — Human Knight"
    oracleText = "Flanking (Whenever a creature without flanking blocks this creature, the blocking creature gets -1/-1 until end of turn.)\nWhenever Sidar Jabari attacks, tap target creature defending player controls."
    power = 2
    toughness = 2
    keywords(Keyword.FLANKING)
    triggeredAbility {
        trigger = Triggers.Attacks
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Tap(t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "39"
        artist = "Gerry Grace"
        flavorText = "\"Prophecy is whatever one makes of it, but destiny cannot be changed.\"\n—Sidar Jabari"
        imageUri = "https://cards.scryfall.io/normal/front/7/4/743f0d06-cd14-49f3-ad3c-0d419a0c30bc.jpg"
    }
}
