// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CantBeBlockedByMoreThan


/**
 * Stalking Tiger
 * {3}{G}
 * Creature — Cat
 * 3/3
 * This creature can't be blocked by more than one creature.
 */
val StalkingTiger = card("Stalking Tiger") {
    manaCost = "{3}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Cat"
    power = 3
    toughness = 3
    staticAbility {
        ability = CantBeBlockedByMoreThan(maxBlockers = 1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "243"
        artist = "Terese Nielsen"
        flavorText = "In the Jamuraan jungles, there is often no separating beauty from danger."
        imageUri = "https://cards.scryfall.io/normal/front/f/1/f12cc4e9-010a-4ff7-a026-dcb6113a36fb.jpg"
    }
}
