// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Tranquil Domain
 * {1}{G}
 * Instant
 * Destroy all non-Aura enchantments.
 */
val TranquilDomain = card("Tranquil Domain") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Destroy all non-Aura enchantments."
    spell {
        effect = Effects.DestroyAll(GameObjectFilter.Enchantment.notSubtype(Subtype.AURA))
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "245"
        artist = "D. Alexander Gregory"
        flavorText = "\"An ancient court mage unified the houses into guilds to serve Zhalfir above their own interests. Even during the civil war, the guilds stood together, a testament to the wisdom of Teferi.\"\n—Afari, Tales"
        imageUri = "https://cards.scryfall.io/normal/front/8/0/801f34a6-9f22-43c2-b1e5-194395cc7da1.jpg"
    }
}
