// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Volcanic Dragon
 * {4}{R}{R}
 * Creature — Dragon
 * 4/4
 * Flying, haste
 */
val VolcanicDragon = card("Volcanic Dragon") {
    manaCost = "{4}{R}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Dragon"
    power = 4
    toughness = 4
    keywords(Keyword.FLYING, Keyword.HASTE)
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "201"
        artist = "Janine Johnston"
        flavorText = "Speed and fire are always a deadly combination."
        imageUri = "https://cards.scryfall.io/normal/front/b/d/bda123a7-d121-483a-8ff0-a541ccdbc7ca.jpg"
    }
}
