// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Wave Elemental
 * {2}{U}{U}
 * Creature — Elemental
 * 2/3
 * {U}, {T}, Sacrifice this creature: Tap up to three target creatures without flying.
 */
val WaveElemental = card("Wave Elemental") {
    manaCost = "{2}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Elemental"
    oracleText = "{U}, {T}, Sacrifice this creature: Tap up to three target creatures without flying."
    power = 2
    toughness = 3
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{U}"), Costs.Tap, Costs.SacrificeSelf)
        val t = target(
            "target",
            TargetCreature(optional = true, count = 3, filter = TargetFilter.Creature.withoutKeyword(Keyword.FLYING))
        )
        effect = Effects.TapEachTarget()
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "102"
        artist = "Zak Plucinski"
        flavorText = "\"Consider the wave: how weak the mother yet how strong the child.\"\n—Tywanna, Shaper Guildmage"
        imageUri = "https://cards.scryfall.io/normal/front/1/1/111ee762-72cb-43e3-88a1-6f1f0b9ee66e.jpg"
    }
}
