// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.IfYouDoEffect
import com.wingedsheep.sdk.scripting.effects.MayEffect


/**
 * Boundary Lands Ranger
 * {1}{R}
 * Creature — Human Ranger
 * 2/2
 * At the beginning of combat on your turn, if you control a creature with power 4 or greater, you may discard a card. If you do, draw a card.
 */
val BoundaryLandsRanger = card("Boundary Lands Ranger") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Human Ranger"
    oracleText = "At the beginning of combat on your turn, if you control a creature with power 4 or greater, you may discard a card. If you do, draw a card."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.BeginCombat
        interveningIf = Conditions.YouControl(GameObjectFilter.Creature.powerAtLeast(4))
        effect = MayEffect(effect = IfYouDoEffect(action = Patterns.Hand.discardCards(1), ifYouDo = DrawCardsEffect(1)))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "123"
        artist = "Pascal Quidault"
        flavorText = "\"You only find out who was hunting who when one of you is dead.\""
        imageUri = "https://cards.scryfall.io/normal/front/c/c/ccdcbb1d-702e-4832-8eed-7ed3deffefe3.jpg"
    }
}
