// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Candy Trail
 * {1}
 * Artifact — Food Clue
 * When this artifact enters, scry 2.
 * {2}, {T}, Sacrifice this artifact: You gain 3 life and draw a card.
 */
val CandyTrail = card("Candy Trail") {
    manaCost = "{1}"
    colorIdentity = ""
    typeLine = "Artifact — Food Clue"
    oracleText = "When this artifact enters, scry 2.\n{2}, {T}, Sacrifice this artifact: You gain 3 life and draw a card."
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Patterns.Library.scry(2)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.Tap, Costs.SacrificeSelf)
        effect = Effects.Composite(
            GainLifeEffect(3),
            DrawCardsEffect(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "243"
        artist = "Alix Branwyn"
        flavorText = "\"Look! Another one! Who cares what Mother said? We'll be home before she gets back.\"\n—Daniela, Edgewall youth"
        imageUri = "https://cards.scryfall.io/normal/front/1/a/1a860925-d912-49e5-9ddc-41ab26916bb3.jpg"
    }
}
