// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Freeze in Place
 * {1}{U}
 * Sorcery
 * Tap target creature an opponent controls and put three stun counters on it. Scry 2. (If a permanent with a stun counter would become untapped, remove one from it instead.)
 */
val FreezeInPlace = card("Freeze in Place") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Tap target creature an opponent controls and put three stun counters on it. Scry 2. (If a permanent with a stun counter would become untapped, remove one from it instead.)"
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.opponentControls()))
        effect = Effects.Composite(
            Effects.Tap(t),
            AddCountersEffect(counterType = Counters.STUN, count = 3, target = t),
            Patterns.Library.scry(2)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "50"
        artist = "Leanna Crossan"
        flavorText = "\"I'm getting the sense we shouldn't expect a warm welcome.\"\n—Kellan"
        imageUri = "https://cards.scryfall.io/normal/front/1/a/1a8bb9c7-2c4b-48a1-806e-742addb72b4b.jpg"
    }
}
