// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Moment of Valor
 * {2}{W}
 * Instant
 * Choose one —
 * • Untap target creature. It gets +1/+0 and gains indestructible until end of turn.
 * • Destroy target creature with power 4 or greater.
 */
val MomentOfValor = card("Moment of Valor") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Choose one —\n• Untap target creature. It gets +1/+0 and gains indestructible until end of turn.\n• Destroy target creature with power 4 or greater."
    spell {
        modal(chooseCount = 1) {
            mode("Untap target creature. It gets +1/+0 and gains indestructible until end of turn") {
                val t = target("target", TargetCreature(filter = TargetFilter.Creature))
                effect = Effects.Composite(
                    Effects.Untap(t),
                    Effects.ModifyStats(1, 0, t),
                    Effects.GrantKeyword(Keyword.INDESTRUCTIBLE, t)
                )
            }
            mode("Destroy target creature with power 4 or greater") {
                val t = target("target", TargetCreature(filter = TargetFilter.Creature.powerAtLeast(4)))
                effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
            }
        }
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "20"
        artist = "Joshua Cairos"
        flavorText = "Hardened by the Phyrexian invasion, Will's knights starved the nightmares of the thing they craved most: fear."
        imageUri = "https://cards.scryfall.io/normal/front/6/f/6f257fd6-24a4-4cc1-89e0-99cf5d821e3a.jpg"
    }
}
