// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Redcap Thief
 * {2}{R}
 * Creature — Goblin Rogue
 * 2/3
 * When this creature enters, create a Treasure token. (It's an artifact with "{T}, Sacrifice this token: Add one mana of any color.")
 */
val RedcapThief = card("Redcap Thief") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Goblin Rogue"
    oracleText = "When this creature enters, create a Treasure token. (It's an artifact with \"{T}, Sacrifice this token: Add one mana of any color.\")"
    power = 2
    toughness = 3
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.CreateTreasure()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "147"
        artist = "Vincent Christiaens"
        flavorText = "\"Shiny is best. Then sharp. Sharp is good. Anything else is basically trash.\""
        imageUri = "https://cards.scryfall.io/normal/front/c/d/cda6bdeb-a0d6-46ca-ba8c-317ee0096416.jpg"
    }
}
