// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.ConditionalEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Taken by Nightmares
 * {2}{B}{B}
 * Instant
 * Exile target creature. If you control an enchantment, scry 2.
 */
val TakenByNightmares = card("Taken by Nightmares") {
    manaCost = "{2}{B}{B}"
    colorIdentity = "B"
    typeLine = "Instant"
    oracleText = "Exile target creature. If you control an enchantment, scry 2."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.Composite(
            Effects.Exile(t),
            ConditionalEffect(
                condition = Conditions.YouControl(GameObjectFilter.Enchantment),
                effect = Patterns.Library.scry(2)
            )
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "112"
        artist = "Artur Treffner"
        flavorText = "Dying in your sleep is never peaceful when Ashiok is involved."
        imageUri = "https://cards.scryfall.io/normal/front/f/8/f858d83d-a13e-4ffa-a91d-d695e5e5d71a.jpg"
    }
}
