// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.effects.WardCost
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Toadstool Admirer
 * {G}
 * Creature — Ouphe
 * 1/1
 * Ward {2} (Whenever this creature becomes the target of a spell or ability an opponent controls, counter it unless that player pays {2}.)
 * {3}{G}: Put a +1/+1 counter on this creature.
 */
val ToadstoolAdmirer = card("Toadstool Admirer") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Creature — Ouphe"
    oracleText = "Ward {2} (Whenever this creature becomes the target of a spell or ability an opponent controls, counter it unless that player pays {2}.)\n{3}{G}: Put a +1/+1 counter on this creature."
    power = 1
    toughness = 1
    keywordAbility(KeywordAbility.Ward(WardCost.Mana("{2}")))
    activatedAbility {
        cost = Costs.Mana("{3}{G}")
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "192"
        artist = "Julia Metzger"
        flavorText = "Where an ouphe makes its home, the land blooms with color and joy."
        imageUri = "https://cards.scryfall.io/normal/front/f/0/f0a6349a-beff-4abd-b005-86d27c1e2957.jpg"
    }
}
