// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Unruly Catapult
 * {2}{R}
 * Artifact Creature — Construct
 * 0/4
 * Defender
 * {T}: This creature deals 1 damage to each opponent.
 * Whenever you cast an instant or sorcery spell, untap this creature.
 */
val UnrulyCatapult = card("Unruly Catapult") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Artifact Creature — Construct"
    oracleText = "Defender\n{T}: This creature deals 1 damage to each opponent.\nWhenever you cast an instant or sorcery spell, untap this creature."
    power = 0
    toughness = 4
    keywords(Keyword.DEFENDER)
    activatedAbility {
        cost = Costs.Tap
        effect = DealDamageEffect(1, EffectTarget.PlayerRef(Player.EachOpponent))
    }
    triggeredAbility {
        trigger = Triggers.YouCastInstantOrSorcery
        effect = Effects.Untap(EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "156"
        artist = "Vincent Christiaens"
        flavorText = "An autonomous, self-loading catapult had seemed like such a good idea."
        imageUri = "https://cards.scryfall.io/normal/front/3/d/3dc275f8-f060-4c15-9b8f-63cf3857eaa7.jpg"
    }
}
