// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersWithCounters


/**
 * Festerhide Boar
 * {3}{G}
 * Creature — Boar
 * 3/3
 * Trample
 * Morbid — This creature enters with two +1/+1 counters on it if a creature died this turn.
 */
val FesterhideBoar = card("Festerhide Boar") {
    manaCost = "{3}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Boar"
    oracleText = "Trample\nMorbid — This creature enters with two +1/+1 counters on it if a creature died this turn."
    power = 3
    toughness = 3
    keywords(Keyword.TRAMPLE)
    replacementEffect(EntersWithCounters(count = 2, selfOnly = true, condition = Conditions.CreatureDiedThisTurn))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "179"
        artist = "Nils Hamm"
        flavorText = "\"Bury your dead deep. The boars are hungriest while the corpse is still warm.\"\n—Paulin, trapper of Somberwald"
        imageUri = "https://cards.scryfall.io/normal/front/3/1/31740fe9-27d2-416e-93de-509ac1a7b7cd.jpg"
    }
}
