// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tmp.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Winds of Rath
 * {3}{W}{W}
 * Sorcery
 * Destroy all creatures that aren't enchanted. They can't be regenerated.
 */
val WindsOfRath = card("Winds of Rath") {
    manaCost = "{3}{W}{W}"
    colorIdentity = "W"
    typeLine = "Sorcery"
    oracleText = "Destroy all creatures that aren't enchanted. They can't be regenerated."
    spell {
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature),
            Effects.Move(EffectTarget.Self, Zone.GRAVEYARD, byDestruction = true),
            noRegenerate = true
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "52"
        artist = "Drew Tucker"
        flavorText = "\"There shall be a vast shout and then a vaster silence.\"\n—Oracle en-Vec"
        imageUri = "https://cards.scryfall.io/normal/front/a/6/a6d731b2-0113-4fd5-8b78-1aa1064bb4f5.jpg"
    }
}
