// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mkm.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Haazda Vigilante
 * {4}{W}
 * Creature — Giant Soldier
 * 4/4
 * Whenever this creature enters or attacks, put a +1/+1 counter on target creature you control with power 2 or less.
 */
val HaazdaVigilante = card("Haazda Vigilante") {
    manaCost = "{4}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Giant Soldier"
    oracleText = "Whenever this creature enters or attacks, put a +1/+1 counter on target creature you control with power 2 or less."
    power = 4
    toughness = 4
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.powerAtMost(2).youControl()))
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = t)
    }
    triggeredAbility {
        trigger = Triggers.Attacks
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.powerAtMost(2).youControl()))
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "18"
        artist = "Tomas Duchek"
        flavorText = "\"Call the Boros if you want. While they figure out if they have enough people to send a patrol, I'll be out clobbering the lowlifes who robbed you.\""
        imageUri = "https://cards.scryfall.io/normal/front/5/2/5277fe72-dc33-4d19-a439-63b5344c6034.jpg"
    }
}
