// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mkm.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Makeshift Binding
 * {2}{W}
 * Enchantment
 * When this enchantment enters, exile target creature an opponent controls until this enchantment leaves the battlefield. You gain 2 life.
 */
val MakeshiftBinding = card("Makeshift Binding") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment"
    oracleText = "When this enchantment enters, exile target creature an opponent controls until this enchantment leaves the battlefield. You gain 2 life."
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.opponentControls()))
        effect = Effects.Composite(
            Effects.ExileUntilLeaves(t),
            GainLifeEffect(2)
        )
    }
    triggeredAbility {
        trigger = Triggers.LeavesBattlefield
        effect = Effects.ReturnLinkedExileUnderOwnersControl()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "23"
        artist = "Matt Stewart"
        flavorText = "Kaya clung to the cords of the barrier ward with all her might, trapping the thrashing dryad like a fly in a spider's web."
        imageUri = "https://cards.scryfall.io/normal/front/e/4/e45d2e0c-d70d-40e5-8c3d-db6803393516.jpg"
    }
}
