// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mkm.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Marketwatch Phantom
 * {1}{W}
 * Creature — Spirit Detective
 * 2/2
 * Whenever another creature you control with power 2 or less enters, this creature gains flying until end of turn.
 */
val MarketwatchPhantom = card("Marketwatch Phantom") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Spirit Detective"
    oracleText = "Whenever another creature you control with power 2 or less enters, this creature gains flying until end of turn."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.entersBattlefield(
            filter = GameObjectFilter.Creature.powerAtMost(2).youControl(),
            binding = TriggerBinding.OTHER
        )
        effect = Effects.GrantKeyword(Keyword.FLYING, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "24"
        artist = "Bram Sels"
        flavorText = "\"It's amazing how efficient a detective you can be when you're not slowed down by things like self-preservation or walls.\""
        imageUri = "https://cards.scryfall.io/normal/front/d/a/daf6a392-3fc4-45d1-b85d-3b1381b3ab7d.jpg"
    }
}
