// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mkm.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Pick Your Poison
 * {G}
 * Sorcery
 * Choose one —
 * • Each opponent sacrifices an artifact of their choice.
 * • Each opponent sacrifices an enchantment of their choice.
 * • Each opponent sacrifices a creature with flying of their choice.
 */
val PickYourPoison = card("Pick Your Poison") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "Choose one —\n• Each opponent sacrifices an artifact of their choice.\n• Each opponent sacrifices an enchantment of their choice.\n• Each opponent sacrifices a creature with flying of their choice."
    spell {
        modal(chooseCount = 1) {
            mode("Each opponent sacrifices an artifact of their choice") {
                effect = Effects.Sacrifice(
                    filter = GameObjectFilter.Artifact,
                    target = EffectTarget.PlayerRef(Player.EachOpponent)
                )
            }
            mode("Each opponent sacrifices an enchantment of their choice") {
                effect = Effects.Sacrifice(
                    filter = GameObjectFilter.Enchantment,
                    target = EffectTarget.PlayerRef(Player.EachOpponent)
                )
            }
            mode("Each opponent sacrifices a creature with flying of their choice") {
                effect = Effects.Sacrifice(
                    filter = GameObjectFilter.Creature.withKeyword(Keyword.FLYING),
                    target = EffectTarget.PlayerRef(Player.EachOpponent)
                )
            }
        }
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "170"
        artist = "Julia Metzger"
        flavorText = "A reliable, general-purpose toxin is a handy way to save on belt space."
        imageUri = "https://cards.scryfall.io/normal/front/f/5/f58cfb23-4d99-4133-bf4b-d7e7c7d17cea.jpg"
    }
}
