// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mkm.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Rubblebelt Maverick
 * {G}
 * Creature — Human Detective
 * 1/1
 * When this creature enters, surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)
 * {G}, Exile this card from your graveyard: Put a +1/+1 counter on target creature. Activate only as a sorcery.
 */
val RubblebeltMaverick = card("Rubblebelt Maverick") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Creature — Human Detective"
    oracleText = "When this creature enters, surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)\n{G}, Exile this card from your graveyard: Put a +1/+1 counter on target creature. Activate only as a sorcery."
    power = 1
    toughness = 1
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Patterns.Library.surveil(2)
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{G}"), Costs.ExileSelf)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = t)
        timing = TimingRule.SorcerySpeed
        activateFromZone = Zone.GRAVEYARD
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "174"
        artist = "Carissa Susilo"
        imageUri = "https://cards.scryfall.io/normal/front/8/1/81c7ff67-b9e1-4d2e-b1ae-da9b946da00b.jpg"
    }
}
