// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mkm.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Sanitation Automaton
 * {2}
 * Artifact Creature — Construct
 * 2/1
 * When this creature enters, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
 */
val SanitationAutomaton = card("Sanitation Automaton") {
    manaCost = "{2}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Construct"
    oracleText = "When this creature enters, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)"
    power = 2
    toughness = 1
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Patterns.Library.surveil(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "256"
        artist = "Mike Burns"
        flavorText = "\"I am once again bursting with discarded theories. Disposal imminent.\""
        imageUri = "https://cards.scryfall.io/normal/front/5/2/52608ba4-c47d-44e4-b624-dee2a3a42ae2.jpg"
    }
}
