// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mkm.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding


/**
 * Snarling Gorehound
 * {B}
 * Creature — Dog
 * 1/1
 * Menace
 * Whenever another creature you control with power 2 or less enters, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
 */
val SnarlingGorehound = card("Snarling Gorehound") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Creature — Dog"
    oracleText = "Menace\nWhenever another creature you control with power 2 or less enters, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)"
    power = 1
    toughness = 1
    keywords(Keyword.MENACE)
    triggeredAbility {
        trigger = Triggers.entersBattlefield(
            filter = GameObjectFilter.Creature.powerAtMost(2).youControl(),
            binding = TriggerBinding.OTHER
        )
        effect = Patterns.Library.surveil(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "105"
        artist = "John Tedrick"
        flavorText = "\"I'd offer your dog a treat, but I'm afraid I don't have any appendages to spare.\"\n—Alquist Proft, to Judith"
        imageUri = "https://cards.scryfall.io/normal/front/9/3/93ab3e11-8584-406f-b9ae-9e1df4396cbc.jpg"
    }
}
