// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mkm.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Wispdrinker Vampire
 * {2}{W}{B}
 * Creature — Vampire Rogue
 * 2/4
 * Flying
 * Whenever another creature you control with power 2 or less enters, each opponent loses 1 life and you gain 1 life.
 * {5}{W}{B}: Creatures you control with power 2 or less gain deathtouch and lifelink until end of turn.
 */
val WispdrinkerVampire = card("Wispdrinker Vampire") {
    manaCost = "{2}{W}{B}"
    colorIdentity = "WB"
    typeLine = "Creature — Vampire Rogue"
    oracleText = "Flying\nWhenever another creature you control with power 2 or less enters, each opponent loses 1 life and you gain 1 life.\n{5}{W}{B}: Creatures you control with power 2 or less gain deathtouch and lifelink until end of turn."
    power = 2
    toughness = 4
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.entersBattlefield(
            filter = GameObjectFilter.Creature.powerAtMost(2).youControl(),
            binding = TriggerBinding.OTHER
        )
        effect = Effects.Composite(
            Effects.LoseLife(1, EffectTarget.PlayerRef(Player.EachOpponent)),
            GainLifeEffect(1)
        )
    }
    activatedAbility {
        cost = Costs.Mana("{5}{W}{B}")
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature.powerAtMost(2).youControl()),
            Effects.Composite(
                Effects.GrantKeyword(Keyword.DEATHTOUCH, EffectTarget.Self),
                Effects.GrantKeyword(Keyword.LIFELINK, EffectTarget.Self)
            )
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "243"
        artist = "Zara Alfonso"
        imageUri = "https://cards.scryfall.io/normal/front/a/3/a3490c05-d12c-4483-acbc-1b4ae68877f0.jpg"
    }
}
