// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Coastal Drake
 * {2}{U}
 * Creature — Drake
 * 2/1
 * Flying
 * {1}{U}, {T}: Return target Kavu to its owner's hand.
 */
val CoastalDrake = card("Coastal Drake") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Drake"
    oracleText = "Flying\n{1}{U}, {T}: Return target Kavu to its owner's hand."
    power = 2
    toughness = 1
    keywords(Keyword.FLYING)
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{1}{U}"), Costs.Tap)
        val t = target("target", TargetCreature(filter = TargetFilter(GameObjectFilter.Permanent.withSubtype("Kavu"))))
        effect = Effects.Move(t, Zone.HAND)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "22"
        artist = "John Gallagher"
        flavorText = "When the kavu emerged from their ancient nests, food chains long dormant became vibrant again."
        imageUri = "https://cards.scryfall.io/normal/front/f/8/f87aaa74-26c6-4057-84b9-a007383684a5.jpg"
    }
}
