// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Flowstone Charger
 * {2}{R}{W}
 * Creature — Beast
 * 2/5
 * Whenever this creature attacks, it gets +3/-3 until end of turn.
 */
val FlowstoneCharger = card("Flowstone Charger") {
    manaCost = "{2}{R}{W}"
    colorIdentity = "WR"
    typeLine = "Creature — Beast"
    oracleText = "Whenever this creature attacks, it gets +3/-3 until end of turn."
    power = 2
    toughness = 5
    triggeredAbility {
        trigger = Triggers.Attacks
        effect = Effects.ModifyStats(3, -3, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "99"
        artist = "John Gallagher"
        flavorText = "A mane of flowstone and a mien of fury."
        imageUri = "https://cards.scryfall.io/normal/front/c/5/c57abdab-d99c-418c-818d-b06a8722d733.jpg"
    }
}
