// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter


/**
 * Goblin Trenches
 * {1}{R}{W}
 * Enchantment
 * {2}, Sacrifice a land: Create two 1/1 red and white Goblin Soldier creature tokens.
 */
val GoblinTrenches = card("Goblin Trenches") {
    manaCost = "{1}{R}{W}"
    colorIdentity = "WR"
    typeLine = "Enchantment"
    oracleText = "{2}, Sacrifice a land: Create two 1/1 red and white Goblin Soldier creature tokens."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.Sacrifice(GameObjectFilter.Land))
        effect = Effects.CreateToken(
            power = 1,
            toughness = 1,
            colors = setOf(Color.RED, Color.WHITE),
            creatureTypes = setOf("Goblin", "Soldier"),
            count = 2
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "104"
        artist = "Wayne England"
        flavorText = "The ground rose and formed into thousands of tiny warriors. This fight was far from over."
        imageUri = "https://cards.scryfall.io/normal/front/2/1/2100844c-6a41-40f5-b7f8-9b426d5a6945.jpg"
    }
}
