// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Kavu Mauler
 * {4}{G}{G}
 * Creature — Kavu
 * 4/4
 * Trample
 * Whenever this creature attacks, it gets +1/+1 until end of turn for each other attacking Kavu.
 */
val KavuMauler = card("Kavu Mauler") {
    manaCost = "{4}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Kavu"
    oracleText = "Trample\nWhenever this creature attacks, it gets +1/+1 until end of turn for each other attacking Kavu."
    power = 4
    toughness = 4
    keywords(Keyword.TRAMPLE)
    triggeredAbility {
        trigger = Triggers.Attacks
        effect = Effects.ModifyStats(
            DynamicAmount.Subtract(
                DynamicAmount.AggregateBattlefield(
                    Player.You,
                    GameObjectFilter.Creature.withSubtype("Kavu").attacking()
                ),
                DynamicAmount.Fixed(1)
            ),
            DynamicAmount.Subtract(
                DynamicAmount.AggregateBattlefield(
                    Player.You,
                    GameObjectFilter.Creature.withSubtype("Kavu").attacking()
                ),
                DynamicAmount.Fixed(1)
            ),
            EffectTarget.Self
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "80"
        artist = "Daren Bader"
        flavorText = "To the kavu, all Phyrexians are merely crunchy snacks."
        imageUri = "https://cards.scryfall.io/normal/front/7/9/79adc3af-5fa3-4cb6-9bbc-52ede0c69263.jpg"
    }
}
