// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.RegenerateEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Living Airship
 * {3}{U}
 * Creature — Metathran
 * 2/3
 * Flying
 * {2}{G}: Regenerate this creature.
 */
val LivingAirship = card("Living Airship") {
    manaCost = "{3}{U}"
    colorIdentity = "UG"
    typeLine = "Creature — Metathran"
    oracleText = "Flying\n{2}{G}: Regenerate this creature."
    power = 2
    toughness = 3
    keywords(Keyword.FLYING)
    activatedAbility {
        cost = Costs.Mana("{2}{G}")
        effect = RegenerateEffect(EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "28"
        artist = "Mark Tedin"
        flavorText = "The ship has a crew of three: the pilot, the gunner, and the ship itself."
        imageUri = "https://cards.scryfall.io/normal/front/b/0/b0441eef-392e-4af4-b189-2f1fb8bf3fca.jpg"
    }
}
