// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.targets.TargetPlayer


/**
 * Mournful Zombie
 * {2}{B}
 * Creature — Zombie
 * 2/1
 * {W}, {T}: Target player gains 1 life.
 */
val MournfulZombie = card("Mournful Zombie") {
    manaCost = "{2}{B}"
    colorIdentity = "WB"
    typeLine = "Creature — Zombie"
    oracleText = "{W}, {T}: Target player gains 1 life."
    power = 2
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{W}"), Costs.Tap)
        val t = target("target", TargetPlayer())
        effect = GainLifeEffect(1, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "43"
        artist = "John Matson"
        flavorText = "Treated with a powerful mix of herbs and potions, its wrappings have a remarkable preservative effect, even for the living."
        imageUri = "https://cards.scryfall.io/normal/front/9/b/9ba12fb1-de8c-46c6-b33f-e0580ed2a3ee.jpg"
    }
}
