// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Penumbra Kavu
 * {4}{G}
 * Creature — Kavu
 * 3/3
 * When this creature dies, create a 3/3 black Kavu creature token.
 */
val PenumbraKavu = card("Penumbra Kavu") {
    manaCost = "{4}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Kavu"
    oracleText = "When this creature dies, create a 3/3 black Kavu creature token."
    power = 3
    toughness = 3
    triggeredAbility {
        trigger = Triggers.Dies
        effect = Effects.CreateToken(
            power = 3,
            toughness = 3,
            colors = setOf(Color.BLACK),
            creatureTypes = setOf("Kavu")
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "83"
        artist = "Tony Szczudlo"
        flavorText = "\"These kavu are so stubborn they even refuse to die.\"\n—Tahngarth"
        imageUri = "https://cards.scryfall.io/normal/front/e/e/ee334211-4109-46ff-8676-856048221a1c.jpg"
    }
}
