// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Razorfin Hunter
 * {U}{R}
 * Creature — Merfolk Goblin
 * 1/1
 * {T}: This creature deals 1 damage to any target.
 */
val RazorfinHunter = card("Razorfin Hunter") {
    manaCost = "{U}{R}"
    colorIdentity = "UR"
    typeLine = "Creature — Merfolk Goblin"
    oracleText = "{T}: This creature deals 1 damage to any target."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(1, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "119"
        artist = "Jeff Easley"
        flavorText = "No one knew if they'd been lurking under the sea all along, or if they'd been created by the Phyrexian overlay."
        imageUri = "https://cards.scryfall.io/normal/front/9/9/99829552-917a-4373-9772-4255dff542d6.jpg"
    }
}
