// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Smash
 * {2}{R}
 * Instant
 * Destroy target artifact.
 * Draw a card.
 */
val Smash = card("Smash") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Destroy target artifact.\nDraw a card."
    spell {
        val t = target("target", TargetPermanent(filter = TargetFilter.Artifact))
        effect = Effects.Composite(
            Effects.Move(t, Zone.GRAVEYARD, byDestruction = true),
            DrawCardsEffect(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "69"
        artist = "Pete Venters"
        flavorText = "\"They're ugly, and they're in my way.\"\n—Tahngarth"
        imageUri = "https://cards.scryfall.io/normal/front/4/a/4a6c869c-74c2-42b6-bb23-a2f481c4b673.jpg"
    }
}
