// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Vindicate
 * {1}{W}{B}
 * Sorcery
 * Destroy target permanent.
 */
val Vindicate = card("Vindicate") {
    manaCost = "{1}{W}{B}"
    colorIdentity = "WB"
    typeLine = "Sorcery"
    oracleText = "Destroy target permanent."
    spell {
        val t = target("target", TargetPermanent())
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "126"
        artist = "Brian Snõddy"
        flavorText = "\"Don't mourn for me. This is my destiny.\"\n—Gerrard"
        imageUri = "https://cards.scryfall.io/normal/front/2/a/2a1bfefd-dae8-49e9-9d56-cc852e3dc93b.jpg"
    }
}
