// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Wild Research
 * {2}{R}
 * Enchantment
 * {1}{W}: Search your library for an enchantment card and reveal that card. Put it into your hand, then discard a card at random. Then shuffle.
 * {1}{U}: Search your library for an instant card and reveal that card. Put it into your hand, then discard a card at random. Then shuffle.
 */
val WildResearch = card("Wild Research") {
    manaCost = "{2}{R}"
    colorIdentity = "WUR"
    typeLine = "Enchantment"
    oracleText = "{1}{W}: Search your library for an enchantment card and reveal that card. Put it into your hand, then discard a card at random. Then shuffle.\n{1}{U}: Search your library for an instant card and reveal that card. Put it into your hand, then discard a card at random. Then shuffle."
    activatedAbility {
        cost = Costs.Mana("{1}{W}")
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Instant,
            destination = SearchDestination.HAND,
            reveal = true
        )
    }
    activatedAbility {
        cost = Costs.Mana("{1}{U}")
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Instant,
            destination = SearchDestination.HAND,
            reveal = true
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "72"
        artist = "Gary Ruddell"
        imageUri = "https://cards.scryfall.io/normal/front/8/f/8f00e6f1-e854-40b0-855d-7e0d7d233850.jpg"
    }
}
