// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tla.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Avatar Enthusiasts
 * {2}{W}
 * Creature — Human Peasant Ally
 * 2/2
 * Whenever another Ally you control enters, put a +1/+1 counter on this creature.
 */
val AvatarEnthusiasts = card("Avatar Enthusiasts") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Peasant Ally"
    oracleText = "Whenever another Ally you control enters, put a +1/+1 counter on this creature."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.entersBattlefield(
            filter = GameObjectFilter.Permanent.withSubtype(Subtype.ALLY).youControl(),
            binding = TriggerBinding.OTHER
        )
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "11"
        artist = "Leanna Crossan"
        flavorText = "\"There he is! There he is! The Avatar's on Kyoshi!\""
        imageUri = "https://cards.scryfall.io/normal/front/7/2/7292e5f2-d5a1-4e39-8f75-eba471819f04.jpg"
    }
}
