// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tla.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Boar-q-pine
 * {2}{R}
 * Creature — Boar Porcupine
 * 2/2
 * Whenever you cast a noncreature spell, put a +1/+1 counter on this creature.
 */
val BoarQPine = card("Boar-q-pine") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Boar Porcupine"
    oracleText = "Whenever you cast a noncreature spell, put a +1/+1 counter on this creature."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.YouCastNoncreature
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "124"
        artist = "Brandon L. Hunt"
        flavorText = "This fiercely territorial beast uses knife- sharp quills to ensure would-be attackers always get the point."
        imageUri = "https://cards.scryfall.io/normal/front/0/8/087a445c-5f63-45d6-83e8-20d22650db20.jpg"
    }
}
