// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tla.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.AnyTarget
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Cat-Gator
 * {6}{B}
 * Creature — Fish Crocodile
 * 3/2
 * Lifelink
 * When this creature enters, it deals damage equal to the number of Swamps you control to any target.
 */
val CatGator = card("Cat-Gator") {
    manaCost = "{6}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Fish Crocodile"
    oracleText = "Lifelink\nWhen this creature enters, it deals damage equal to the number of Swamps you control to any target."
    power = 3
    toughness = 2
    keywords(Keyword.LIFELINK)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(
            DynamicAmount.AggregateBattlefield(Player.You, GameObjectFilter.Land.withSubtype(Subtype.SWAMP)),
            t
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "91"
        artist = "Joseph Weston"
        flavorText = "People don't go fishing for cat-gators. Cat-gators go fishing for people."
        imageUri = "https://cards.scryfall.io/normal/front/e/c/ec83a825-79e6-42a4-919c-3bc498ff4433.jpg"
    }
}
