// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tla.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Earth Village Ruffians
 * {2}{B/G}
 * Creature — Human Soldier Rogue
 * 3/1
 * When this creature dies, earthbend 2. (Target land you control becomes a 0/0 creature with haste that's still a land. Put two +1/+1 counters on it. When it dies or is exiled, return it to the battlefield tapped.)
 */
val EarthVillageRuffians = card("Earth Village Ruffians") {
    manaCost = "{2}{B/G}"
    colorIdentity = "BG"
    typeLine = "Creature — Human Soldier Rogue"
    oracleText = "When this creature dies, earthbend 2. (Target land you control becomes a 0/0 creature with haste that's still a land. Put two +1/+1 counters on it. When it dies or is exiled, return it to the battlefield tapped.)"
    power = 3
    toughness = 1
    triggeredAbility {
        trigger = Triggers.Dies
        val t = target("target", TargetPermanent(filter = TargetFilter.Land.youControl()))
        effect = Effects.Earthbend(2, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "219"
        artist = "Dom Lay"
        flavorText = "\"The army 'appreciates' your support.\""
        imageUri = "https://cards.scryfall.io/normal/front/5/6/56d4e0b7-232f-4953-84a3-e6f17781aa45.jpg"
    }
}
