// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tla.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Geyser Leaper
 * {4}{U}
 * Creature — Human Warrior Ally
 * 4/3
 * Flying
 * Waterbend {4}: Draw a card, then discard a card. (While paying a waterbend cost, you can tap your artifacts and creatures to help. Each one pays for {1}.)
 */
val GeyserLeaper = card("Geyser Leaper") {
    manaCost = "{4}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Warrior Ally"
    oracleText = "Flying\nWaterbend {4}: Draw a card, then discard a card. (While paying a waterbend cost, you can tap your artifacts and creatures to help. Each one pays for {1}.)"
    power = 4
    toughness = 3
    keywords(Keyword.FLYING)
    activatedAbility {
        cost = Costs.Mana("{4}")
        hasWaterbend = true
        effect = Effects.Composite(
            DrawCardsEffect(1),
            Patterns.Hand.discardCards(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "52"
        artist = "Norikatsu Miyoshi"
        flavorText = "With enough water pressure, a Waterbender can briefly experience the world as an Airbender."
        imageUri = "https://cards.scryfall.io/normal/front/4/d/4d25428d-e5a5-43c4-8544-43120ed1c4d5.jpg"
    }
}
