// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tla.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Glider Kids
 * {2}{W}
 * Creature — Human Pilot Ally
 * 2/3
 * Flying
 * When this creature enters, scry 1. (Look at the top card of your library. You may put it on the bottom.)
 */
val GliderKids = card("Glider Kids") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Pilot Ally"
    oracleText = "Flying\nWhen this creature enters, scry 1. (Look at the top card of your library. You may put it on the bottom.)"
    power = 2
    toughness = 3
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Patterns.Library.scry(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "21"
        artist = "ikeda_cpt"
        flavorText = "The Fire Nation never expected the Earth Kingdom to take to the skies."
        imageUri = "https://cards.scryfall.io/normal/front/0/6/0613afb5-4cee-4132-8adf-404767ed8d07.jpg"
    }
}
