// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tla.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Pretending Poxbearers
 * {1}{W/B}
 * Creature — Human Citizen Ally
 * 2/1
 * When this creature dies, create a 1/1 white Ally creature token.
 */
val PretendingPoxbearers = card("Pretending Poxbearers") {
    manaCost = "{1}{W/B}"
    colorIdentity = "WB"
    typeLine = "Creature — Human Citizen Ally"
    oracleText = "When this creature dies, create a 1/1 white Ally creature token."
    power = 2
    toughness = 1
    triggeredAbility {
        trigger = Triggers.Dies
        effect = Effects.CreateToken(
            power = 1,
            toughness = 1,
            colors = setOf(Color.WHITE),
            creatureTypes = setOf("Ally")
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "237"
        artist = "Salvatorre Zee Yazzie"
        flavorText = "Pentapox, a deadly skin affliction bearing similarity to pentapus markings, was entirely fabricated—but the Fire Nation didn't know that."
        imageUri = "https://cards.scryfall.io/normal/front/d/1/d1af91a5-8681-4a05-910d-96f7a819bfaa.jpg"
    }
}
