// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.snc.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Inspiring Overseer
 * {2}{W}
 * Creature — Angel Cleric
 * 2/1
 * Flying
 * When this creature enters, you gain 1 life and draw a card.
 */
val InspiringOverseer = card("Inspiring Overseer") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Angel Cleric"
    oracleText = "Flying\nWhen this creature enters, you gain 1 life and draw a card."
    power = 2
    toughness = 1
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.Composite(
            GainLifeEffect(1),
            DrawCardsEffect(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "18"
        artist = "Irina Nordsol"
        flavorText = "\"This city could certainly use a bit more divine intervention.\"\n—Inspector Jillard"
        imageUri = "https://cards.scryfall.io/normal/front/3/5/35d9da1d-8678-4252-b0f8-9960795642f0.jpg"
    }
}
