// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.vis.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Prosperity
 * {X}{U}
 * Sorcery
 * Each player draws X cards.
 */
val Prosperity = card("Prosperity") {
    manaCost = "{X}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    spell {
        effect = Patterns.Hand.eachPlayerDrawsX(includeController = true, includeOpponents = true)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "40"
        artist = "Dan Frazier"
        flavorText = "\"Wealth is a good thing, compared to poverty—your food is better, your robes are softer, and your companions have bathed more recently.\"\n—Kipkemboi, Kukemssa pirate"
        imageUri = "https://cards.scryfall.io/normal/front/3/f/3fa5e806-3cf2-4241-b45d-a05d2b715efd.jpg"
    }
}
