// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.vis.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule


/**
 * Sisay's Ring
 * {4}
 * Artifact
 * {T}: Add {C}{C}.
 */
val SisaysRing = card("Sisay's Ring") {
    manaCost = "{4}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{T}: Add {C}{C}."
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddColorlessMana(2)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "154"
        artist = "Donato Giancola"
        flavorText = "\"With this ring, you have friends in worlds you've never heard of.\"\n—Sisay, Captain of the Weatherlight"
        imageUri = "https://cards.scryfall.io/normal/front/a/0/a08becd3-ca5e-4150-8d28-52436a3eaffd.jpg"
    }
}
