// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fin.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.predicates.CardPredicate
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Ashe, Princess of Dalmasca
 * {2}{W}
 * Legendary Creature — Human Rebel Noble
 * 3/2
 * Whenever Ashe attacks, look at the top five cards of your library. You may reveal an artifact card from among them and put it into your hand. Put the rest on the bottom of your library in a random order.
 */
val AshePrincessOfDalmasca = card("Ashe, Princess of Dalmasca") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Legendary Creature — Human Rebel Noble"
    oracleText = "Whenever Ashe attacks, look at the top five cards of your library. You may reveal an artifact card from among them and put it into your hand. Put the rest on the bottom of your library in a random order."
    power = 3
    toughness = 2
    triggeredAbility {
        trigger = Triggers.Attacks
        effect = Patterns.Library.lookAtTopRevealMatchingToHand(
            count = DynamicAmount.Fixed(5),
            filter = GameObjectFilter(cardPredicates = listOf(CardPredicate.IsArtifact)),
            prompt = "You may reveal an artifact card from among them and put it into your hand"
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "7"
        artist = "Yumi Yaoshida"
        flavorText = "\"I am simply myself. No more and no less. And I want only to be free.\""
        imageUri = "https://cards.scryfall.io/normal/front/f/f/ffe0596f-ef99-4862-9386-0fe455259995.jpg"
    }
}
