package com.wingedsheep.mtg.sets.definitions.fin.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ActivatedAbility
import com.wingedsheep.sdk.scripting.AdditionalManaOnSourceTap
import com.wingedsheep.sdk.scripting.Durations
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TappedForManaType
import com.wingedsheep.sdk.scripting.effects.BecomeArtifactEffect

/**
 * Ultima, Origin of Oblivion
 * {5}
 * Legendary Creature — God
 * 4/4
 *
 * Flying
 * Whenever Ultima attacks, put a blight counter on target land. For as long as that land has a
 * blight counter on it, it loses all land types and abilities and has "{T}: Add {C}."
 * Whenever you tap a land for {C}, add an additional {C}.
 *
 * Modeling notes:
 *
 *  - The attack trigger puts a blight counter on target land and then establishes a *continuous*
 *    transform on that land. "For as long as that land has a blight counter on it" is a CR 611.2b
 *    one-shot continuous effect generated by the resolving ability — it exists independently of
 *    Ultima and ends only when the blight counter leaves the land (NOT when Ultima leaves the
 *    battlefield). That independence is why the transform is a floating [BecomeArtifactEffect] with
 *    [Durations.whileAffectedHasCounter] rather than a counter-filtered static ability on Ultima
 *    (which would incorrectly revert every blighted land the instant Ultima died).
 *
 *  - "loses all land types and abilities" strips the land's *subtypes* (`subtypes = emptySet()`)
 *    and abilities (`loseAllAbilities = true`) but leaves its card types unchanged
 *    (`cardTypes = null`) and its color unchanged (`colors = null`) — per the ruling "The affected
 *    land keeps any other card types (such as artifact) and supertypes (such as basic or legendary)
 *    when it loses its land types." The granted "{T}: Add {C}" survives the lose-all-abilities wipe
 *    via the durable granted-activated-ability record, exactly like Imprisoned in the Moon.
 *
 *  - The last ability is a triggered mana ability (per ruling: "It doesn't use the stack and can't
 *    be responded to."). Modeled as [AdditionalManaOnSourceTap] over lands you control, gated to
 *    colorless taps ([TappedForManaType.COLORLESS]) so only a tap that produced {C} fires it — a
 *    Forest tapped for {G} does not. The mirror form (`color = null`) then adds the extra {C}. This
 *    is the payoff for the attack ability, whose blighted lands all tap for {C}.
 */
val UltimaOriginOfOblivion = card("Ultima, Origin of Oblivion") {
    manaCost = "{5}"
    colorIdentity = ""
    typeLine = "Legendary Creature — God"
    oracleText = "Flying\n" +
        "Whenever Ultima attacks, put a blight counter on target land. For as long as that land " +
        "has a blight counter on it, it loses all land types and abilities and has \"{T}: Add {C}.\"\n" +
        "Whenever you tap a land for {C}, add an additional {C}."
    power = 4
    toughness = 4

    keywords(Keyword.FLYING)

    // Whenever Ultima attacks, put a blight counter on target land, then transform that land for
    // as long as the counter remains on it.
    triggeredAbility {
        trigger = Triggers.Attacks
        val land = target("target land", Targets.Land)
        effect = Effects.Composite(
            Effects.AddCounters(Counters.BLIGHT, 1, land),
            BecomeArtifactEffect(
                target = land,
                cardTypes = null,       // keep the land's card types (stays a land; keeps e.g. artifact)
                subtypes = emptySet(),  // "loses all land types" (subtypes)
                colors = null,          // no color change
                loseAllAbilities = true,
                grantedAbility = ActivatedAbility(
                    cost = Costs.Tap,
                    effect = Effects.AddColorlessMana(1),
                    isManaAbility = true,
                    descriptionOverride = "{T}: Add {C}."
                ),
                duration = Durations.whileAffectedHasCounter(Counters.BLIGHT)
            )
        )
        description = "Whenever Ultima attacks, put a blight counter on target land. For as long " +
            "as that land has a blight counter on it, it loses all land types and abilities and " +
            "has \"{T}: Add {C}.\""
    }

    // Whenever you tap a land for {C}, add an additional {C}. (Triggered mana ability — off-stack.)
    staticAbility {
        ability = AdditionalManaOnSourceTap(
            sourceFilter = GameObjectFilter.Land.youControl(),
            color = null,
            whenProducing = TappedForManaType.COLORLESS
        )
    }

    metadata {
        rarity = Rarity.RARE
        collectorNumber = "2"
        artist = "Russell Lu"
        imageUri = "https://cards.scryfall.io/normal/front/d/5/d55a4c02-1aa4-454c-9041-84937377a53b.jpg?1782686600"

        ruling(
            "2025-06-06",
            "The affected land keeps any other card types (such as artifact) and supertypes (such " +
                "as basic or legendary) when it loses its land types."
        )
        ruling(
            "2025-06-06",
            "Ultima's last ability is a triggered mana ability. It doesn't use the stack and can't " +
                "be responded to."
        )
    }
}
