// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.stx.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Burrog Befuddler
 * {1}{U}
 * Creature — Frog Wizard
 * 2/1
 * Flash (You may cast this spell any time you could cast an instant.)
 * When this creature enters, target creature an opponent controls gets -1/-0 until end of turn.
 */
val BurrogBefuddler = card("Burrog Befuddler") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Frog Wizard"
    oracleText = "Flash (You may cast this spell any time you could cast an instant.)\nWhen this creature enters, target creature an opponent controls gets -1/-0 until end of turn."
    power = 2
    toughness = 1
    keywords(Keyword.FLASH)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.opponentControls()))
        effect = Effects.ModifyStats(-1, 0, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "38"
        artist = "Zoltan Boros"
        flavorText = "Students who seek river herbs in Doradur quickly find themselves slightly damp and thoroughly surrounded."
        imageUri = "https://cards.scryfall.io/normal/front/6/0/6040c573-cd8c-4593-8ade-d9922482035c.jpg"
    }
}
