// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.stx.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Campus Guide
 * {2}
 * Artifact Creature — Golem
 * 2/1
 * When this creature enters, you may search your library for a basic land card, reveal it, then shuffle and put that card on top.
 */
val CampusGuide = card("Campus Guide") {
    manaCost = "{2}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Golem"
    oracleText = "When this creature enters, you may search your library for a basic land card, reveal it, then shuffle and put that card on top."
    power = 2
    toughness = 1
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        optional = true
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.BasicLand,
            destination = SearchDestination.TOP_OF_LIBRARY,
            reveal = true
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "252"
        artist = "Slawomir Maniak"
        flavorText = "\"There's nowhere in Strixhaven I can't find. Where do you need to go?\""
        imageUri = "https://cards.scryfall.io/normal/front/8/7/87a9a8a2-de81-441b-b501-418311b677f7.jpg"
    }
}
