// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.stx.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Teach by Example
 * {U/R}{U/R}
 * Instant
 * ({U/R} can be paid with either {U} or {R}.)
 * When you next cast an instant or sorcery spell this turn, copy that spell. You may choose new targets for the copy.
 */
val TeachByExample = card("Teach by Example") {
    manaCost = "{U/R}{U/R}"
    colorIdentity = "UR"
    typeLine = "Instant"
    oracleText = "({U/R} can be paid with either {U} or {R}.)\nWhen you next cast an instant or sorcery spell this turn, copy that spell. You may choose new targets for the copy."
    spell {
        effect = Effects.CopyNextSpellCast(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "241"
        artist = "Johan Grenier"
        flavorText = "\"Learning to imitate a master is the first step in becoming one.\"\n—Uvilda, Prismari dean"
        imageUri = "https://cards.scryfall.io/normal/front/a/a/aa7fbb9b-50a8-4d18-a667-fe965468ca16.jpg"
    }
}
