// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.m11.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Ajani's Pridemate
 * {1}{W}
 * Creature — Cat Soldier
 * 2/2
 * Whenever you gain life, put a +1/+1 counter on this creature.
 */
val AjanisPridemate = card("Ajani's Pridemate") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Cat Soldier"
    oracleText = "Whenever you gain life, put a +1/+1 counter on this creature."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.YouGainLife
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "3"
        artist = "Svetlin Velinov"
        flavorText = "\"When one of us prospers, the pride prospers.\"\n—Jazal Goldmane"
        imageUri = "https://cards.scryfall.io/normal/front/f/7/f70d1452-6b61-4c63-841f-4256ac498e9f.jpg"
    }
}
