package com.wingedsheep.mtg.sets.definitions.war.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget

/**
 * Spellgorger Weird
 * {2}{R}
 * Creature — Weird
 * 2/2
 * Whenever you cast a noncreature spell, put a +1/+1 counter on Spellgorger Weird.
 *
 * Initial draft auto-generated by `:mtgish-tooling` (the new `WhenAPlayerCastsASpell` ->
 * `Triggers.YouCastNoncreature` emitter path), then verified against Scryfall and given a
 * scenario test.
 */
val SpellgorgerWeird = card("Spellgorger Weird") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Weird"
    oracleText = "Whenever you cast a noncreature spell, put a +1/+1 counter on this creature."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.YouCastNoncreature
        effect = Effects.AddCounters(Counters.PLUS_ONE_PLUS_ONE, 1, EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "145"
        artist = "James Paick"
        flavorText = "Freed from their respective labs, the two weirds formed a partnership, feeding on the arcane energies of war."
        imageUri = "https://cards.scryfall.io/normal/front/9/1/91551f85-4630-43a0-af72-8332d2ff0752.jpg?1557576817"
    }
}
