// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ModifyStats


/**
 * Bonesplitter
 * {1}
 * Artifact — Equipment
 * Equipped creature gets +2/+0.
 * Equip {1}
 */
val Bonesplitter = card("Bonesplitter") {
    manaCost = "{1}"
    colorIdentity = ""
    typeLine = "Artifact — Equipment"
    oracleText = "Equipped creature gets +2/+0.\nEquip {1}"
    staticAbility {
        ability = ModifyStats(2, 0)
    }
    equipAbility("{1}")
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "146"
        artist = "Darrell Riche"
        imageUri = "https://cards.scryfall.io/normal/front/4/6/465a7990-c9f9-4716-a833-fd41458b9cee.jpg"
    }
}
