// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.ModifyStats


/**
 * Leonin Scimitar
 * {1}
 * Artifact — Equipment
 * Equipped creature gets +1/+1.
 * Equip {1} ({1}: Attach to target creature you control. Equip only as a sorcery.)
 */
val LeoninScimitar = card("Leonin Scimitar") {
    manaCost = "{1}"
    colorIdentity = ""
    typeLine = "Artifact — Equipment"
    oracleText = "Equipped creature gets +1/+1.\nEquip {1} ({1}: Attach to target creature you control. Equip only as a sorcery.)"
    staticAbility {
        ability = ModifyStats(1, 1)
    }
    equipAbility("{1}")
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "193"
        artist = "Doug Chaffee"
        imageUri = "https://cards.scryfall.io/normal/front/8/a/8abf4bbe-5b1c-4f6f-be32-5f61c66e1830.jpg"
    }
}
