// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.m12.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Rune-Scarred Demon
 * {5}{B}{B}
 * Creature — Demon
 * 6/6
 * Flying
 * When this creature enters, search your library for a card, put it into your hand, then shuffle.
 */
val RuneScarredDemon = card("Rune-Scarred Demon") {
    manaCost = "{5}{B}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Demon"
    oracleText = "Flying\nWhen this creature enters, search your library for a card, put it into your hand, then shuffle."
    power = 6
    toughness = 6
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Patterns.Library.searchLibrary(filter = GameObjectFilter.Any, destination = SearchDestination.HAND)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "106"
        artist = "Michael Komarck"
        flavorText = "The litany of the infernal on his flesh pulses to the beating of his dark heart."
        imageUri = "https://cards.scryfall.io/normal/front/5/0/509e0f81-0591-4b28-978e-a2f1c46b7427.jpg"
    }
}
