// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.m12.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Stingerfling Spider
 * {4}{G}
 * Creature — Spider
 * 2/5
 * Reach
 * When this creature enters, you may destroy target creature with flying.
 */
val StingerflingSpider = card("Stingerfling Spider") {
    manaCost = "{4}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Spider"
    oracleText = "Reach\nWhen this creature enters, you may destroy target creature with flying."
    power = 2
    toughness = 5
    keywords(Keyword.REACH)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        optional = true
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.withKeyword(Keyword.FLYING)))
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "197"
        artist = "Dave Allsop"
        flavorText = "The juiciest prey is that which grows lazy, thinking itself beyond the reach of danger."
        imageUri = "https://cards.scryfall.io/normal/front/3/b/3b781626-f4ce-4d00-aa7c-0e07f58f688f.jpg"
    }
}
