// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ptk.cards

import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Strategic Planning
 * {1}{U}
 * Sorcery
 * Look at the top three cards of your library. Put one of them into your hand and the rest into your graveyard.
 */
val StrategicPlanning = card("Strategic Planning") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Look at the top three cards of your library. Put one of them into your hand and the rest into your graveyard."
    spell {
        effect = Patterns.Library.lookAtTopAndKeep(count = 3, keepCount = 1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "53"
        artist = "Zhang Jiazhen"
        flavorText = "\"Plans evolved within the tent decide a victory 1,000 li away.\""
        imageUri = "https://cards.scryfall.io/normal/front/7/7/7727e7b5-39a3-46ba-935b-ee093c694c38.jpg"
    }
}
