// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.c14.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Jazal Goldmane
 * {2}{W}{W}
 * Legendary Creature — Cat Warrior
 * 4/4
 * First strike (This creature deals combat damage before creatures without first strike.)
 * {3}{W}{W}: Attacking creatures you control get +X/+X until end of turn, where X is the number of attacking creatures.
 */
val JazalGoldmane = card("Jazal Goldmane") {
    manaCost = "{2}{W}{W}"
    colorIdentity = "W"
    typeLine = "Legendary Creature — Cat Warrior"
    oracleText = "First strike (This creature deals combat damage before creatures without first strike.)\n{3}{W}{W}: Attacking creatures you control get +X/+X until end of turn, where X is the number of attacking creatures."
    power = 4
    toughness = 4
    keywords(Keyword.FIRST_STRIKE)
    activatedAbility {
        cost = Costs.Mana("{3}{W}{W}")
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Creature.attacking().youControl()),
            Effects.ModifyStats(
                DynamicAmount.AggregateBattlefield(Player.Each, GameObjectFilter.Creature.attacking()),
                DynamicAmount.AggregateBattlefield(Player.Each, GameObjectFilter.Creature.attacking()),
                EffectTarget.Self
            )
        )
    }
    metadata {
        rarity = Rarity.MYTHIC
        collectorNumber = "9"
        artist = "Aaron Miller"
        flavorText = "\"As my kha, he is the source of my inspiration. As my brother, he is the embodiment of my aspirations.\"\n—Ajani Goldmane"
        imageUri = "https://cards.scryfall.io/normal/front/c/4/c410d530-e9fc-4dc0-a4bd-70bd70aaf0c7.jpg"
    }
}
