// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.exo.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Scrivener
 * {4}{U}
 * Creature — Human Wizard
 * 2/2
 * When this creature enters, you may return target instant card from your graveyard to your hand.
 */
val Scrivener = card("Scrivener") {
    manaCost = "{4}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Human Wizard"
    oracleText = "When this creature enters, you may return target instant card from your graveyard to your hand."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        optional = true
        val t = target(
            "target",
            TargetObject(filter = TargetFilter(GameObjectFilter.Instant.ownedByYou(), zone = Zone.GRAVEYARD))
        )
        effect = Effects.Move(t, Zone.HAND)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "46"
        artist = "Heather Hudson"
        flavorText = "\"History is a potent weapon.\"\n—Karn, silver golem"
        imageUri = "https://cards.scryfall.io/normal/front/8/b/8b236bba-160a-4637-a83e-8456834ce59f.jpg"
    }
}
