// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dka.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Drogskol Reaver
 * {5}{W}{U}
 * Creature — Spirit
 * 3/5
 * Flying
 * Double strike (This creature deals both first-strike and regular combat damage.)
 * Lifelink (Damage dealt by this creature also causes you to gain that much life.)
 * Whenever you gain life, draw a card.
 */
val DrogskolReaver = card("Drogskol Reaver") {
    manaCost = "{5}{W}{U}"
    colorIdentity = "WU"
    typeLine = "Creature — Spirit"
    oracleText = "Flying\nDouble strike (This creature deals both first-strike and regular combat damage.)\nLifelink (Damage dealt by this creature also causes you to gain that much life.)\nWhenever you gain life, draw a card."
    power = 3
    toughness = 5
    keywords(Keyword.FLYING, Keyword.DOUBLE_STRIKE, Keyword.LIFELINK)
    triggeredAbility {
        trigger = Triggers.YouGainLife
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.MYTHIC
        collectorNumber = "137"
        artist = "Vincent Proce"
        flavorText = "Wracked and warped with anguish, it obsessively seeks out other souls to hoard within its eternal prison."
        imageUri = "https://cards.scryfall.io/normal/front/a/f/af2d9e0b-6433-40a2-9847-9fa4e3c008c4.jpg"
    }
}
