// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dka.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Tower Geist
 * {3}{U}
 * Creature — Spirit
 * 2/2
 * Flying
 * When this creature enters, look at the top two cards of your library. Put one of them into your hand and the other into your graveyard.
 */
val TowerGeist = card("Tower Geist") {
    manaCost = "{3}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Spirit"
    oracleText = "Flying\nWhen this creature enters, look at the top two cards of your library. Put one of them into your hand and the other into your graveyard."
    power = 2
    toughness = 2
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Patterns.Library.lookAtTopAndKeep(count = DynamicAmount.Fixed(2), keepCount = DynamicAmount.Fixed(1))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "53"
        artist = "Izzy"
        flavorText = "Jenrik's tower is served by those who once sought to enter it uninvited."
        imageUri = "https://cards.scryfall.io/normal/front/c/9/c9e9f552-34b6-43a5-8ef8-9d5208f4cae0.jpg"
    }
}
