// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.avr.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Seraph of Dawn
 * {2}{W}{W}
 * Creature — Angel
 * 2/4
 * Flying, lifelink
 */
val SeraphOfDawn = card("Seraph of Dawn") {
    manaCost = "{2}{W}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Angel"
    oracleText = "Flying, lifelink"
    power = 2
    toughness = 4
    keywords(Keyword.FLYING, Keyword.LIFELINK)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "35"
        artist = "Todd Lockwood"
        flavorText = "She parts the clouds so sunlight can reach even the darkest lairs and duskiest tombs."
        imageUri = "https://cards.scryfall.io/normal/front/5/d/5da345bd-8f2b-4966-97f5-c0e4c6cfe3b7.jpg"
    }
}
