// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.xln.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Bishop's Soldier
 * {1}{W}
 * Creature — Vampire Soldier
 * 2/2
 * Lifelink (Damage dealt by this creature also causes you to gain that much life.)
 */
val BishopsSoldier = card("Bishop's Soldier") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Vampire Soldier"
    oracleText = "Lifelink (Damage dealt by this creature also causes you to gain that much life.)"
    power = 2
    toughness = 2
    keywords(Keyword.LIFELINK)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "6"
        artist = "Scott Murphy"
        flavorText = "Vampires, the noble class of old Torrezon, are guided by their dual loyalties to church and crown."
        imageUri = "https://cards.scryfall.io/normal/front/d/9/d954677c-2de6-440a-90d0-bab2e0c8b4af.jpg"
    }
}
