// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.xln.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Dive Down
 * {U}
 * Instant
 * Target creature you control gets +0/+3 and gains hexproof until end of turn. (It can't be the target of spells or abilities your opponents control.)
 */
val DiveDown = card("Dive Down") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Target creature you control gets +0/+3 and gains hexproof until end of turn. (It can't be the target of spells or abilities your opponents control.)"
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.youControl()))
        effect = Effects.Composite(
            Effects.ModifyStats(0, 3, t),
            Effects.GrantKeyword(Keyword.HEXPROOF, t)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "53"
        artist = "Magali Villeneuve"
        flavorText = "\"Seeing the river is not the same as seeing the fish.\""
        imageUri = "https://cards.scryfall.io/normal/front/b/3/b33e493e-1aef-43b3-9716-52158b002430.jpg"
    }
}
