// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dmu.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Resolute Reinforcements
 * {1}{W}
 * Creature — Human Soldier
 * 1/1
 * Flash (You may cast this spell any time you could cast an instant.)
 * When this creature enters, create a 1/1 white Soldier creature token.
 */
val ResoluteReinforcements = card("Resolute Reinforcements") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Soldier"
    oracleText = "Flash (You may cast this spell any time you could cast an instant.)\nWhen this creature enters, create a 1/1 white Soldier creature token."
    power = 1
    toughness = 1
    keywords(Keyword.FLASH)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = Effects.CreateToken(
            power = 1,
            toughness = 1,
            colors = setOf(Color.WHITE),
            creatureTypes = setOf("Soldier")
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "29"
        artist = "Billy Christian"
        flavorText = "Morale rarely survives the sudden appearance of a squad of Sursi skirmishers at an army's flank."
        imageUri = "https://cards.scryfall.io/normal/front/3/e/3e11ad33-b9d7-43ef-840a-61955683b599.jpg"
    }
}
