// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.m14.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggerBinding


/**
 * Sporemound
 * {3}{G}{G}
 * Creature — Fungus
 * 3/3
 * Landfall — Whenever a land you control enters, create a 1/1 green Saproling creature token.
 */
val Sporemound = card("Sporemound") {
    manaCost = "{3}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Fungus"
    oracleText = "Landfall — Whenever a land you control enters, create a 1/1 green Saproling creature token."
    power = 3
    toughness = 3
    triggeredAbility {
        trigger = Triggers.entersBattlefield(filter = GameObjectFilter.Land.youControl(), binding = TriggerBinding.ANY)
        effect = Effects.CreateToken(
            power = 1,
            toughness = 1,
            colors = setOf(Color.GREEN),
            creatureTypes = setOf("Saproling")
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "196"
        artist = "Svetlin Velinov"
        flavorText = "\"If you threaten its territory, it produces spores. Actually, no matter what you do, it produces spores.\"\n—Hadi Kasten, Calla Dale naturalist"
        imageUri = "https://cards.scryfall.io/normal/front/2/d/2d256cd0-6fe9-4905-9886-fb1457292db5.jpg"
    }
}
