// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.zen.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Kor Cartographer
 * {3}{W}
 * Creature — Kor Scout
 * 2/2
 * When this creature enters, you may search your library for a Plains card, put it onto the battlefield tapped, then shuffle.
 */
val KorCartographer = card("Kor Cartographer") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Kor Scout"
    oracleText = "When this creature enters, you may search your library for a Plains card, put it onto the battlefield tapped, then shuffle."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        optional = true
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.Land.withSubtype(Subtype.PLAINS),
            destination = SearchDestination.BATTLEFIELD,
            entersTapped = true
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "18"
        artist = "Ryan Pancoast"
        flavorText = "Kor have no concept of exploration. They return to homelands forgotten."
        imageUri = "https://cards.scryfall.io/normal/front/6/0/6063b7ee-94ae-4a5b-9902-6aa0335af593.jpg"
    }
}
