// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.roe.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Dreamstone Hedron
 * {6}
 * Artifact
 * {T}: Add {C}{C}{C}.
 * {3}, {T}, Sacrifice this artifact: Draw three cards.
 */
val DreamstoneHedron = card("Dreamstone Hedron") {
    manaCost = "{6}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{T}: Add {C}{C}{C}.\n{3}, {T}, Sacrifice this artifact: Draw three cards."
    activatedAbility {
        cost = Costs.Tap
        effect = Effects.AddColorlessMana(3)
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{3}"), Costs.Tap, Costs.SacrificeSelf)
        effect = DrawCardsEffect(3)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "216"
        artist = "Eric Deschamps"
        flavorText = "Only the Eldrazi mind thinks in the warped paths required to open the hedrons and tap the power within."
        imageUri = "https://cards.scryfall.io/normal/front/7/9/79090d66-19ab-456e-96c0-023c84f4e521.jpg"
    }
}
