// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ice.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Mountain Goat
 * {R}
 * Creature — Goat
 * 1/1
 * Mountainwalk (This creature can't be blocked as long as defending player controls a Mountain.)
 */
val MountainGoat = card("Mountain Goat") {
    manaCost = "{R}"
    colorIdentity = "R"
    typeLine = "Creature — Goat"
    power = 1
    toughness = 1
    keywords(Keyword.MOUNTAINWALK)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "203"
        artist = "Cornelius Brudi"
        flavorText = "\"Folkore has it that to capture a Mountain Goat is a sign of divine blessing. I just know it's a sign that dinner is on the way.\"\n—Klazina Jansdotter, Leader of the Order of the Sacred Torch"
        imageUri = "https://cards.scryfall.io/normal/front/c/c/ccf70276-a40c-4d25-b584-4c8a07a00602.jpg"
    }
}
