// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Ancestor's Chosen
 * {5}{W}{W}
 * Creature — Human Cleric
 * 4/4
 * First strike (This creature deals combat damage before creatures without first strike.)
 * When this creature enters, you gain 1 life for each card in your graveyard.
 */
val AncestorsChosen = card("Ancestor's Chosen") {
    manaCost = "{5}{W}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Cleric"
    oracleText = "First strike (This creature deals combat damage before creatures without first strike.)\nWhen this creature enters, you gain 1 life for each card in your graveyard."
    power = 4
    toughness = 4
    keywords(Keyword.FIRST_STRIKE)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = GainLifeEffect(DynamicAmount.Count(Player.You, Zone.GRAVEYARD, GameObjectFilter.Any))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "1"
        artist = "Pete Venters"
        flavorText = "Empowered by generations of strength."
        imageUri = "https://cards.scryfall.io/normal/front/c/0/c0cf71e1-3c57-47f9-a4ef-e0d0ad1ee329.jpg"
    }
}
