// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetPermanent


/**
 * Aven Fogbringer
 * {3}{U}
 * Creature — Bird Wizard
 * 2/1
 * Flying
 * When this creature enters, return target land to its owner's hand.
 */
val AvenFogbringer = card("Aven Fogbringer") {
    manaCost = "{3}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Bird Wizard"
    oracleText = "Flying\nWhen this creature enters, return target land to its owner's hand."
    power = 2
    toughness = 1
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetPermanent(filter = TargetFilter.Land))
        effect = Effects.Move(t, Zone.HAND)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "34"
        artist = "Edward P. Beard, Jr."
        flavorText = "\"I cover the land with blankets and it sleeps.\""
        imageUri = "https://cards.scryfall.io/normal/front/c/0/c0ee9e09-c4b1-4133-90a3-350677f0b72a.jpg"
    }
}
