// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Cabal Trainee
 * {B}
 * Creature — Human Minion
 * 1/1
 * Sacrifice this creature: Target creature gets -2/-0 until end of turn.
 */
val CabalTrainee = card("Cabal Trainee") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Creature — Human Minion"
    oracleText = "Sacrifice this creature: Target creature gets -2/-0 until end of turn."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.SacrificeSelf
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(-2, 0, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "63"
        artist = "Pete Venters"
        flavorText = "\"Ah, a faceshredder. Very rare. Nearly unstoppable. Good luck!\"\n—Cabal instructor"
        imageUri = "https://cards.scryfall.io/normal/front/d/3/d345d702-b205-4391-985a-6201e707f0ba.jpg"
    }
}
