// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Defy Gravity
 * {U}
 * Instant
 * Target creature gains flying until end of turn.
 * Flashback {U} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val DefyGravity = card("Defy Gravity") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Target creature gains flying until end of turn.\nFlashback {U} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.GrantKeyword(Keyword.FLYING, t)
    }
    keywordAbility(KeywordAbility.flashback("{U}"))
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "38"
        artist = "Ben Thompson"
        flavorText = "Magical or not, it's still a cloud."
        imageUri = "https://cards.scryfall.io/normal/front/4/6/461413fe-0392-41c1-b50f-05e87ea1c338.jpg"
    }
}
