// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Ember Shot
 * {6}{R}
 * Instant
 * Ember Shot deals 3 damage to any target.
 * Draw a card.
 */
val EmberShot = card("Ember Shot") {
    manaCost = "{6}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Ember Shot deals 3 damage to any target.\nDraw a card."
    spell {
        val t = target("target", AnyTarget())
        effect = Effects.Composite(
            DealDamageEffect(3, t),
            DrawCardsEffect(1)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "87"
        artist = "Alan Pollack"
        flavorText = "Dwarves bring poor coal to market, use good coal in their homes, and throw their best coal away."
        imageUri = "https://cards.scryfall.io/normal/front/6/a/6a9eb72b-9ae2-4b64-bbb9-187446b5fd2f.jpg"
    }
}
