// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.targets.AnyTarget


/**
 * Jeska, Warrior Adept
 * {2}{R}{R}
 * Legendary Creature — Human Barbarian Warrior
 * 3/1
 * First strike, haste
 * {T}: Jeska deals 1 damage to any target.
 */
val JeskaWarriorAdept = card("Jeska, Warrior Adept") {
    manaCost = "{2}{R}{R}"
    colorIdentity = "R"
    typeLine = "Legendary Creature — Human Barbarian Warrior"
    oracleText = "First strike, haste\n{T}: Jeska deals 1 damage to any target."
    power = 3
    toughness = 1
    keywords(Keyword.FIRST_STRIKE, Keyword.HASTE)
    activatedAbility {
        cost = Costs.Tap
        val t = target("target", AnyTarget())
        effect = DealDamageEffect(1, t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "93"
        artist = "rk post"
        flavorText = "\"My brother and I both come from Balthor's forge. Kamahl has a temper of fire. I have a temper of steel.\""
        imageUri = "https://cards.scryfall.io/normal/front/1/c/1cf96a59-8b7d-4a5b-adfd-17eeedd95db5.jpg"
    }
}
