// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.MayEffect


/**
 * Krosan Wayfarer
 * {G}
 * Creature — Human Druid
 * 1/1
 * Sacrifice this creature: You may put a land card from your hand onto the battlefield.
 */
val KrosanWayfarer = card("Krosan Wayfarer") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Creature — Human Druid"
    oracleText = "Sacrifice this creature: You may put a land card from your hand onto the battlefield."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.SacrificeSelf
        effect = MayEffect(Patterns.Hand.putFromHand(filter = GameObjectFilter.Land))
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "123"
        artist = "Edward P. Beard, Jr."
        flavorText = "\"The Krosan Forest lives, and druids are its seeds.\"\n—Seton, centaur druid"
        imageUri = "https://cards.scryfall.io/normal/front/5/3/5356e684-c2fc-465e-a16c-7300824d2a8d.jpg"
    }
}
