// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Liberated Dwarf
 * {R}
 * Creature — Dwarf
 * 1/1
 * {R}, Sacrifice this creature: Target green creature gets +1/+0 and gains first strike until end of turn.
 */
val LiberatedDwarf = card("Liberated Dwarf") {
    manaCost = "{R}"
    colorIdentity = "R"
    typeLine = "Creature — Dwarf"
    oracleText = "{R}, Sacrifice this creature: Target green creature gets +1/+0 and gains first strike until end of turn."
    power = 1
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{R}"), Costs.SacrificeSelf)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.withColor(Color.GREEN)))
        effect = Effects.Composite(
            Effects.ModifyStats(1, 0, t),
            Effects.GrantKeyword(Keyword.FIRST_STRIKE, t)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "95"
        artist = "Greg Hildebrandt"
        flavorText = "Freed from their chains, these dwarves are bound only by honor."
        imageUri = "https://cards.scryfall.io/normal/front/e/2/e2c07842-9b70-40b1-9b97-9a9279b7ebc4.jpg"
    }
}
