// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Nomad Mythmaker
 * {2}{W}
 * Creature — Human Nomad Cleric
 * 2/2
 * {W}, {T}: Put target Aura card from a graveyard onto the battlefield under your control attached to a creature you control.
 */
val NomadMythmaker = card("Nomad Mythmaker") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Nomad Cleric"
    oracleText = "{W}, {T}: Put target Aura card from a graveyard onto the battlefield under your control attached to a creature you control."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{W}"), Costs.Tap)
        val t = target("target", TargetObject(filter = TargetFilter.CardInGraveyard))
        effect = Effects.PutOntoBattlefieldUnderYourControl(t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "15"
        artist = "Eric Peterson"
        flavorText = "Nomads weave tales thicker than tapestries."
        imageUri = "https://cards.scryfall.io/normal/front/9/a/9a5694fe-57d2-4359-857a-63213d986747.jpg"
    }
}
