// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Serene Sunset
 * {X}{G}
 * Instant
 * Prevent all combat damage X target creatures would deal this turn.
 */
val SereneSunset = card("Serene Sunset") {
    manaCost = "{X}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Prevent all combat damage X target creatures would deal this turn."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.PreventAllCombatDamage()
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "131"
        artist = "David Martin"
        flavorText = "The armies paused, silent, as the warriors reflected on the sunsets of their youth."
        imageUri = "https://cards.scryfall.io/normal/front/0/a/0a6ded26-b748-406d-8740-9b8590be2bb1.jpg"
    }
}
