// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Thriss, Nantuko Primus
 * {5}{G}{G}
 * Legendary Creature — Insect Druid
 * 5/5
 * {G}, {T}: Target creature gets +5/+5 until end of turn.
 */
val ThrissNantukoPrimus = card("Thriss, Nantuko Primus") {
    manaCost = "{5}{G}{G}"
    colorIdentity = "G"
    typeLine = "Legendary Creature — Insect Druid"
    oracleText = "{G}, {T}: Target creature gets +5/+5 until end of turn."
    power = 5
    toughness = 5
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{G}"), Costs.Tap)
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = Effects.ModifyStats(5, 5, t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "134"
        artist = "John Avon"
        flavorText = "\"When you live for others, you live for yourself.\""
        imageUri = "https://cards.scryfall.io/normal/front/a/d/ad9e647d-903f-4a77-a56c-cd5c0c2f12cf.jpg"
    }
}
