// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.kld.cards

import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect


/**
 * Filigree Familiar
 * {3}
 * Artifact Creature — Fox
 * 2/2
 * When this creature enters, you gain 2 life.
 * When this creature dies, draw a card.
 */
val FiligreeFamiliar = card("Filigree Familiar") {
    manaCost = "{3}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Fox"
    oracleText = "When this creature enters, you gain 2 life.\nWhen this creature dies, draw a card."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        effect = GainLifeEffect(2)
    }
    triggeredAbility {
        trigger = Triggers.Dies
        effect = DrawCardsEffect(1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "212"
        artist = "Izzy"
        flavorText = "\"It's the must-have gift for everyone on your list. Get one for yourself, too!\"\n—Chammi, curio vendor"
        imageUri = "https://cards.scryfall.io/normal/front/9/c/9cc9ecfd-6cf0-4488-a14a-afec1bc0d253.jpg"
    }
}
